import {useEffect,useMemo,useState} from 'react';
import {useAppServices} from '../services/context';
import {asset} from '../segmented/types';
import {examSessions} from '../learning/examRegistry';
import type {WrongQuestionState} from '../learning/wrongQuestions';
import {classificationCounts,filterInventory,needsClassificationReview,type BankFilters} from './model';
import {useBankData} from './useBankData';
import './bank.css';
export default function BankView({wrongOnly=false}:{wrongOnly?:boolean}){
 const {data,error}=useBankData(),{repository,user}=useAppServices();const [wrong,setWrong]=useState<WrongQuestionState[]>([]),[personalError,setPersonalError]=useState('');
 const [group,setGroup]=useState<'knowledge'|'question_type'>('knowledge'),[topic,setTopic]=useState(''),[type,setType]=useState(''),[module,setModule]=useState(''),[year,setYear]=useState(''),[kind,setKind]=useState(''),[unknown,setUnknown]=useState(false),[onlyWrong,setOnlyWrong]=useState(wrongOnly),[minimum,setMinimum]=useState(1),[page,setPage]=useState(0);
 useEffect(()=>{let alive=true;const refresh=()=>void repository.getWrongQuestions(user.id).then(rows=>{if(alive){setWrong(rows);setPersonalError('')}}).catch(e=>{if(alive)setPersonalError(String(e))});refresh();window.addEventListener('ap2:personal-data-changed',refresh);return()=>{alive=false;window.removeEventListener('ap2:personal-data-changed',refresh)}},[repository,user.id,wrongOnly]);
 const active=wrong.filter(w=>w.active&&w.wrong_count>=minimum);const wrongIds=active.map(w=>w.question_id);
 const filters:BankFilters={knowledgeTopicIds:topic?[topic]:[],questionTypeIds:type?[type]:[],modules:module?[module]:[],examIds:year?[year]:[],kind:kind as BankFilters['kind']||undefined,unclassified:unknown,wrongOnly:wrongOnly||onlyWrong,wrongQuestionIds:wrongIds};
 const results=data?filterInventory(data.inventory,data.classifications,filters,data.taxonomy):[];
 useEffect(()=>setPage(p=>Math.min(p,Math.max(0,Math.ceil(results.length/24)-1))),[results.length]);
 const cMap=useMemo(()=>new Map(data?.classifications.map(c=>[c.question_id,c])),[data]);
 useEffect(()=>setPage(0),[topic,type,module,year,kind,unknown,onlyWrong,minimum]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Aufgabenbank wird geladen…</p>;
 const taxonomy=data.taxonomy.nodes.filter(n=>n.active),knowledge=taxonomy.filter(n=>n.kind==='knowledge'),types=taxonomy.filter(n=>n.kind==='question_type'),counts=classificationCounts(data.inventory,data.classifications);
 const facet=taxonomy.filter(n=>n.kind===group).map(node=>({node,count:filterInventory(data.inventory,data.classifications,{...filters,...(group==='knowledge'?{knowledgeTopicIds:[node.id]}:{questionTypeIds:[node.id]})},data.taxonomy).length})).filter(n=>n.count>0);
 const hide=async(id:string)=>{try{await repository.hideWrongQuestion(user.id,id);setWrong(await repository.getWrongQuestions(user.id))}catch(e){setPersonalError(String(e))}};
 return <section className="bank"><h1>{wrongOnly?'Fehlerfragen':'Aufgabenbank'}</h1><p>{wrongOnly?'Falsche und teilweise richtige Abgaben. Nach zwei aufeinanderfolgenden richtigen Abgaben wird die Aufgabe ausgeblendet.':'Originalaufgaben aus allen freigegebenen Prüfungen. Ungeprüfte Klassifikationen sind Vorschläge.'}</p>{personalError&&<p role="alert">{personalError}</p>}
 {!wrongOnly&&<p className="bank-coverage">{counts.total} Aufgaben · {counts.knowledgeClassified} mit Wissensgebiet · {counts.unclassified} noch nicht vollständig klassifiziert · <a href={asset('?view=classification-review')}>Klassifikation prüfen ({counts.review})</a></p>}
 <div className="bank-modes"><button className={group==='knowledge'?'primary':'outline'} onClick={()=>setGroup('knowledge')}>Nach Wissensgebiet</button><button className={group==='question_type'?'primary':'outline'} onClick={()=>setGroup('question_type')}>Nach Aufgabentyp</button></div>
 <div className="bank-facets" aria-label="Kategorien"><button className="outline" onClick={()=>{setTopic('');setType('');setUnknown(false)}}>Alle Aufgaben</button>{facet.map(({node,count})=><button className="outline" key={node.id} aria-pressed={group==='knowledge'?topic===node.id:type===node.id} onClick={()=>{if(group==='knowledge')setTopic(topic===node.id?'':node.id);else setType(type===node.id?'':node.id);setUnknown(false)}}>{node.label} <strong>{count}</strong></button>)}<button className="outline" aria-pressed={unknown} onClick={()=>{setUnknown(v=>!v);setTopic('');setType('')}}>Unklassifiziert / unvollständig</button></div>
 <div className="bank-filters"><label>Wissensgebiet<select aria-label="Wissensgebiet" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Alle Wissensgebiete</option>{knowledge.map(n=><option key={n.id} value={n.id}>{n.parent_id?'↳ ':''}{n.label}</option>)}</select></label><label>Aufgabentyp<select aria-label="Aufgabentyp" value={type} onChange={e=>setType(e.target.value)}><option value="">Alle Aufgabentypen</option>{types.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label>Modul<select aria-label="Modul" value={module} onChange={e=>setModule(e.target.value)}><option value="">Alle Module</option>{[...new Map(data.inventory.map(q=>[q.module,q.moduleTitle])).entries()].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Jahrgang<select aria-label="Jahrgang" value={year} onChange={e=>setYear(e.target.value)}><option value="">Alle Jahre</option>{examSessions(data.inventory).map(y=><option key={y.id} value={y.id}>{y.label}</option>)}</select></label><label>Format<select aria-label="Format" value={kind} onChange={e=>setKind(e.target.value)}><option value="">MC und U</option><option value="multiple_choice">MC</option><option value="multi_part">U</option></select></label>{!wrongOnly&&<label className="bank-check"><input type="checkbox" checked={onlyWrong} onChange={e=>setOnlyWrong(e.target.checked)}/>Nur Fehlerfragen</label>}{(wrongOnly||onlyWrong)&&<label>Mindestens so oft falsch<input type="number" min="1" max="9999" value={minimum} onChange={e=>setMinimum(Math.max(1,Number(e.target.value)||1))}/></label>}</div>
 <p role="status" data-testid="bank-count">{results.length} Aufgaben gefunden</p>{results.length===0&&<p>Keine passenden Aufgaben. Filter ändern oder weiterlernen.</p>}
 <div className="bank-results">{results.slice(page*24,page*24+24).map(q=>{const c=cMap.get(q.question_id),state=wrong.find(w=>w.question_id===q.question_id);return <article className="bank-question" key={q.question_id} data-question-id={q.question_id}><h2>{q.examLabel} · {q.moduleTitle} · {q.kind==='multiple_choice'?'Q':''}{q.number}</h2><p>{c?.knowledge_topic_ids.map(id=>taxonomy.find(n=>n.id===id)?.label??id).join(' · ')||'Wissensgebiet noch unklassifiziert'} · {taxonomy.find(n=>n.id===c?.primary_question_type_id)?.label??'Aufgabentyp offen'}</p>{(!c||needsClassificationReview(c))&&<small>Klassifikation ungeprüft / unvollständig</small>}{state?.active&&<p>{state.wrong_count} falsche/teilweise Abgaben · {state.consecutive_correct}/2 zuletzt richtig</p>}<div className="bank-actions"><a className="primary" href={asset(`?view=study&exam=${encodeURIComponent(q.examId)}&module=${encodeURIComponent(q.module)}&q=${encodeURIComponent(q.number)}`)}>Aufgabe lernen</a><details><summary>Originalaufgabe ansehen</summary><img loading="lazy" src={asset(q.crop)} alt={`Originalaufgabe ${q.number}`}/></details>{(wrongOnly||onlyWrong)&&<button className="outline" onClick={()=>void hide(q.question_id)}>Ausblenden</button>}<a className="bank-review-link" href={asset('?view=classification-review&item='+encodeURIComponent(q.question_id))}>Klassifikation</a></div></article>})}</div>
 {results.length>24&&<div className="bank-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>← Zurück</button><span>Seite {page+1} / {Math.ceil(results.length/24)}</span><button disabled={(page+1)*24>=results.length} onClick={()=>setPage(p=>p+1)}>Weiter →</button></div>}</section>;
}
