import {useEffect,useState} from 'react';
import {useAppServices} from '../services/context';
import {asset} from '../segmented/types';
import {useBankData} from './useBankData';
import {classificationOverrideExport,needsClassificationReview,parseClassificationOverrides} from './model';
import {confirmClassification,downloadJSON} from './review';
import './bank.css';
export default function ClassificationReview(){
 const {data,error,save}=useBankData(),{user}=useAppServices();const [id,setId]=useState(()=>new URLSearchParams(location.search).get('item')??''),[topics,setTopics]=useState<string[]>([]),[primary,setPrimary]=useState(''),[secondary,setSecondary]=useState<string[]>([]),[add,setAdd]=useState(''),[message,setMessage]=useState(''),[failure,setFailure]=useState(''),[imageReady,setImageReady]=useState(false),[proposal,setProposal]=useState(''),[proposalKind,setProposalKind]=useState<'knowledge'|'question_type'>('knowledge'),[showAll,setShowAll]=useState(false);
 const [proposals,setProposals]=useState<{id:string;label:string;kind:string;question_id:string}[]>([]);
 const proposalKey='ap2:technical-review:taxonomy-proposals:'+user.id;
 useEffect(()=>{try{setProposals(JSON.parse(localStorage.getItem(proposalKey)??'[]'))}catch{setFailure('Taxonomievorschläge konnten nicht gelesen werden.')}} ,[proposalKey]);
 const q=data?.inventory.find(q=>q.question_id===id),c=data?.classifications.find(c=>c.question_id===id);
 useEffect(()=>{if(data&&!q)setId(data.inventory.find(q=>needsClassificationReview(data.classifications.find(c=>c.question_id===q.question_id)!))?.question_id??data.inventory[0]?.question_id??'')},[data,q]);
 useEffect(()=>{setTopics(c?.knowledge_topic_ids??[]);setPrimary(c?.primary_question_type_id??'');setSecondary(c?.secondary_question_type_ids??[]);setMessage('');setImageReady(false);setFailure('')},[id]);
 // Data loads asynchronously; initialize the first selected record when it becomes available.
 useEffect(()=>{if(c){setTopics(c.knowledge_topic_ids);setPrimary(c.primary_question_type_id??'');setSecondary(c.secondary_question_type_ids)}},[c?.question_id]);
 const dirty=JSON.stringify(topics)!==JSON.stringify(c?.knowledge_topic_ids??[])||primary!==(c?.primary_question_type_id??'')||JSON.stringify(secondary)!==JSON.stringify(c?.secondary_question_type_ids??[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 useEffect(()=>{const pop=()=>{const next=new URLSearchParams(location.search).get('item')??'';if(dirty&&!window.confirm('Ungespeicherte Klassifikation verwerfen?')){const url=new URL(location.href);url.searchParams.set('item',id);history.pushState(null,'',url);return}setId(next)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[dirty,id]);
 if(error)return <p role="alert">{error}</p>;if(!data||!q||!c)return <p role="status">Klassifikation wird geladen…</p>;
 const nodes=data.taxonomy.nodes.filter(n=>n.active),knowledge=nodes.filter(n=>n.kind==='knowledge'),types=nodes.filter(n=>n.kind==='question_type');
 const pending=data.classifications.filter(needsClassificationReview),queue=data.inventory.filter(q=>showAll||q.question_id===id||pending.some(c=>c.question_id===q.question_id)),index=queue.findIndex(q=>q.question_id===id);
 const move=(next:string)=>{if(dirty&&!window.confirm('Ungespeicherte Klassifikation verwerfen?'))return;const url=new URL(location.href);url.searchParams.set('item',next);history.pushState(null,'',url);setId(next)};
 const confirm=()=>{try{save([confirmClassification(q,topics,primary||null,secondary,data.taxonomy.version,new Date().toISOString())]);setMessage('Gespeichert · menschlich bestätigt · gesperrt');setFailure('')}catch(e){setFailure(String(e))}};
 const propose=()=>{try{const label=proposal.trim();if(!label)return;const list=JSON.parse(localStorage.getItem(proposalKey)??'[]');list.push({id:crypto.randomUUID(),kind:proposalKind,label,status:'proposed_new_taxonomy_node',question_id:q.question_id,question_source_revision:q.question_source_revision,created_at:new Date().toISOString()});localStorage.setItem(proposalKey,JSON.stringify(list));setProposals(list);setProposal('');setMessage('Vorschlag gespeichert. Erst nach Prüfung wird die Taxonomie erweitert.')}catch(e){setFailure(String(e))}};
 const exportAll=()=>{try{downloadJSON('classification-confirmations.json',{...classificationOverrideExport(data.overrides),proposed_new_taxonomy_nodes:JSON.parse(localStorage.getItem(proposalKey)??'[]')})}catch(e){setFailure(String(e))}};
 const importFile=async(file:File)=>{try{const rows=parseClassificationOverrides(JSON.parse(await file.text()),data.taxonomy,data.inventory);save(rows);setMessage(`${rows.length} gültige Bestätigungen importiert.`)}catch(e){setFailure(String(e))}};
 return <section className="bank classification-review"><h1>Klassifikation</h1><p>{pending.length} Prüfaufträge · <a href={asset('?view=review-queue')}>Historische Quellen-Review Queue (unverändert)</a></p><p>Originalbild prüfen, Wissensgebiete und Aufgabentyp bestätigen. Die Bestätigung bleibt lokal gesperrt; Export dient der geprüften Veröffentlichung.</p><div className="bank-actions"><button className="outline" onClick={exportAll}>Bestätigungen exportieren</button><label>Bestätigungen importieren<input type="file" accept="application/json,.json" onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);e.target.value=''}}/></label><label><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/>Auch bestätigte Aufgaben</label></div>
 <details><summary>Taxonomie-Vorschläge zur Prüfung ({proposals.length})</summary>{proposals.length===0?<p>Keine offenen Vorschläge.</p>:proposals.map(n=><p key={n.id}>{n.label} · {n.kind==='knowledge'?'Wissensgebiet':'Aufgabentyp'} · {n.question_id} · vorgeschlagen, noch nicht aktiv</p>)}<p>Vorschläge werden separat im Export erhalten und erst nach redaktioneller Prüfung in die Taxonomiedaten übernommen.</p></details><label>Aufgabe<select aria-label="Aufgabe" value={id} onChange={e=>move(e.target.value)}>{queue.map(q=><option key={q.question_id} value={q.question_id}>{q.examLabel} · {q.moduleTitle} · {q.number}</option>)}</select></label><h2>{q.examLabel} · {q.moduleTitle} · {q.number}</h2><div className="classification-columns"><div><img className="classification-crop" src={asset(q.crop)} alt={`Originalaufgabe ${q.number}`} onLoad={()=>setImageReady(true)} onError={()=>{setImageReady(false);setFailure('Originalbild konnte nicht geladen werden. Bitte neu laden.')}}/></div><div><p>{c.source==='human_confirmed'?'Menschlich bestätigt':'Maschinenvorschlag'} · Sicherheit {Math.round(c.confidence*100)}%{c.locked?' · gesperrt':''}</p>{c.review_reasons.length>0&&<p>Prüfgründe: {c.review_reasons.map(r=>({knowledge_unclassified:'Wissensgebiet offen',question_type_unclassified:'Aufgabentyp offen',candidate_requires_confirmation:'Vorschlag prüfen',text_not_trustworthy:'Kein zuverlässiger Text',source_changed_since_confirmation:'Originalquelle seit Bestätigung geändert',taxonomy_changed_since_confirmation:'Taxonomie seit Bestätigung geändert'}[r]??r)).join(' · ')}</p>}
 <h3>Wissensgebiete</h3>{topics.length===0&&<p>Noch nicht klassifiziert</p>}{topics.map(topic=><div className="bank-topic" key={topic}><span>{data.taxonomy.nodes.find(n=>n.id===topic)?.label??topic}</span><button className="outline" onClick={()=>setTopics(v=>v.filter(id=>id!==topic))}>Entfernen</button></div>)}<label>Wissensgebiet hinzufügen<select aria-label="Wissensgebiet hinzufügen" value={add} onChange={e=>setAdd(e.target.value)}><option value="">Bitte auswählen</option>{knowledge.filter(n=>!topics.includes(n.id)).map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><button className="outline" disabled={!add} onClick={()=>{setTopics(v=>[...v,add]);setAdd('')}}>Hinzufügen</button>
 <label>Primärer Aufgabentyp<select aria-label="Primärer Aufgabentyp" value={primary} onChange={e=>{setPrimary(e.target.value);setSecondary(s=>s.filter(id=>id!==e.target.value))}}><option value="">Noch offen</option>{primary&&!types.some(n=>n.id===primary)&&<option value={primary}>{data.taxonomy.nodes.find(n=>n.id===primary)?.label??primary} (inaktiv — bitte ändern)</option>}{types.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><details><summary>Weitere Aufgabentypen</summary>{secondary.filter(id=>!types.some(n=>n.id===id)).map(id=><div className="bank-topic" key={id}><span>{data.taxonomy.nodes.find(n=>n.id===id)?.label??id} (inaktiv)</span><button onClick={()=>setSecondary(v=>v.filter(x=>x!==id))}>Entfernen</button></div>)}{types.filter(n=>n.id!==primary).map(n=><label className="bank-check" key={n.id}><input type="checkbox" checked={secondary.includes(n.id)} onChange={e=>setSecondary(v=>e.target.checked?[...v,n.id]:v.filter(id=>id!==n.id))}/>{n.label}</label>)}</details>
 <button className="primary" disabled={!imageReady} onClick={confirm}>Bestätigen / Änderung speichern</button><p role="status">{message}</p>{failure&&<p role="alert">{failure}</p>}
 <details><summary>Neuen Taxonomiebegriff vorschlagen</summary><label>Art<select aria-label="Art" value={proposalKind} onChange={e=>setProposalKind(e.target.value as 'knowledge'|'question_type')}><option value="knowledge">Wissensgebiet</option><option value="question_type">Aufgabentyp</option></select></label><label>Bezeichnung<input value={proposal} onChange={e=>setProposal(e.target.value)} maxLength={120}/></label><button className="outline" disabled={!proposal.trim()} onClick={propose}>Zur Prüfung vormerken</button><p>Keine automatische Erweiterung. Der Vorschlag wird mit den Bestätigungen exportiert.</p></details><small>Quellenrevision: {q.question_source_revision}</small></div></div><div className="bank-pagination"><button disabled={index<=0} onClick={()=>move(queue[index-1].question_id)}>← Previous</button><span>{index+1} / {queue.length}</span><button disabled={index>=queue.length-1} onClick={()=>move(queue[index+1].question_id)}>Next →</button></div></section>;
}
