export interface InventoryQuestion {question_id:string;examId:string;examLabel:string;module:string;moduleTitle:string;number:string;kind:'multiple_choice'|'multi_part';crop:string;text:string;extraction_confidence:number;question_source_revision:string}
export interface TaxonomyNode {id:string;kind:'knowledge'|'question_type';label:string;parent_id:string|null;active:boolean;aliases:string[];version:string;text_cues?:string[];module_cues?:string[];kind_cues?:InventoryQuestion['kind'][];merged_into?:string}
export interface Taxonomy {version:string;nodes:TaxonomyNode[]}
export interface QuestionClassification {question_id:string;question_source_revision:string;knowledge_topic_ids:string[];primary_question_type_id:string|null;secondary_question_type_ids:string[];source:'machine_suggested'|'human_confirmed';confidence:number;taxonomy_version:string;locked:boolean;updated_at:string;active:boolean;review_reasons:string[]}
export interface BankFilters {knowledgeTopicIds?:string[];questionTypeIds?:string[];modules?:string[];examIds?:string[];kind?:InventoryQuestion['kind'];unclassified?:boolean;wrongOnly?:boolean;wrongQuestionIds?:Iterable<string>}
function exceptionReasons(c:QuestionClassification){return c.review_reasons.filter(reason=>!['candidate_requires_confirmation','text_not_trustworthy','taxonomy_changed_since_confirmation'].includes(reason)&&(c.source==='human_confirmed'||!['knowledge_unclassified','question_type_unclassified'].includes(reason)));}
export function needsClassificationReview(c:QuestionClassification){return c.active&&exceptionReasons(c).length>0;}
function candidate(q:InventoryQuestion,t:Taxonomy,now:string):QuestionClassification {
 const text=q.extraction_confidence>=0.8?q.text.toLocaleLowerCase('de'):'';
 const matches=t.nodes.filter(n=>n.active&&((n.module_cues??[]).includes(q.module)||(n.kind_cues??[]).includes(q.kind)||(n.text_cues??[]).some(c=>text.includes(c.toLocaleLowerCase('de')))));
 const knowledge=matches.filter(n=>n.kind==='knowledge').map(n=>n.id),types=matches.filter(n=>n.kind==='question_type').map(n=>n.id);
 return {question_id:q.question_id,question_source_revision:q.question_source_revision,knowledge_topic_ids:knowledge,primary_question_type_id:types[0]??null,secondary_question_type_ids:types.slice(1),source:'machine_suggested',confidence:knowledge.length||types.length?0.65:0,taxonomy_version:t.version,locked:false,updated_at:now,active:true,review_reasons:[]};
}
export function reconcileClassifications(inventory:InventoryQuestion[],previous:QuestionClassification[],taxonomy:Taxonomy,now:string):QuestionClassification[]{
 const old=new Map(previous.map(c=>[c.question_id,c])); const active=new Set(inventory.map(q=>q.question_id));
 const records=inventory.map(q=>{const prior=old.get(q.question_id);if(!prior)return candidate(q,taxonomy,now);
 if(prior.source==='human_confirmed'&&prior.locked){const reasons=exceptionReasons(prior).filter(r=>r!=='source_changed_since_confirmation'&&r!=='taxonomy_labels_inactive');if(prior.question_source_revision!==q.question_source_revision)reasons.push('source_changed_since_confirmation');if([...prior.knowledge_topic_ids,prior.primary_question_type_id,...prior.secondary_question_type_ids].filter(Boolean).some(id=>!taxonomy.nodes.some(n=>n.id===id&&n.active)))reasons.push('taxonomy_labels_inactive');const same=prior.active&&JSON.stringify(reasons)===JSON.stringify(prior.review_reasons);return same?prior:{...prior,active:true,review_reasons:reasons,updated_at:now};}
 const reasons=exceptionReasons(prior);
 if(prior.active&&prior.question_source_revision===q.question_source_revision&&prior.taxonomy_version===taxonomy.version)return JSON.stringify(reasons)===JSON.stringify(prior.review_reasons)?prior:{...prior,review_reasons:reasons,updated_at:now};
 return {...candidate(q,taxonomy,now),review_reasons:reasons};});
 return [...records,...previous.filter(c=>!active.has(c.question_id)).map(c=>c.active?{...c,active:false,updated_at:now}:c)].sort((a,b)=>a.question_id.localeCompare(b.question_id));
}
export function filterInventory(inventory:InventoryQuestion[],classifications:QuestionClassification[],filters:BankFilters={},taxonomy?:Taxonomy):InventoryQuestion[]{
 const map=new Map(classifications.filter(c=>c.active).map(c=>[c.question_id,c]));const wrong=new Set(filters.wrongQuestionIds??[]);const expanded=(ids:string[])=>ids.flatMap(id=>[id,...(taxonomy?.nodes.filter(n=>n.active&&n.parent_id===id).map(n=>n.id)??[])]);
 return inventory.filter(q=>{const c=map.get(q.question_id),types=c?[c.primary_question_type_id,...c.secondary_question_type_ids]:[];return (!filters.modules?.length||filters.modules.includes(q.module))&&(!filters.examIds?.length||filters.examIds.includes(q.examId))&&(!filters.kind||q.kind===filters.kind)&&(!filters.knowledgeTopicIds?.length||expanded(filters.knowledgeTopicIds).some(id=>c?.knowledge_topic_ids.includes(id)))&&(!filters.questionTypeIds?.length||expanded(filters.questionTypeIds).some(id=>types.includes(id)))&&(!filters.unclassified||!c||!c.knowledge_topic_ids.length||!c.primary_question_type_id)&&(!filters.wrongOnly||wrong.has(q.question_id));});
}
export function classificationCounts(inventory:InventoryQuestion[],classifications:QuestionClassification[]){const ids=new Set(inventory.map(q=>q.question_id)),records=classifications.filter(c=>c.active&&ids.has(c.question_id));return {total:inventory.length,knowledgeClassified:records.filter(c=>c.knowledge_topic_ids.length).length,typeClassified:records.filter(c=>c.primary_question_type_id).length,unclassified:filterInventory(inventory,classifications,{unclassified:true}).length,review:records.filter(needsClassificationReview).length,confirmed:records.filter(c=>c.source==='human_confirmed'&&c.locked).length,orphans:classifications.filter(c=>!c.active).length};}
export function parseClassificationOverrides(value:unknown,taxonomy:Taxonomy,inventory:InventoryQuestion[],options:{allowStale?:boolean;allowOrphans?:boolean}={}):QuestionClassification[]{
 if(!value||typeof value!=='object'||(value as {schema_version?:unknown}).schema_version!==1||!Array.isArray((value as {classifications?:unknown}).classifications))throw new Error('Invalid classification export');
 const records=(value as {classifications:unknown[]}).classifications;const questions=new Map(inventory.map(q=>[q.question_id,q]));const seen=new Set<string>();
 return records.map(value=>{if(!value||typeof value!=='object')throw new Error('Invalid classification');const c=value as QuestionClassification;const q=questions.get(c.question_id);const validIds=(ids:unknown,kind:TaxonomyNode['kind'])=>Array.isArray(ids)&&new Set(ids).size===ids.length&&ids.every(id=>typeof id==='string'&&taxonomy.nodes.some(n=>n.id===id&&n.kind===kind&&(options.allowStale||n.active)));
 if((!q&&!options.allowOrphans)||typeof c.question_id!=='string'||!c.question_id||seen.has(c.question_id)||(!options.allowStale&&c.question_source_revision!==q?.question_source_revision)||typeof c.question_source_revision!=='string'||!c.question_source_revision||c.source!=='human_confirmed'||c.locked!==true||c.active!==true||(!options.allowStale&&c.taxonomy_version!==taxonomy.version)||!validIds(c.knowledge_topic_ids,'knowledge')||!validIds(c.secondary_question_type_ids,'question_type')||!(c.primary_question_type_id===null||validIds([c.primary_question_type_id],'question_type'))||!Number.isFinite(c.confidence)||c.confidence<0||c.confidence>1||typeof c.updated_at!=='string'||!Number.isFinite(Date.parse(c.updated_at))||!Array.isArray(c.review_reasons)||!c.review_reasons.every(r=>typeof r==='string'))throw new Error('Invalid, duplicate, stale or unknown classification override');seen.add(c.question_id);return {...c,knowledge_topic_ids:[...c.knowledge_topic_ids],secondary_question_type_ids:[...c.secondary_question_type_ids],review_reasons:[...c.review_reasons]};});
}
export function classificationOverrideExport(classifications:QuestionClassification[]){return {schema_version:1 as const,classifications:classifications.filter(c=>c.source==='human_confirmed'&&c.locked)};}


/** Taxonomy edits require a new version; retired IDs remain for audit, never silently disappear. */
export function validateTaxonomy(value:Taxonomy):void {
 if(!value||typeof value.version!=='string'||!value.version||!Array.isArray(value.nodes))throw new Error('Invalid taxonomy');
 const ids=new Set(value.nodes.map(n=>n.id));if(ids.size!==value.nodes.length)throw new Error('Duplicate taxonomy ID');
 for(const node of value.nodes){if(!node.id||!node.label||!['knowledge','question_type'].includes(node.kind)||typeof node.active!=='boolean'||!Array.isArray(node.aliases)||node.version!==value.version)throw new Error('Invalid taxonomy node');if(node.parent_id){const parent=value.nodes.find(n=>n.id===node.parent_id);if(!parent||parent.kind!==node.kind||parent.parent_id||parent.id===node.id)throw new Error('Taxonomy depth exceeds two or invalid parent');}if(node.merged_into&&!ids.has(node.merged_into))throw new Error('Unknown merge target');if(node.module_cues?.some(c=>c!=='wiso'))throw new Error('Only broad WiSo classification may use module metadata');}
}
