import 'fake-indexeddb/auto';
import {it,expect} from 'vitest';
import Dexie from 'dexie';
import {IndexedDBProgressRepository} from '../storage/storage';
import {FirestoreSyncProvider,type CloudAuth,type CloudTransport} from './FirestoreSyncProvider';
import type {SyncEnvelope,PushMutation} from './protocol';
const user={id:'google-a',mode:'remote' as const};
function auth(){let uid:string|null=user.id;const listeners=new Set<(a:any)=>void>();return {configured:true,account:()=>uid?{uid,email:'a@example.test',displayName:'A'}:null,currentUser:async()=>({id:uid??'local',mode:uid?'remote':'local'} as const),restoreSession:async()=>({id:uid??'local',mode:uid?'remote':'local'} as const),login:async()=>user,logout:async()=>{uid=null;listeners.forEach(f=>f(null));},onAuthChanged:(f:(a:any)=>void)=>{listeners.add(f);return()=>{listeners.delete(f);};},switch:(next:string)=>{uid=next;listeners.forEach(f=>f({uid}));}} satisfies CloudAuth&{switch:(uid:string)=>void};}
function cloud(){const records=new Map<string,SyncEnvelope>(),receipts=new Map<string,any>();let cursor=0;let offline=false;return {setOffline:(v:boolean)=>{offline=v;},records,transport:{async push(mutations:PushMutation[],uid?:string){if(offline)throw Error('offline');return {results:mutations.map(m=>{if(receipts.has(m.mutationId))return {...receipts.get(m.mutationId),status:'duplicate' as const};const key=uid+':'+m.entity+':'+m.id,old=records.get(key);if((old?.revision??0)!==m.baseRevision)return {mutationId:m.mutationId,status:'conflict' as const,record:old!};const record:SyncEnvelope={entity:m.entity,id:m.id,value:m.value,deleted:m.deleted,revision:(old?.revision??0)+1,cursor:++cursor,updatedAt:new Date().toISOString(),deviceId:'test-device'};records.set(key,record);const result={mutationId:m.mutationId,status:'applied' as const,record};receipts.set(m.mutationId,result);return result;})};},async pull(since:number,_limit?:number,uid?:string){const changes=[...records].filter(([k,r])=>k.startsWith(uid+':')&&r.cursor>since).map(([,r])=>r).sort((a,b)=>a.cursor-b.cursor);return {changes,cursor:changes.at(-1)?.cursor??since,hasMore:false};}} satisfies CloudTransport};}
async function pair(){const names=['sync-a-'+crypto.randomUUID(),'sync-b-'+crypto.randomUUID()],a=new IndexedDBProgressRepository(names[0]),b=new IndexedDBProgressRepository(names[1]),remote=cloud(),aa=auth(),ba=auth();return {a,b,remote,aa,ba,sa:new FirestoreSyncProvider(a,aa,remote.transport),sb:new FirestoreSyncProvider(b,ba,remote.transport),close:async()=>{a.close();b.close();for(const n of names)await Dexie.delete(n);}};}
it('two isolated devices retry offline, preserve conflicts, and explicitly resolve notes',async()=>{const x=await pair();try{
 x.remote.setOffline(true);await x.a.saveCorrection(user.id,'q','note','A offline');expect((await x.sa.sync(user)).status).toBe('error');expect(await x.a.getOutbox(user.id)).toHaveLength(1);x.remote.setOffline(false);await x.sa.sync(user);await x.sb.sync(user);expect((await x.b.get(user.id,'q'))?.fields.note.value).toBe('A offline');
 await x.a.saveCorrection(user.id,'q','note','A next');await x.b.saveCorrection(user.id,'q','note','B next');await x.sa.sync(user);expect((await x.sb.sync(user)).status).toBe('conflicts');expect((await x.b.get(user.id,'q'))?.fields.note.value).toBe('B next');const [c]=await x.sb.conflicts();await x.sb.resolveConflict(user,c,'local');await x.sa.sync(user);expect((await x.a.get(user.id,'q'))?.fields.note.value).toBe('B next');expect(await x.b.getOutbox(user.id)).toHaveLength(0);
 }finally{await x.close();}});
it('remote success before failed local ack retries idempotently without a conflict',async()=>{const x=await pair();try{await x.a.saveCorrection(user.id,'q','note','stable');const ack=x.a.acknowledge.bind(x.a);let once=true;x.a.acknowledge=async(...args)=>{if(once){once=false;throw Error('disk unavailable');}return ack(...args);};expect((await x.sa.sync(user)).status).toBe('error');expect((await x.sa.sync(user)).status).toBe('completed');expect(await x.a.getSyncConflicts(user.id)).toEqual([]);expect(x.remote.records.size).toBe(1);}finally{await x.close();}});
it('migration is explicit, retains original data and source provenance, and backup local-only does not queue remote',async()=>{const x=await pair();try{await x.a.saveCorrection('local','q','note','old');await x.sa.sync(user);expect(x.remote.records.size).toBe(0);const before=await x.a.exportSnapshot('local');await x.sa.migrateLocal();expect(await x.a.exportSnapshot('local')).toEqual(before);await x.sb.sync(user);expect((await x.b.get(user.id,'q'))?.fields.note.value).toBe('old');await x.sb.importBackup(before,'local');expect(await x.b.getOutbox('local')).toEqual([]);expect((await x.b.get('local','q'))?.fields.note.value).toBe('old');await x.aa.logout();expect((await x.aa.currentUser()).id).toBe('local');expect(x.remote.records.size).toBe(1);}finally{await x.close();}});
it('rejects foreign-owner remote payloads and account changes before applying responses',async()=>{const x=await pair();try{await expect(x.b.receiveRemote(user.id,{entity:'settings',id:'x',revision:1,cursor:1,updatedAt:'now',deviceId:'x',deleted:false,value:{id:'x',userId:'other',value:'secret'}})).rejects.toThrow();const old=x.remote.transport.push;x.remote.transport.push=async(m,u)=>{const r=await old(m,u);x.aa.switch('google-b');return r;};await x.a.saveCorrection(user.id,'q','note','only A');await x.sa.sync(user);expect(await x.a.getOutbox(user.id)).toHaveLength(1);expect(await x.a.getRecords('google-b')).toEqual([]);expect(x.sa.lastResult.status).toBe('noop');}finally{await x.close();}});
import type {TestSession} from '../exams/model';
const session=():TestSession=>({test_id:'test-stable',exam_session_id:'test-stable',userId:user.id,test_type:'original',exam:'2017-sommer',module:'wiso',mode:'kurz',seed:'s',question_ids:['q'],question_models:{q:{kind:'multiple_choice',number:'1',part:'A',subpart_ids:[]}},source_mix:[],answers:{},subpart_assessments:{},official_answers:{q:2},started_at:new Date().toISOString(),completed_at:null,status:'active',current_question:'q',elapsed_time:0,active_since:Date.now(),revision:0,duration_minutes:60,result:null});
it('delete versus another device edit keeps both versions until explicit deletion choice',async()=>{const x=await pair();try{await x.a.createTestSession(session());await x.sa.sync(user);await x.sb.sync(user);await x.a.deleteTestSession(user.id,'test-stable',0);await x.b.updateTestSession(user.id,'test-stable',0,{type:'answer',questionId:'q',answer:{choice:'2'}});await x.sb.sync(user);expect((await x.sa.sync(user)).status).toBe('conflicts');expect(await x.a.getTestSession(user.id,'test-stable')).toBeUndefined();const [c]=await x.sa.conflicts();expect((c.remote as SyncEnvelope).deleted).toBe(false);expect((c.local as any).deleted).toBe(true);await x.sa.resolveConflict(user,c,'local');await x.sb.sync(user);expect(await x.b.getTestSession(user.id,'test-stable')).toBeUndefined();expect([...x.remote.records.values()][0].deleted).toBe(true);}finally{await x.close();}});
it('stale conflict choice rejects then latest explicit choice succeeds after another local edit',async()=>{const x=await pair();try{await x.a.saveCorrection(user.id,'q','note','initial');await x.sa.sync(user);await x.sb.sync(user);await x.a.saveCorrection(user.id,'q','note','A');await x.b.saveCorrection(user.id,'q','note','B');await x.sa.sync(user);await x.sb.sync(user);const [old]=await x.sb.conflicts();await x.b.saveCorrection(user.id,'q','note','B changed');await expect(x.sb.resolveConflict(user,old,'remote')).rejects.toThrow('erneut');const [latest]=await x.sb.conflicts();await x.sb.resolveConflict(user,latest,'remote');expect((await x.b.get(user.id,'q'))?.fields.note.value).toBe('A');}finally{await x.close();}});
it('local-only import can later be explicitly queued, with canonical ordering and stable IDs',async()=>{const x=await pair();try{await x.a.saveCorrection('local','q','note','keep');const backup=await x.a.exportSnapshot('local');await x.b.importSnapshot(backup,user.id,false);expect(await x.b.getOutbox(user.id)).toEqual([]);await x.b.importSnapshot({...backup,records:backup.records.map(r=>({updatedAt:r.updatedAt,fields:r.fields,questionId:r.questionId,userId:r.userId,schema_version:r.schema_version}))},user.id,true);expect(await x.b.getOutbox(user.id)).toHaveLength(1);await x.sb.sync(user);await x.b.importSnapshot(backup,user.id,true);expect(await x.b.getOutbox(user.id)).toHaveLength(0);expect(x.remote.records.size).toBe(1);}finally{await x.close();}});
it('explicit migration includes all eight entity types and preserves stable IDs and historical provenance',async()=>{const x=await pair();try{
 await x.a.saveCorrection('local','q','note','note');await x.a.saveReview({userId:'local',question_id:'q',source_revision:'seg-old',question_number:'1',bounding_box:[0,0,2,2],regions:[[0,0,2,2]],extracted_text:'review',tags:[],solution_page:null,solution_confirmed:false,review_status:'confirmed',updated_at:'old'});await x.a.saveAnswerReview({userId:'local',question_id:'q',official_answer:2,official_answer_status:'confirmed',user_corrected:true,locked:true,parser_revision:'answer-old',updated_at:'old'});
 await x.a.saveAttempt({userId:'local',question_id:'q',attempt_id:'stable-attempt',timestamp:new Date().toISOString(),user_answer:{choice:2},correctness:'richtig',partial_status:false,unsure:false,confidence:'sure',hints_used:[],error_reason:'',note:'historical note',self_assessed:false,auto_scored:true,subparts:[],question_source_revision:'immutable-question',official_answer_revision:'immutable-key'},{userId:'local',question_id:'q',draft:{choice:'2',note:'draft'},revealed:true});await x.a.createTestSession({...session(),userId:'local'});await x.a.saveSetting('local','study-preference',{compact:true});
 const before=await x.a.exportSnapshot('local');await x.sa.migrateLocal();await x.sb.sync(user);expect(await x.a.exportSnapshot('local')).toEqual(before);const after=await x.b.exportSnapshot(user.id);for(const entity of ['records','reviews','answerReviews','attempts','learningSessions','testSessions','settings','questionNotes'] as const){expect(after[entity]).toHaveLength(1);expect(after[entity]![0]).toEqual({...before[entity]![0],userId:user.id});}await x.sa.migrateLocal();expect(x.remote.records.size).toBe(8);
 }finally{await x.close();}});
it('in-flight old account completes without uploading its queued record to a newly signed-in account',async()=>{const x=await pair();try{await x.a.saveCorrection(user.id,'q','note','A');let release!:()=>void;const wait=new Promise<void>(r=>{release=r;});const push=x.remote.transport.push;x.remote.transport.push=async(m,u)=>{await wait;return push(m,u);};const first=x.sa.sync(user);await new Promise(r=>setTimeout(r,10));x.aa.switch('google-b');await x.a.saveCorrection('google-b','b','note','B');const second=x.sa.sync({id:'google-b',mode:'remote'});release();await first;await second;expect(x.remote.records.has('google-b:records:q')).toBe(false);expect(x.remote.records.has('google-b:records:b')).toBe(true);expect(await x.a.getOutbox(user.id)).toHaveLength(1);}finally{await x.close();}});
it('atomically rejects damaged backups and remote records before UI can see incomplete models or object drafts',async()=>{const x=await pair();try{
 const baseline=await x.a.exportSnapshot(user.id);const good={...session(),question_ids:['q','q2'],question_models:{...session().question_models,q2:{kind:'multi_part' as const,number:'U1',part:'B',subpart_ids:['1']}},official_answers:{q:2,q2:null}};
 for(const damage of [ (s:any)=>delete s.question_models.q2,(s:any)=>s.current_question='missing',(s:any)=>s.answers={q:{choice:{bad:true}}},(s:any)=>s.elapsed_time=-1,(s:any)=>s.question_models.q2.subpart_ids=[{}],(s:any)=>s.active_since=Infinity]){
  const broken=structuredClone(good);damage(broken);const backup={...baseline,records:[{schema_version:1 as const,userId:user.id,questionId:'before-invalid',fields:{},updatedAt:'now'}],testSessions:[broken]};await expect(x.a.importSnapshot(backup,user.id,false)).rejects.toThrow();expect(await x.a.exportSnapshot(user.id)).toEqual(baseline);await expect(x.a.receiveRemote(user.id,{entity:'testSessions',id:broken.test_id,revision:1,cursor:1,updatedAt:'now',deviceId:'test',deleted:false,value:broken as any})).rejects.toThrow();
 }
 await expect(x.a.importSnapshot({...baseline,learningSessions:[{userId:user.id,question_id:'q',draft:{note:{bad:true}} as any,revealed:false}]},user.id,false)).rejects.toThrow();expect(await x.a.exportSnapshot(user.id)).toEqual(baseline);
 }finally{await x.close();}});
it('restores last-sync time only for the current UID without overwriting a newer run',async()=>{const x=await pair();try{await x.a.setDeviceState('lastSync:google-a','2025-01-01T00:00:00Z');await x.a.setDeviceState('lastSync:google-b','2025-02-01T00:00:00Z');x.aa.switch('google-a');x.aa.switch('google-b');await new Promise(r=>setTimeout(r,10));expect(x.sa.lastSync).toBe('2025-02-01T00:00:00Z');await x.sa.sync({id:'google-b',mode:'remote'});expect(x.sa.lastSync).not.toBe('2025-02-01T00:00:00Z');}finally{await x.close();}});

it('question notes sync offline, retry without duplicates, and preserve conflicting edits',async()=>{const x=await pair();try{
 await x.a.saveQuestionNote(user.id,'q','A offline',0,'');x.remote.setOffline(true);expect((await x.sa.sync(user)).status).toBe('error');x.remote.setOffline(false);await x.sa.sync(user);await x.sa.sync(user);await x.sb.sync(user);expect((await x.b.getQuestionNote(user.id,'q'))?.text).toBe('A offline');expect(x.remote.records.size).toBe(1);
 await x.a.saveQuestionNote(user.id,'q','A next',1,'A offline');await x.b.saveQuestionNote(user.id,'q','B next',1,'A offline');await x.sa.sync(user);expect((await x.sb.sync(user)).status).toBe('conflicts');expect((await x.b.getQuestionNote(user.id,'q'))?.text).toBe('B next');const [c]=await x.sb.conflicts();await x.sb.resolveConflict(user,c,'local');await x.sa.sync(user);expect((await x.a.getQuestionNote(user.id,'q'))?.text).toBe('B next');await expect(x.a.saveQuestionNote(user.id,'q','stale editor',2,'A next')).rejects.toThrow();expect(await x.b.getOutbox(user.id)).toEqual([]);
 }finally{await x.close();}});
