import {useEffect,useState} from 'react';
import {useAppServices} from '../services/context';
import type {PersonalDataSnapshot,SyncConflict} from '../types';
export default function SyncSettings(){
 const {syncControl:control,repository,user}=useAppServices();const [,render]=useState(0);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [counts,setCounts]=useState<Record<string,number>>({});const [conflicts,setConflicts]=useState<SyncConflict[]>([]);const [backup,setBackup]=useState<PersonalDataSnapshot>();const [mode,setMode]=useState<'local'|'sync'>('local');
 const refresh=async()=>{if(control){setCounts((await control.localSummary()).counts);setConflicts(await control.conflicts());}};
 useEffect(()=>{void refresh();return control?.subscribe(()=>{render(n=>n+1);void refresh();});},[control,user.id]);
 const act=async(work:()=>Promise<unknown>)=>{setBusy(true);setMessage('');try{const r=await work();setMessage(r&&typeof r==='object'&&'status'in r?r.status==='error'&&'message'in r?String(r.message):r.status==='noop'&&'reason'in r?String(r.reason):r.status==='conflicts'?'Konflikte bleiben gespeichert. Bitte beide Versionen prüfen.':'Synchronisierung abgeschlossen.':'Aktion abgeschlossen.');await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Aktion fehlgeschlagen. Bitte erneut versuchen.');}finally{setBusy(false);}};
 const exportData=async()=>{const data=await repository.exportSnapshot(user.id);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ap2-lernfortschritt.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const account=control?.account();const total=Object.values(counts).reduce((a,b)=>a+b,0);
 return <section className="sync-settings"><h1>Synchronisierung</h1>{!control?.configured?<><p>Noch nicht synchronisiert.</p><p>Cloud-Sync nicht eingerichtet. Du kannst weiterhin lokal lernen und Sicherungen erstellen. Für Google-Anmeldung fehlt die Firebase-Konfiguration.</p><button disabled>Mit Google anmelden</button></>:!account?<><p>Lokal gespeichert. Mit demselben Google-Konto kannst du später auf mehreren Geräten lernen.</p><button disabled={busy} onClick={()=>void act(()=>control.login())}>Mit Google anmelden</button></>:<><p>Angemeldet: {account.email??account.displayName??'Google-Konto'}</p><p>Dieses Gerät: {control.deviceName}</p><p>{control.busy?'Synchronisierung läuft…':control.lastResult.status==='completed'?'Synchronisiert':control.lastResult.status==='conflicts'?'Konflikte prüfen':control.lastResult.status==='error'?control.lastResult.message:'Lokal gespeichert · Synchronisierung bereit'}</p><p>Letzte Synchronisierung: {control.lastSync?new Date(control.lastSync).toLocaleString('de-DE'):'Noch keine'}</p><button disabled={busy||control.busy} onClick={()=>void act(()=>control.sync(user))}>Jetzt synchronisieren</button><button disabled={busy||control.busy} onClick={()=>void act(()=>control.logout())}>Von Google abmelden</button><p>Abmelden löscht weder lokale noch Cloud-Daten.</p></>}
 {account&&total>0&&<section aria-label="Lokale Daten übernehmen"><h2>Vorhandene lokale Daten</h2><p>{total} Datensätze. Die lokale Kopie bleibt erhalten. Erst mit deiner Bestätigung werden diese Daten dem angemeldeten Konto zugeordnet und synchronisiert.</p><ul>{Object.entries(counts).map(([name,n])=><li key={name}>{name}: {n}</li>)}</ul><button disabled={busy||control?.busy} onClick={()=>void act(()=>control!.migrateLocal())}>Lokale Daten übernehmen und synchronisieren</button></section>}
 {conflicts.length>0&&<section><h2>Konflikte</h2><p>Beide Versionen bleiben gespeichert, bis du dich entscheidest. Es wird nichts automatisch überschrieben.</p>{conflicts.map(c=><article key={c.entity+c.id}><h3>{c.entity} · {c.id}</h3><details><summary>Beide Versionen ansehen</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify({diesesGeraet:c.local,cloud:c.remote},null,2)}</pre></details><button disabled={busy} onClick={()=>void act(()=>control!.resolveConflict(user,c,'local'))}>Diese Geräteversion verwenden</button><button disabled={busy} onClick={()=>void act(()=>control!.resolveConflict(user,c,'remote'))}>Cloud-Version verwenden</button></article>)}</section>}
 <section><h2>Sicherung</h2><button disabled={busy} onClick={()=>void act(exportData)}>Lernfortschritt exportieren</button><label>Lernfortschritt importieren <input type="file" accept="application/json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void act(async()=>{const data=JSON.parse(await f.text());if(data.schema_version!==1||typeof data.userId!=='string')throw Error('Ungültige Sicherung.');setBackup(data);});}}/></label>{backup&&<><p>Importierte Daten ersetzen keine Datensätze mit abweichendem Inhalt. Die Herkunft deiner Ergebnisse bleibt erhalten.</p><label><input type="radio" checked={mode==='local'} onChange={()=>setMode('local')}/> Nur lokal importieren (im lokalen Profil, ohne Upload)</label><label><input type="radio" checked={mode==='sync'} disabled={!account} onChange={()=>setMode('sync')}/> Importieren und synchronisieren</label><button disabled={busy||!control} onClick={()=>void act(async()=>{const r=await control!.importBackup(backup,mode);setBackup(undefined);return mode==='local'?{status:'noop',reason:'Nur im lokalen Profil importiert, ohne Upload. Wenn du angemeldet bist, melde dich ab, um diese Kopie zu sehen.'}:r;})}>Import bestätigen</button></>}</section><p role="status">{message}</p></section>;
}
