import {useEffect,useState,type ReactNode} from 'react';
import {useAppServices} from '../services/context';
import {asset} from '../segmented/types';
import type {InventoryQuestion} from '../bank/model';
import type {TrainingLaunch} from '../bank/BankView';
import type {TestSession} from '../exams/model';
import type {TrainingRun} from '../training/model';
import {deriveDashboard,type DashboardSnapshot} from './analytics';
import './dashboard.css';
import dashboardConfig from './config.json';
type Props={disabled:boolean;revision:unknown;onLearn:()=>void;onExams:()=>void;onTests:()=>void;onBank:(module?:string)=>void;onStudy:(q:InventoryQuestion)=>void;onTraining:(r:TrainingRun)=>void;onStartTraining:(input:TrainingLaunch)=>Promise<void>;onTest:(t:TestSession)=>void;renderTest:(t:TestSession)=>ReactNode;onHistory:()=>void};
const percent=(n:number|null)=>n===null?'–':Math.round(n)+' %';
const count=(n:number)=>n.toLocaleString('de-DE');
export default function HomeDashboard(p:Props){
 const {repository,user}=useAppServices();const [snapshot,setSnapshot]=useState<DashboardSnapshot>(),[inventory,setInventory]=useState<InventoryQuestion[]>(),[error,setError]=useState(''),[launching,setLaunching]=useState(false);
 useEffect(()=>{let alive=true;const load=()=>void Promise.all([repository.getDashboardSnapshot(user.id),fetch(asset('data/question_inventory.json')).then(r=>{if(!r.ok)throw Error('Aufgabenvorrat nicht verfügbar.');return r.json() as Promise<InventoryQuestion[]>;})]).then(([s,i])=>{if(alive){setSnapshot(s);setInventory(i);setError('')}}).catch(()=>{if(alive)setError('Die Lernübersicht konnte nicht geladen werden. Bitte erneut öffnen.');});load();window.addEventListener('ap2:personal-data-changed',load);window.addEventListener('focus',load);return()=>{alive=false;window.removeEventListener('ap2:personal-data-changed',load);window.removeEventListener('focus',load)}},[repository,user.id,p.revision]);
 const s=snapshot&&inventory?deriveDashboard(user.id,inventory,snapshot):null;const disabled=p.disabled||launching;
 const test=snapshot?.testSessions.filter(t=>['active','paused'].includes(t.status)&&!t.discarded_at&&!t.deleted_at).sort((a,b)=>b.started_at.localeCompare(a.started_at))[0];
 const training=snapshot?.trainingRuns.filter(r=>r.question_ids.some(id=>!r.drafts[id]?.attempt_id)).sort((a,b)=>b.updated_at.localeCompare(a.updated_at))[0];
 const learning=snapshot?.learningSessions.filter(l=>inventory?.some(q=>q.question_id===l.question_id)).sort((a,b)=>(b.updated_at??'').localeCompare(a.updated_at??''))[0];
 const candidates=[...(test?[{stamp:test.started_at,kind:'test',run:()=>p.onTest(test),label:'Gespeicherte Prüfung'}]:[]),...(training?[{stamp:training.updated_at,kind:'training',run:()=>p.onTraining(training),label:'Dein gespeichertes Training'}]:[]),...(learning?[{stamp:learning.updated_at??'',kind:'study',run:()=>p.onStudy(inventory!.find(q=>q.question_id===learning.question_id)!),label:'Freies Lernen · '+inventory!.find(q=>q.question_id===learning.question_id)!.moduleTitle}]:[])].sort((a,b)=>b.stamp.localeCompare(a.stamp));
 const resume=candidates[0];
 const next=async()=>{if(!s||!inventory)return;setLaunching(true);try{if(s.next.kind==='wrong'||s.next.kind==='uncertainty'){const ids=new Set(s.next.kind==='wrong'?s.stage1Ids:s.unsureIds);await p.onStartTraining({definition:{knowledgeTopicIds:[],questionTypeIds:[],moduleIds:[],examIds:[]},questions:inventory.filter(q=>ids.has(q.question_id)),...(s.next.kind==='wrong'?{stage:1 as const}:{uncertainty:true})});}else if(s.next.kind==='test')p.onTests();else p.onBank(s.next.module);}catch(e){setError(e instanceof Error?e.message:'Training konnte nicht geöffnet werden.');}finally{setLaunching(false)}};
 return <div className="home-dashboard">
 <section data-testid="home-resume" className="home-action-section" aria-label="Weiterlernen">{resume?.kind==='test'&&test?p.renderTest(test):<><h1>Weiterlernen</h1><div className="home-resume-card"><div><span className="eyebrow">DEIN NÄCHSTER LERNSCHRITT</span><h2>{resume?.label??'Bereit für deine nächste Aufgabe?'}</h2><p>{resume?'Dein Fortschritt bleibt gespeichert. Mach dort weiter, wo du aufgehört hast.':'Wähle dein Modul und starte in deinem Tempo.'}</p></div><button className="primary" disabled={disabled} onClick={()=>resume?resume.run():p.onLearn()}>{resume?'Fortsetzen':'Freies Lernen starten'}</button></div></>}</section>
 <section data-testid="home-quick"><h2>Schnell starten</h2><div className="mode-cards"><button disabled={disabled} onClick={p.onLearn}><strong>Freies Lernen</strong><span>Aufgaben auswählen und in deinem Tempo üben.</span></button><button disabled={disabled} onClick={p.onExams}><strong>Originalprüfung</strong><span>Eine echte Prüfung in Originalreihenfolge.</span></button><button disabled={disabled} onClick={p.onTests}><strong>Modultests</strong><span>Originalaufgaben zu einem Übungstest kombinieren.</span></button></div></section>
 {error&&<p role="alert">{error}</p>}
 <section data-testid="home-progress" className="home-progress"><h2>Dein Fortschritt</h2>{!s?<p role="status">Lernübersicht wird geladen…</p>:<><div className="home-hero"><div><span className="eyebrow">SCHRITT FÜR SCHRITT WEITER</span><h3><strong data-testid="coverage-count">{count(s.answered)}</strong><span> / {count(s.total)} Aufgaben geschafft</span></h3><p>{percent(s.coverage)} des Fragenpools abgedeckt</p><progress aria-label="Abdeckung" value={s.answered} max={s.total||1}/><div className="home-hero-foot"><span>Noch <b>{count(s.open)}</b> Aufgaben offen</span><span>+{s.newCoverage} erstmals bearbeitet in den letzten 7 Tagen</span><span>{s.accuracy===null?'– · Noch keine bewerteten Aufgaben':`${percent(s.accuracy)} aktuell richtig`}</span></div></div><button className="primary" disabled={disabled} onClick={()=>resume?resume.run():void next()}>Weiterlernen</button></div>
 <div className="home-kpis">{[{title:'Beherrscht',value:s.correct,text:'Zuletzt richtig beantwortet',id:'correct'},{title:'Unsicher',value:s.unsure,text:'Ohne aktive Fehlertraining-Stufen',id:'unsure'},{title:'Im Fehlertraining',value:s.wrong,text:'Aktuell in Stufe 1, 2 oder 3',id:'wrong'},{title:'Gemeistert',value:s.mastered,text:'Drei Wiederholungsstufen geschafft',id:'mastered'}].map(k=><article key={k.id}><h3>{k.title}</h3><strong data-testid={'kpi-'+k.id}>{count(k.value)}</strong><p>{k.text}</p></article>)}</div></>}</section>
 {s&&<><section className="home-next" data-testid="home-next"><div><span className="eyebrow">DEIN NÄCHSTER SCHRITT</span><h2>{s.next.kind==='wrong'?`${s.next.count} ${s.next.count===1?'Aufgabe':'Aufgaben'} in Stufe 1`:s.next.kind==='uncertainty'?`${s.next.count} unsichere Aufgaben`:s.next.kind==='test'?'Bereit für einen Modultest':s.modules.find(m=>m.module===s.next.module)?.title??'Starte deine erste Aufgabe'}</h2><p>{s.next.kind==='wrong'?'Diese Aufgaben haben aktuell höchste Priorität.':s.next.kind==='uncertainty'?'Mehr Sicherheit gewinnen – mit deinen markierten Aufgaben.':s.next.kind==='test'?'Du hast einen großen Teil des Fragenpools bearbeitet. Prüfe dein Wissen im Zusammenhang.':'Hier ist noch am meisten Platz für deinen Fortschritt.'}</p></div><button className="primary" disabled={disabled} onClick={()=>void next()}>{s.next.kind==='wrong'?'Fehlertraining starten':s.next.kind==='uncertainty'?'Unsicher Training starten':s.next.kind==='test'?'Modultest starten':'Weiterlernen'}</button></section>
 <section data-testid="home-modules"><h2>Module</h2><div className="home-modules">{s.modules.map(m=><button className="home-module" key={m.module} onClick={()=>p.onBank(m.module)} disabled={disabled}><h3>{m.title}</h3><strong>{count(m.answered)} / {count(m.total)}</strong><span>{percent(m.coverage)} abgedeckt</span><progress aria-label={m.title+' Abdeckung'} value={m.answered} max={m.total||1}/><span>{m.accuracy===null?'– · Noch keine bewerteten Aufgaben':`${percent(m.accuracy)} aktuell richtig`}</span><b>Im Aufgabenpool üben →</b></button>)}</div></section>
 <section className="home-development" data-testid="home-development"><h2>Deine Entwicklung</h2><div className="home-window-grid"><article><span>Letzte 7 Tage</span><h3>{s.current.count} Aufgaben · {percent(s.current.accuracy)} richtig</h3><p>Je Aufgabe zählt das letzte gültige Ergebnis in diesem Zeitraum.</p></article><article><span>Vorherige 7 Tage</span><h3>{s.previous.count} Aufgaben · {percent(s.previous.accuracy)} richtig</h3><p>{s.delta===null?`Für einen Vergleich brauchst du mindestens ${dashboardConfig.minTrendQuestions} bewertete Aufgaben in beiden Zeiträumen.`:s.delta>0?`↑ +${Math.round(s.delta)} %-Punkte gegenüber der Vorwoche`:s.delta<0?`${Math.round(s.delta)} %-Punkte · Wiederholung lohnt sich`:'Stabil geblieben · Bleib dran'}</p></article></div></section>
 <section className="home-goals"><article><span className="eyebrow">NÄCHSTES ZIEL</span><h2>{s.milestone?`${count(s.milestone)} Aufgaben`:'Den ganzen Fragenpool geschafft'}</h2><p>{s.milestone?`Noch ${count(s.milestone-s.answered)} Aufgaben bis zu deinem nächsten Ziel.`:'Jede Wiederholung hilft dir, sicherer zu werden.'}</p></article><article><span className="eyebrow">DEINE LERNSERIE</span><h2>{s.streak?`${s.streak} ${s.streak===1?'Tag':'Tage'} in Folge`:'Ein guter Tag zum Starten'}</h2><p>Diese Woche: {s.weekActive} / 7 Tage aktiv</p></article></section></>}
 <button className="outline history-overview-link" disabled={disabled} onClick={p.onHistory}>Alle Versuche ansehen</button>
 </div>;
}
