import publishedModules from '../../public/data/promoted_modules.json';
import {useEffect,useState} from 'react';
import {useAppServices} from '../services/context';
import {asset} from '../segmented/types';
import type {AnswerReview} from '../segmented/answers';
import {confirmedReview,machineChanged,makeConfirmation,reviewExport,strongestCandidate,type ReviewQueue,type ReviewItem} from './model';
import './review.css';
import {resolveReviewScope} from './scopes';
function SourceCrop({item,onVerified}:{item:ReviewItem;onVerified:(value:boolean)=>void}){
 const [url,setUrl]=useState('');const [error,setError]=useState('');
 useEffect(()=>{let active=true;let objectUrl='';onVerified(false);setUrl('');setError('');void(async()=>{try{const response=await fetch(asset(item.source_crop));if(!response.ok)throw Error();const bytes=await response.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');if(hash!==item.source_crop_sha256)throw Error();if(!active)return;objectUrl=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));setUrl(objectUrl);}catch{if(active)setError('Quellbild konnte nicht verifiziert werden. Speichern gesperrt. Bitte neu laden.');}})();return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)};},[item.question_id,item.source_crop_sha256]);
 return <>{error&&<p role="alert">{error}</p>}{url?<div className="manual-crop"><img src={url} alt={`Originale Antwortquelle ${item.module} Q${item.question_number}`} onLoad={()=>onVerified(true)} onError={()=>{onVerified(false);setError('Quellbild nicht lesbar.');}}/>{item.row_positions.map((top,i)=><span key={i} style={{top:top+'%'}} aria-hidden="true">{i+1} →</span>)}</div>:!error&&<p>Originalquelle wird geprüft…</p>}</>;
}
export default function ManualAnswerReview(){
 const [search,setSearch]=useState(location.search);
 useEffect(()=>{const pop=()=>setSearch(location.search);window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
 const scopeParam=new URLSearchParams(search).get('scope');
 const selected=(()=>{try{return resolveReviewScope(scopeParam)}catch{return undefined}})();
 const {repository,user}=useAppServices();const [queue,setQueue]=useState<ReviewQueue>();const [reviews,setReviews]=useState<AnswerReview[]>([]);const [index,setIndex]=useState(0);const [draft,setDraft]=useState<number|null>(null);const [ready,setReady]=useState(false);const [verified,setVerified]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;setReady(false);setError('');if(!selected){setError('Unbekannter Review-Bereich.');return;}void Promise.all([fetch(asset(selected.path)).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<ReviewQueue>}),repository.getAnswerReviews(user.id)]).then(([q,r])=>{if(!active)return;if(q.scope!==selected.scope||!q.items.length||new Set(q.items.map(i=>i.question_id)).size!==q.items.length)throw Error();setQueue(q);setReviews(r);setIndex(Math.max(0,q.items.findIndex(i=>i.question_id===new URLSearchParams(location.search).get('item'))));setReady(true)}).catch(()=>{if(active)setError('Review-Daten konnten nicht geladen werden. Bitte neu laden.')});return()=>{active=false}},[repository,user.id,selected?.scope]);
 const item=queue?.items[index];const saved=item?confirmedReview(item,reviews.find(r=>r.question_id===item.question_id)):undefined;
 useEffect(()=>{setDraft(saved?.official_answer??null);setMessage('');setVerified(false)},[item?.question_id]);
 useEffect(()=>{const pop=()=>{if(!queue)return;const next=queue.items.findIndex(i=>i.question_id===new URLSearchParams(location.search).get('item'));setIndex(Math.max(0,next));};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[queue]);
 const done=queue?.items.filter(i=>confirmedReview(i,reviews.find(r=>r.question_id===i.question_id))).length??0;
 const dirty=draft!==(saved?.official_answer??null);
 const move=(n:number)=>{if(!queue||busy||n<0||n>=queue.items.length)return;if(dirty&&!window.confirm('Ungespeicherte Auswahl verwerfen?'))return;const u=new URL(location.href);u.searchParams.set('item',queue.items[n].question_id);history.pushState(null,'',u);setIndex(n);requestAnimationFrame(()=>document.getElementById('review-question')?.scrollIntoView({block:'start'}))};
 const save=async()=>{if(!item||!verified||busy)return;setBusy(true);setError('');try{const r=makeConfirmation(item,user.id,draft);await repository.saveAnswerReview(r);setReviews(all=>[...all.filter(v=>v.question_id!==r.question_id),r]);setMessage('Gespeichert · Confirmed · gesperrt')}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen.')}finally{setBusy(false)}};
 const download=()=>{if(!queue)return;const value=reviewExport(queue.items,reviews,queue.scope),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=selected!.download;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <main className="manual-review"><header><a href={asset('?view=start')}>← Zur Lernseite</a><span>Review / Quellen · {selected?.label}</span></header><h1>Offizielle Antworten prüfen</h1><p>{queue?.items.length??0} ursprünglich unsichere Markierungen · Nur die tatsächlich eingekreiste Position bestätigen. Die Maschinenempfehlung wird nicht automatisch übernommen.</p>{error&&<p role="alert">{error}</p>}
 {ready&&item&&queue?<><section className="manual-progress"><strong>{done}/{queue.items.length} bestätigt</strong><div>{[...new Set(queue.items.map(i=>i.module))].map(module=>{const items=queue.items.filter(i=>i.module===module),count=items.filter(i=>confirmedReview(i,reviews.find(r=>r.question_id===i.question_id))).length;return publishedModules.some(m=>m.examId===selected?.examId&&m.title===module)?<p key={module}>{module}: Offiziell freigegeben · 28/28 MC + 8/8 U · {count}/{items.length} lokal bestätigt</p>:<p key={module}>{module}: {count}/{items.length} manuell · {28-items.length+count}/28 Antworten lokal vollständig{count===items.length?' · Bereit für Freigabe-Import':' · Noch gesperrt'}</p>})}</div><button disabled={!done||busy||dirty} onClick={download}>Bestätigungen exportieren ({done}/{queue.items.length})</button><p>Auf diesem Gerät gespeichert. Für die öffentliche Freigabe die exportierte JSON-Datei im Codex-Chat zurückgeben. Der Import prüft jedes Modul vollständig und registriert es automatisch; die Webseite selbst kann GitHub nicht ändern.</p></section>
 <nav aria-label="Antwort-Review Aufgaben">{queue.items.map((q,i)=><button key={q.question_id} disabled={busy} aria-current={index===i?'step':undefined} onClick={()=>move(i)}>{q.module==='Arbeitsplanung'?'AP':q.module==='Funktionsanalyse'?'FA':'WiSo'} Q{q.question_number}{confirmedReview(q,reviews.find(r=>r.question_id===q.question_id))?' ✓':''}</button>)}</nav>
 <article id="review-question"><h2>{item.module} · Q{item.question_number}</h2><p>Aufgabe {index+1}/{queue.items.length} · Lösung Seite {item.source_page} · {saved?'Confirmed · gesperrt':'Needs Review'}</p><div className="manual-columns"><section><h3>Originale Kreis-Markierung</h3><p>Von oben nach unten: Antwort 1, 2, 3, 4, 5.</p><SourceCrop key={item.question_id} item={item} onVerified={setVerified}/><p><a href={asset(item.source_crop)} target="_blank" rel="noreferrer">Originalausschnitt öffnen ↗</a> · <a href={asset(item.overlay)} target="_blank" rel="noreferrer">Gesamte Erkennungstabelle ↗</a></p></section><section><fieldset disabled={busy||!verified}><legend>Welche Position ist tatsächlich eingekreist?</legend><div className="manual-options">{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="manual-answer" checked={draft===n} onChange={()=>setDraft(n)} value={n}/><span>{n}</span></label>)}</div></fieldset><button className="primary" disabled={busy||!verified||draft===null} onClick={()=>void save()}>Speichern</button><p role="status">{message}</p>{saved&&<p>Deine Bestätigung hat Vorrang vor jeder späteren Maschinenempfehlung.</p>}{saved&&machineChanged(item,saved)&&<p role="alert">Machine suggestion changed. Deine bestätigte Antwort bleibt unverändert. Die Freigabe benötigt eine erneute Prüfung der Quellenbindung.</p>}
 <h3>Maschinenbefund — keine Bestätigung</h3><p>Stärkster Kandidat nach Ring-Farbdeckung: <strong>{strongestCandidate(item)??'nicht eindeutig'}</strong>. Nur ein Vergleichswert, keine automatisch akzeptierte Antwort.</p><p>Review reasons: {item.review_reasons.join(', ')}</p><div className="manual-measurements"><table><thead><tr><th>Row</th><th>Schwelle</th><th>Ring ink</th><th>Angular support</th><th>Center ink</th></tr></thead><tbody>{item.measurements.map((m,i)=><tr key={i}><td>{m.row}</td><td>{m.threshold_offset}</td><td>{m.ring_ink}</td><td>{m.angular_support}</td><td>{m.center_ink}</td></tr>)}</tbody></table></div><details><summary>Unveränderte Quellen- und Detektordaten</summary><pre>{JSON.stringify(item,null,2)}</pre></details></section></div></article><div className="manual-navigation"><button disabled={busy||index===0} onClick={()=>move(index-1)}>← Previous</button><button disabled={busy||index===queue.items.length-1} onClick={()=>move(index+1)}>Next →</button></div></>:!error&&<p>Review lädt…</p>}</main>;
}
