import {describe,it,expect} from 'vitest';
import {makeConfirmation,confirmedReview,strongestCandidate,reviewExport,machineChanged,type ReviewItem} from './model';
const item={question_id:'2018-19-ap-p3-3',question_number:3,exam:'2018_19_winter',module:'Arbeitsplanung',parser_revision:'v1',source_pdf_sha256:'a'.repeat(64),source_crop:'assets/q3.png',source_crop_sha256:'b'.repeat(64),evidence_hash:'c'.repeat(64),official_answer:null,official_answer_status:'needs_review',review_reasons:['threshold_disagreement'],measurements:[{row:2,ring_ink:.38,angular_support:.9,threshold_offset:3},{row:1,ring_ink:.1,angular_support:.2,threshold_offset:3}]} as ReviewItem;
describe('manual official review',()=>{
 it('requires explicit 1-5 selection; candidate cannot become a confirmation by default',()=>{expect(strongestCandidate(item)).toBe(2);expect(()=>makeConfirmation(item,'local',null)).toThrow();expect(()=>makeConfirmation(item,'local',6)).toThrow();});
 it('binds a locked selection to source evidence and preserves it after a machine change',()=>{const r=makeConfirmation(item,'local',4);expect(r).toMatchObject({official_answer:4,locked:true,user_corrected:true,confirmation_method:'manual_source_review'});expect(confirmedReview(item,r)?.official_answer).toBe(4);const next={...item,parser_revision:'v2',official_answer:2};expect(confirmedReview(next,r)?.official_answer).toBe(4);expect(machineChanged(next,r)).toBe(true);});
 it('exports only source-bound manual confirmations, excluding unrelated reviews',()=>{const r=makeConfirmation(item,'local',4);const exported=reviewExport([item],[r,{...r,question_id:'other'}]);expect(exported.confirmations).toHaveLength(1);expect(exported.confirmations[0]).not.toHaveProperty('userId');expect(exported.confirmations[0].evidence_hash).toBe(item.evidence_hash);});
 it('does not accept an unrelated or old generic review as a manual source confirmation',()=>{const r=makeConfirmation(item,'local',4);expect(confirmedReview(item,{...r,question_id:'other'})).toBeUndefined();expect(confirmedReview(item,{...r,confirmation_method:undefined})).toBeUndefined();});
});
