import {useEffect,useState} from 'react';
import {useAppServices} from '../services/context';
import {asset} from '../segmented/types';
import type {AnswerReview} from '../segmented/answers';
import {SourceCrop} from './ManualAnswerReview';
import {confirmedReview,makeConfirmation,machineChanged,strongestCandidate} from './model';
import {orderedQueue,exportOvernight,type OvernightItem,type MappingDecision} from './overnight';
import './review.css';
function MappingEvidence({item,onVerified}:{item:OvernightItem;onVerified:(value:boolean)=>void}){
 const [states,setStates]=useState<Record<number,boolean>>({});
 const images=item.evidence_images??(item.source_crop&&item.source_crop_sha256?[{src:item.source_crop,sha256:item.source_crop_sha256,label:'Originale Mapping-Quelle'}]:[]);
 useEffect(()=>{onVerified(images.length>0&&images.every((_,n)=>states[n]))},[states,item.id]);
 return <>{images.map((im,n)=><details key={im.src} open><summary>{im.label}</summary><SourceCrop item={{question_id:item.id+'-'+n,source_crop:im.src,source_crop_sha256:im.sha256,module:item.module,question_number:0,row_positions:[]}} label={im.label} onVerified={v=>setStates(s=>s[n]===v?s:{...s,[n]:v})}/></details>)}</>
}
export default function OvernightReview(){
 const {repository,user}=useAppServices();const [items,setItems]=useState<OvernightItem[]>([]),[reviews,setReviews]=useState<AnswerReview[]>([]),[decisions,setDecisions]=useState<MappingDecision[]>([]),[index,setIndex]=useState(0),[draft,setDraft]=useState<number|null>(null),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[comment,setComment]=useState('');
 const key='ap2:technical-review:overnight:'+user.id;
 useEffect(()=>{void Promise.all([fetch(asset('data/overnight_review_queue.json')).then(r=>{if(!r.ok)throw Error('Review nicht erreichbar');return r.json()}),repository.getAnswerReviews(user.id)]).then(([q,r])=>{const all=orderedQueue(q.items);setItems(all);setReviews(r);setIndex(Math.max(0,all.findIndex(i=>i.id===new URLSearchParams(location.search).get('item'))));setDecisions(JSON.parse(localStorage.getItem(key)??'[]'));}).catch(e=>setError(String(e)))},[repository,user.id,key]);
 const item=items[index],answer=item?.answer;const saved=answer?confirmedReview(answer,reviews.find(r=>r.question_id===answer.question_id)):undefined;
 useEffect(()=>{setDraft(saved&&!machineChanged(answer!,saved)?saved.official_answer:null);setVerified(false);setComment(decisions.find(d=>d.id===item?.id)?.comment??'');setMessage('')},[item?.id]);

 const dirty=draft!==(saved&&answer&&!machineChanged(answer,saved)?saved.official_answer:null)||comment!==(decisions.find(d=>d.id===item?.id)?.comment??'');
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 useEffect(()=>{const pop=()=>{if(busy||dirty&&!window.confirm('Ungespeicherte Auswahl verwerfen? Bitte zuerst speichern.')){const u=new URL(location.href);if(item)u.searchParams.set('item',item.id);history.pushState(null,'',u);return;}setIndex(Math.max(0,items.findIndex(i=>i.id===new URLSearchParams(location.search).get('item'))))};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[items,dirty,busy,item?.id]);
 const move=(n:number)=>{if(n<0||n>=items.length||busy)return;if(dirty&&!window.confirm('Ungespeicherte Auswahl verwerfen? Bitte zuerst bestätigen oder Änderung speichern.'))return;const u=new URL(location.href);u.searchParams.set('item',items[n].id);history.pushState(null,'',u);setIndex(n)};
 const save=async()=>{if(!answer||!verified)return;setBusy(true);try{const r=makeConfirmation(answer,user.id,draft);await repository.saveAnswerReview(r);setReviews(all=>[...all.filter(v=>v.question_id!==r.question_id),r]);setMessage('Gespeichert · gesperrt')}catch(e){setError(String(e))}finally{setBusy(false)}};
 const mapping=(decision:MappingDecision['decision'])=>{if(!item||(item.requires_source||!verified)&&decision==='confirmed')return;const next=[...decisions.filter(d=>d.id!==item.id),{id:item.id,evidence_hash:item.evidence_hash,decision,comment,updated_at:new Date().toISOString()}];try{localStorage.setItem(key,JSON.stringify(next));setDecisions(next);setMessage('Prüfentscheidung gespeichert. Öffentliche Freigabe erfolgt erst nach geprüftem Import.')}catch{setError('Entscheidung konnte nicht gespeichert werden.')}};
 const done=exportOvernight(items,reviews,decisions);const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(done,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='overnight-review-confirmations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <main className="manual-review"><header><a href={asset('?view=start')}>← Lernen</a><a href={asset('evidence/overnight/')}>Morning Report</a></header><h1>Morgen Review Queue</h1><p>{items.length} Prüfaufträge · {done.confirmations.length} Antworten bestätigt · {done.mapping_decisions.length} Quellenentscheidungen gespeichert</p><p>Nur anhand der Originalquelle bestätigen. Keine automatische Übernahme von Vorschlägen. Änderungen an der öffentlichen Bibliothek erfolgen nach geprüftem Export-Import.</p><button disabled={dirty||busy} onClick={download}>Alle Entscheidungen exportieren</button>{error&&<p role="alert">{error}</p>}<label>Prüfauftrag <select value={index} onChange={e=>move(Number(e.target.value))}>{items.map((i,n)=><option key={i.id} value={n}>{i.examLabel} / {i.module} / {i.question} / {i.type}</option>)}</select></label>
 {item&&<article><h2>{item.examLabel} · {item.module} · {item.question}</h2><p>{index+1}/{items.length} · {item.type}</p><p>{item.reason}</p>{answer?<div className="manual-columns"><section><SourceCrop key={item.id} item={answer} onVerified={setVerified}/><p>Von oben nach unten: 1, 2, 3, 4, 5.</p><a href={asset(answer.overlay)} target="_blank" rel="noreferrer">Offizielle Antworttabelle / Overlay</a></section><section><fieldset disabled={!verified||busy}><legend>Tatsächlich eingekreiste Antwort</legend><div className="manual-options">{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="answer" checked={draft===n} onChange={()=>setDraft(n)}/>{n}</label>)}</div></fieldset><button className="primary" disabled={!verified||busy||draft===null} onClick={()=>void save()}>Bestätigen / Änderung speichern</button><p>Maschinenkandidat: {strongestCandidate(answer)??'nicht eindeutig'} — nicht automatisch akzeptiert.</p><details><summary>Detektormessungen und Quellenbindung</summary><pre>{JSON.stringify(answer,null,2)}</pre></details></section></div>:<><MappingEvidence key={item.id} item={item} onVerified={setVerified}/><pre>{JSON.stringify(item.proposal,null,2)}</pre><label>Änderungswunsch (keine Koordinaten erforderlich)<textarea value={comment} onChange={e=>setComment(e.target.value)}/></label><button disabled={item.requires_source||!verified} onClick={()=>mapping('confirmed')}>Bestätigen</button><button onClick={()=>mapping('change_requested')}>Mapping ändern / Quelle ergänzen</button>{item.requires_source&&<p>Eine fehlende Quelle kann nicht durch Bestätigung ersetzt werden.</p>}</>}<p role="status">{message}</p></article>}
 <div className="manual-navigation"><button disabled={index===0||busy} onClick={()=>move(index-1)}>Previous</button><button disabled={index===items.length-1||busy} onClick={()=>move(index+1)}>Next →</button></div></main>
}
