import {useEffect,useRef,useState} from 'react';
import ReviewWorkspace from '../segmented/StudyApp';
import {asset,effectiveQuestion,type QuestionReview,type SegmentedExam} from '../segmented/types';
import {effectiveAnswer,type AnswerKey,type AnswerReview,type OfficialAnswer} from '../segmented/answers';
import {CropImage} from '../segmented/CropImage';
import {IndexedDBProgressRepository} from '../storage/storage';
import Practice from './Practice';
import type {Attempt,LearningSession,USolution} from './model';
import './learning.css';

const repository=new IndexedDBProgressRepository();
type View='start'|'exams'|'study'|'review';
function route(){const p=new URLSearchParams(location.search);return {view:(['start','exams','study','review'].includes(p.get('view')??'')?p.get('view'):p.has('q')?'study':'start') as View,number:p.get('q')??'1'};}
export default function LearningApp(){
 const [locationState,setLocationState]=useState(route);const [exam,setExam]=useState<SegmentedExam>();const [keys,setKeys]=useState<AnswerKey>();
 const [solutions,setSolutions]=useState<USolution[]>([]);const [attempts,setAttempts]=useState<Attempt[]>([]);const [sessions,setSessions]=useState<LearningSession[]>([]);
 const [reviews,setReviews]=useState<QuestionReview[]>([]);const [answerReviews,setAnswerReviews]=useState<AnswerReview[]>([]);
 const [error,setError]=useState('');const [practiceBusy,setBusy]=useState(false);const [reviewBusy,setReviewBusy]=useState(false);const [routing,setRouting]=useState(false);
 const busy=practiceBusy||reviewBusy||routing;const busyRef=useRef(busy);busyRef.current=busy;const deferredRoute=useRef<ReturnType<typeof route>|null>(null);const transition=useRef<(next:ReturnType<typeof route>,push:boolean)=>Promise<void>>(async()=>{});
 const refreshPersonal=async()=>{const [a,s,r,k]=await Promise.all([repository.getAttempts('local'),repository.getLearningSessions('local'),repository.getReviews('local'),repository.getAnswerReviews('local')]);setAttempts(a);setSessions(s);setReviews(r);setAnswerReviews(k);};
 useEffect(()=>{const get=async(path:string)=>{const r=await fetch(asset(path));if(!r.ok)throw Error();return r.json();};Promise.all([get('data/2017_sommer_arbeitsplanung_segmented.json'),get('data/2017_sommer_arbeitsplanung_answers.json'),get('data/2017_sommer_arbeitsplanung_u_solutions.json'),refreshPersonal()]).then(([e,k,u])=>{setExam(e);setKeys(k);setSolutions(u.solutions);}).catch(()=>setError('Daten oder persönlicher Speicher konnten nicht geladen werden. Bitte neu laden.'));},[]);
 transition.current=async(next,push)=>{
  if(locationState.view==='review'){setRouting(true);try{await refreshPersonal();}catch{setError('Persönlicher Speicher nicht lesbar.');setRouting(false);return;}}
  if(push){const url=new URL(location.href);url.searchParams.set('view',next.view);if(next.view==='study'||next.view==='review')url.searchParams.set('q',next.number);else url.searchParams.delete('q');history.pushState(null,'',url);}
  setLocationState(next);setRouting(false);window.scrollTo(0,0);
 };
 useEffect(()=>{const pop=()=>{const next=route();if(busyRef.current)deferredRoute.current=next;else void transition.current(next,false);};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
 useEffect(()=>{if(!busy&&deferredRoute.current){const next=deferredRoute.current;deferredRoute.current=null;void transition.current(next,false);}},[busy]);
 const navigate=(view:View,number=locationState.number)=>{if(busy)return;void transition.current({view,number},true);};
 if(error)return <main className="learning-main" role="alert">{error}</main>;
 if(!exam||!keys)return <main className="learning-main">Lernbereich wird geladen…</main>;
 const original=exam.questions.find(q=>q.question_number===locationState.number)??exam.questions[0];
 const review=reviews.find(r=>r.question_id===original.question_id);const current=effectiveQuestion(original,review);
 const base=keys.answers.find(a=>a.question_id===original.question_id);const answer=base?effectiveAnswer(base,answerReviews.find(r=>r.question_id===original.question_id)) as OfficialAnswer:undefined;
 const solution=solutions.find(s=>s.question_id===original.question_id);
 const recentSession=[...sessions].sort((a,b)=>(a.updated_at??'').localeCompare(b.updated_at??'')).at(-1);
 const done=new Set(attempts.map(a=>a.question_id));const latest=new Map<string,Attempt>();for(const a of [...attempts].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)))latest.set(a.question_id,a);
 const saveSession=async(s:LearningSession)=>{s={...s,updated_at:new Date().toISOString()};await repository.saveLearningSession(s);setSessions(all=>[...all.filter(v=>v.question_id!==s.question_id),s]);};
 const saveAttempt=async(a:Attempt,s:LearningSession)=>{s={...s,updated_at:new Date().toISOString()};await repository.saveAttempt(a,s);setAttempts(all=>[...all,a]);setSessions(all=>[...all.filter(v=>v.question_id!==s.question_id),s]);};
 const annotate=async(id:string,v:Pick<Attempt,'note'|'error_reason'|'unsure'|'confidence'>)=>{await repository.annotateAttempt('local',id,v);setAttempts(all=>all.map(a=>a.attempt_id===id?{...a,...v}:a));};
 return <div className="learning-root"><div className="learning-topbar"><button className="learning-brand" disabled={busy} onClick={()=>navigate('start')}>AP2 <span>lernen</span></button><nav aria-label="Hauptnavigation"><button disabled={busy} onClick={()=>navigate('start')} aria-current={locationState.view==='start'?'page':undefined}>Start / Dashboard</button><button disabled={busy} onClick={()=>navigate('exams')} aria-current={locationState.view==='exams'?'page':undefined}>Originalprüfungen</button></nav><span className="phase">Phase 2A</span></div>
  {locationState.view==='review'?<div className="review-shell" inert={routing}><div className="mode-banner"><strong>Review Mode · Daten und Quellen prüfen</strong><button className="primary" disabled={busy} onClick={()=>navigate('study')}>Zurück zum Lernen</button></div><ReviewWorkspace onBusy={setReviewBusy} uSolutions={solutions} onHome={()=>navigate('start')}/></div>:
  <main className="learning-main"><div className="breadcrumbs"><button disabled={busy} onClick={()=>navigate('exams')}>Originalprüfungen</button><span> / 2017 Sommer / Arbeitsplanung</span></div>
  {locationState.view==='start'?<><div className="eyebrow">DEIN LERNPLATZ</div><h1>Verstehen. Üben.<br/><span>Sicherer werden.</span></h1><p className="intro">Eine Originalprüfung, dein eigener Fortschritt.</p><section className="stats"><div><strong>{done.size}/36</strong><span>Aufgaben bearbeitet</span></div><div><strong>{[...latest.values()].filter(a=>a.correctness==='richtig').length}</strong><span>Zuletzt richtig</span></div><div><strong>{[...latest.values()].filter(a=>a.unsure).length}</strong><span>Noch unsicher</span></div><div><strong>{attempts.length}</strong><span>Gespeicherte Versuche</span></div></section><section className="exam-card"><span className="eyebrow">2017 SOMMER</span><h2>Arbeitsplanung</h2><p>28 Auswahlaufgaben · 8 offene Aufgaben<br/>Originalbilder, offizielle Lösungen und deine Notizen.</p><button className="primary" onClick={()=>navigate('study',recentSession?exam.questions.find(q=>q.question_id===recentSession.question_id)?.question_number??'1':'1')}>Lernen fortsetzen</button><button className="outline" onClick={()=>navigate('exams')}>Prüfung ansehen</button></section></>:
   locationState.view==='exams'?<><h1>Originalprüfungen</h1><section className="exam-card"><span className="eyebrow">2017 SOMMER → ARBEITSPLANUNG</span><h2>Deine Prüfung</h2><div className="part-cards"><button onClick={()=>navigate('study','1')}><strong>Teil A</strong><span>Q1–Q28 · Auswahlaufgaben</span><small>Antwort wählen und direkt vergleichen →</small></button><button onClick={()=>navigate('study','U1')}><strong>Teil B</strong><span>U1–U8 · Offene Aufgaben</span><small>Antworten, Lösung ansehen und selbst bewerten →</small></button></div></section></>:
   <><div className="learning-heading"><div><span className="eyebrow">2017 SOMMER · ARBEITSPLANUNG</span><h1>{original.question_number.startsWith('U')?'Teil B · Offene Aufgaben':'Teil A · Auswahlaufgaben'}</h1></div><span className="practice-label">Study Mode</span></div><nav className="part-nav" aria-label="Prüfungsteile"><button disabled={busy} onClick={()=>navigate('study','1')}>Teil A · Q1–Q28</button><button disabled={busy} onClick={()=>navigate('study','U1')}>Teil B · U1–U8</button></nav><nav className="learning-question-nav" aria-label="Aufgaben">{exam.questions.filter(q=>q.question_number.startsWith('U')===original.question_number.startsWith('U')).map(q=><button disabled={busy} key={q.question_id} onClick={()=>navigate('study',q.question_number)} aria-label={`Aufgabe ${q.question_number}`} aria-current={q.question_id===current.question_id?'true':undefined} className={done.has(q.question_id)?'completed':''}>{q.question_number}{done.has(q.question_id)?' ✓':''}</button>)}</nav>
    <section className="reader"><div className="reader-head"><h2>Aufgabe {current.question_number}</h2><a className="outline" href={asset(current.source_pdf)+`#page=${current.source_page}`} target="_blank" rel="noreferrer">Original-PDF · Seite {current.source_page} ↗</a></div><div className="question-art"><CropImage question={current} edited={!!review&&JSON.stringify(current.regions)!==JSON.stringify(original.regions)}/></div>
     {solution&&<details><summary>Gemeinsame Aufgabenbeschreibung & Anlage</summary><a href={asset(current.source_pdf)+'#page=9'} target="_blank" rel="noreferrer">Aufgabenbeschreibung ↗</a><br/><a href={asset(current.source_pdf)+'#page=13'} target="_blank" rel="noreferrer">Anlage für die Zeichnung ↗</a></details>}
     {original.question_number.startsWith('U')&&!solution?<p role="alert">Offizielle U-Lösung fehlt. Keine Bewertung möglich.</p>:<Practice key={original.question_id} questionId={original.question_id} number={original.question_number} answer={answer} u={solution} session={sessions.find(s=>s.question_id===original.question_id)} history={attempts.filter(a=>a.question_id===original.question_id)} onSession={saveSession} onAttempt={saveAttempt} onAnnotate={annotate} onBusy={setBusy}/>}
    </section><div className="study-pagination"><button disabled={busy||exam.questions.indexOf(original)===0} onClick={()=>navigate('study',exam.questions[exam.questions.indexOf(original)-1].question_number)}>← Vorherige Aufgabe</button><button disabled={busy||exam.questions.indexOf(original)===exam.questions.length-1} onClick={()=>navigate('study',exam.questions[exam.questions.indexOf(original)+1].question_number)}>Nächste Aufgabe →</button></div></>}
    <footer className="learning-footer"><span>Nur 2017 Sommer Arbeitsplanung · Fortschritt bleibt auf diesem Gerät</span><button className="outline" disabled={busy} onClick={()=>navigate('review')}>Review / Quellen</button><button className="outline" disabled={busy} onClick={()=>{const blob=new Blob([JSON.stringify({schema_version:1,attempts,sessions},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ap2-learning-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Lernfortschritt exportieren</button></footer>
  </main>}
 </div>;
}
