import {useEffect,useRef,useState} from 'react';
import ReviewWorkspace from '../segmented/StudyApp';
import {asset,effectiveQuestion,questionSources,type QuestionReview,type SegmentedExam} from '../segmented/types';
import {effectiveAnswer,type AnswerKey,type AnswerReview,type OfficialAnswer} from '../segmented/answers';
import {CropImage} from '../segmented/CropImage';
import {IndexedDBProgressRepository} from '../storage/storage';
import Practice from './Practice';
import type {Attempt,LearningSession,USolution} from './model';
import {MODULES,moduleProgress,moduleParts,questionPart,readRoute,routeUrl,type LearningRoute,type ModuleSlug,type View} from './modules';
import ExamWorkspace from '../exams/ExamWorkspace';
import {createSession,sessionResult,type TestSession,type TestType,type TestMode} from '../exams/model';
import './learning.css';

const repository=new IndexedDBProgressRepository();
interface Bundle {exam:SegmentedExam;keys:AnswerKey;solutions:USolution[]}
interface Launch {module:string;type:TestType;mode:TestMode;replaceId:string;replaceRevision:number}
export default function LearningApp(){
 const [locationState,setLocationState]=useState(()=>readRoute(location.search));const [bundles,setBundles]=useState<Partial<Record<ModuleSlug,Bundle>>>({});
 const [moduleErrors,setModuleErrors]=useState<Partial<Record<ModuleSlug,string>>>({});const [personalLoaded,setPersonalLoaded]=useState(false);
 const [attempts,setAttempts]=useState<Attempt[]>([]);const [sessions,setSessions]=useState<LearningSession[]>([]);const [testSessions,setTestSessions]=useState<TestSession[]>([]);
 const [selectedTest,setSelectedTest]=useState<TestSession>();const [testLoading,setTestLoading]=useState(false);const [testError,setTestError]=useState('');const [launch,setLaunch]=useState<Launch|null>(null);
 const [reviews,setReviews]=useState<QuestionReview[]>([]);const [answerReviews,setAnswerReviews]=useState<AnswerReview[]>([]);
 const [error,setError]=useState('');const [practiceBusy,setBusy]=useState(false);const [reviewBusy,setReviewBusy]=useState(false);const [routing,setRouting]=useState(false);
 const busy=practiceBusy||reviewBusy||routing||!!launch;const busyRef=useRef(busy);busyRef.current=busy;
 const deferredRoute=useRef<LearningRoute|null>(null);const transition=useRef<(next:LearningRoute,push:boolean)=>Promise<void>>(async()=>{});
 const refreshPersonal=async()=>{const [a,s,r,k,t]=await Promise.all([repository.getAttempts('local'),repository.getLearningSessions('local'),repository.getReviews('local'),repository.getAnswerReviews('local'),repository.getTestSessions('local')]);setAttempts(a);setSessions(s);setReviews(r);setAnswerReviews(k);setTestSessions(t);};
 useEffect(()=>{
  const controller=new AbortController();let active=true;const get=async(path:string)=>{const r=await fetch(asset(path),{signal:controller.signal});if(!r.ok)throw Error();return r.json();};
  for(const m of MODULES)void Promise.all([get(m.segmentedPath),get(m.answersPath),get(m.solutionsPath)]).then(([exam,keys,u])=>{if(active)setBundles(all=>({...all,[m.slug]:{exam,keys,solutions:u.solutions}}));}).catch(()=>{if(active)setModuleErrors(all=>({...all,[m.slug]:'Moduldaten konnten nicht geladen werden. Bitte neu laden.'}));});
  void refreshPersonal().then(()=>{if(active)setPersonalLoaded(true);}).catch(()=>{if(active)setError('Persönlicher Speicher konnte nicht geladen werden. Bitte neu laden.');});return()=>{active=false;controller.abort();};
 },[]);
 transition.current=async(next,push)=>{
  busyRef.current=true;setRouting(true);if(locationState.view==='review'){try{await refreshPersonal();}catch{setError('Persönlicher Speicher nicht lesbar.');setRouting(false);return;}}
  if(push)history.pushState(null,'',routeUrl(next,location.href));setLocationState(next);setRouting(false);window.scrollTo(0,0);
 };
 useEffect(()=>{const pop=()=>{const next=readRoute(location.search);if(busyRef.current)deferredRoute.current=next;else void transition.current(next,false);};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
 useEffect(()=>{if(!busy&&deferredRoute.current){const next=deferredRoute.current;deferredRoute.current=null;void transition.current(next,false);}},[busy,locationState]);
 useEffect(()=>{if(!busy&&!deferredRoute.current)history.replaceState(null,'',routeUrl(locationState,location.href));},[locationState,busy]);
 useEffect(()=>{
  if(locationState.view!=='session'){setSelectedTest(undefined);return;}
  let active=true;setTestLoading(true);setSelectedTest(undefined);setTestError('');
  if(!locationState.sessionId){setTestError('Die Sitzungs-ID fehlt. Bitte einen gespeicherten Versuch öffnen.');setTestLoading(false);return;}
  void repository.getTestSession('local',locationState.sessionId).then(s=>{if(!active)return;if(!s){setTestError('Diese Sitzung wurde auf diesem Gerät nicht gefunden.');return;}
   const m=MODULES.find(m=>m.slug===s.module&&m.examId===s.exam);if(!m){setTestError('Das Modul dieser Sitzung ist nicht verfügbar.');return;}
   setSelectedTest(s);setLocationState(r=>r.module===s.module&&r.examId===s.exam?r:{...r,module:s.module,examId:s.exam});
  }).catch(()=>{if(active)setTestError('Die Sitzung konnte nicht geladen werden. Bitte erneut öffnen.');}).finally(()=>{if(active)setTestLoading(false);});return()=>{active=false;};
 },[locationState.view,locationState.sessionId]);
 const navigate=(view:View,number=locationState.number,module=locationState.module)=>{if(busyRef.current)return;void transition.current({view,number,module,examId:MODULES.find(m=>m.slug===module)!.examId},true);};
 const openTest=(s:TestSession)=>{if(busyRef.current)return;void transition.current({view:'session',sessionId:s.test_id,number:'1',module:s.module,examId:s.exam},true);};
 const updatedTest=(s:TestSession)=>{setSelectedTest(s);setTestSessions(all=>[...all.filter(t=>t.test_id!==s.test_id),s]);};
 const startTest=async(module:string,type:TestType,mode:TestMode='kurz',replace?:{id:string;revision:number})=>{
  if(routing||practiceBusy||reviewBusy)return;setRouting(true);setTestError('');
  try{
   const config=MODULES.find(m=>m.slug===module)!;const data=bundles[module];if(!data)throw Error('Moduldaten fehlen.');
   const existing=(await repository.getTestSessions('local')).find(s=>s.module===module&&s.exam===config.examId&&s.test_type===type&&['active','paused'].includes(s.status));
   if(existing&&!replace){setLaunch({module,type,mode,replaceId:existing.test_id,replaceRevision:existing.revision});return;}
   const officialAnswers=data.keys.answers.map(a=>effectiveAnswer(a,answerReviews.find(r=>r.question_id===a.question_id)) as OfficialAnswer);
   const created=await repository.createTestSession(createSession({type,config,exam:data.exam,officialAnswers,solutions:data.solutions,mode}),replace);
   setLaunch(null);setTestSessions(await repository.getTestSessions('local'));
   const next:LearningRoute={view:'session',sessionId:created.test_id,module,examId:config.examId,number:'1'};history.pushState(null,'',routeUrl(next,location.href));setLocationState(next);window.scrollTo(0,0);
  }catch(e){setTestError(e instanceof Error?e.message:'Sitzung nicht gespeichert. Bitte erneut versuchen.');setLaunch(null);setTestSessions(await repository.getTestSessions('local').catch(()=>testSessions));}finally{setRouting(false);}
 };
 const config=MODULES.find(m=>m.slug===locationState.module)!;const bundle=bundles[config.slug];const exam=bundle?.exam;const keys=bundle?.keys;const solutions=bundle?.solutions??[];
 const original=exam?.questions.find(q=>q.question_number===locationState.number)??exam?.questions[0];
 useEffect(()=>{if(['study','review'].includes(locationState.view)&&original&&original.question_number!==locationState.number&&!busy)setLocationState(s=>({...s,number:original.question_number}));},[original,locationState.number,locationState.view,busy]);
 const saveSession=async(s:LearningSession)=>{s={...s,updated_at:new Date().toISOString()};await repository.saveLearningSession(s);setSessions(all=>[...all.filter(v=>v.question_id!==s.question_id),s]);};
 const saveAttempt=async(a:Attempt,s:LearningSession)=>{s={...s,updated_at:new Date().toISOString()};await repository.saveAttempt(a,s);setAttempts(all=>[...all,a]);setSessions(all=>[...all.filter(v=>v.question_id!==s.question_id),s]);};
 const annotate=async(id:string,v:Pick<Attempt,'note'|'error_reason'|'unsure'|'confidence'>)=>{await repository.annotateAttempt('local',id,v);setAttempts(all=>all.map(a=>a.attempt_id===id?{...a,...v}:a));};
 if(error)return <main className="learning-main" role="alert">{error}</main>;
 const progress=moduleProgress(exam?.questions??[],attempts,sessions);const review=reviews.find(r=>r.question_id===original?.question_id);const current=original?effectiveQuestion(original,review):undefined;
 const base=keys?.answers.find(a=>a.question_id===original?.question_id);const answer=base?effectiveAnswer(base,answerReviews.find(r=>r.question_id===original?.question_id)) as OfficialAnswer:undefined;
 const solution=solutions.find(s=>s.question_id===original?.question_id);const currentPart=questionPart(config,original?.question_number??'');
 const savedTests=(type?:TestType)=>[...testSessions].filter(s=>!type||s.test_type===type).sort((a,b)=>b.started_at.localeCompare(a.started_at));
 const testHistory=(type?:TestType,filter?:'unfinished'|'submitted')=>{const list=savedTests(type).filter(s=>filter==='unfinished'?['active','paused'].includes(s.status):filter==='submitted'?s.status==='submitted':true);return list.length?<section className="session-history" aria-label="Gespeicherte Sitzungen"><h2>{filter==='unfinished'?'Weiterlernen':filter==='submitted'?'Letzte Prüfungen':type?'Deine Versuche':'Prüfungen und Tests'}</h2>{list.map(s=>{const result=s.status==='submitted'?sessionResult(s):null;return <article key={s.test_id}><div><h3>{MODULES.find(m=>m.slug===s.module)?.title} · {s.test_type==='original'?'Originalprüfung':`Modultest ${s.mode}`}</h3><p>{new Date(s.started_at).toLocaleString('de-DE')} · {s.status==='active'?'Läuft':s.status==='paused'?'Pausiert':s.status==='submitted'?(result?.vorlaeufig?'Vorläufig ausgewertet':'Ausgewertet'):'Verworfen'}{result?` · ${result.richtig} richtig · ${result.falsch} falsch · ${result.pending} offen`:''}</p></div>{s.status!=='abandoned'&&<button className="outline" disabled={busy} onClick={()=>openTest(s)}>{s.status==='submitted'?'Ergebnis ansehen':'Fortsetzen'}</button>}</article>;})}</section>:null;};
 const cards=(kind:'dashboard'|'learn'|'original'|'module')=>MODULES.map(m=>{const b=bundles[m.slug];const p=moduleProgress(b?.exam.questions??[],attempts,sessions);const type=kind==='original'?'original':'module';const existing=testSessions.find(s=>s.module===m.slug&&s.test_type===type&&['active','paused'].includes(s.status));return <section className="exam-card" key={m.slug}><span className="eyebrow">SOMMER 2017</span><h2>{m.title}</h2>{b?<>{kind==='dashboard'||kind==='learn'?<><p>{p.practiced}/{b.exam.questions.length} frei geübt · {p.attempts} Lernversuche</p><p className="hint">Letzte Lernaktivität: {p.lastActivity?new Date(p.lastActivity).toLocaleString('de-DE'):'Noch nicht begonnen'}</p>{kind==='dashboard'?<button className="primary" disabled={busy||!personalLoaded} onClick={()=>navigate('study',p.resumeNumber,m.slug)}>Lernen fortsetzen · {m.title}</button>:<div className="part-cards">{moduleParts(m,b.exam.questions).map(part=><button key={part.id} disabled={busy||!personalLoaded} onClick={()=>navigate('study',part.questions[0].question_number,m.slug)}><strong>{part.title}</strong><span>{part.questions.length} {part.label}</span><small>Frei auswählen und üben →</small></button>)}</div>}</>:<><p>{kind==='original'?`${b.exam.questions.length} Aufgaben in Originalreihenfolge · ${m.parts.map(p=>p.title).join(" + ")} · ${m.durationMinutes===null?'Prüfungszeit noch nicht bestätigt':m.durationMinutes+' Minuten'}`:`Neue gemischte Auswahl aus ${m.parts.map(p=>p.title).join(' und ')}. Eigene Sitzung ohne vorausgefüllte Antworten.`}</p>{existing&&<p>Eine {existing.status==='paused'?'pausierte':'laufende'} Sitzung ist gespeichert.</p>}<div className="session-launch">{existing&&<button className="primary" disabled={busy||!personalLoaded} onClick={()=>openTest(existing)}>Fortsetzen · {m.title}</button>}{kind==='original'?<button className={existing?'outline':'primary'} disabled={busy||!personalLoaded} onClick={()=>void startTest(m.slug,'original')}>Neue Originalprüfung · {m.title}</button>:<><button className="outline" disabled={busy||!personalLoaded} onClick={()=>void startTest(m.slug,'module','kurz')}>Kurz starten · 6 MC + 2 U</button><button className="outline" disabled={busy||!personalLoaded} onClick={()=>void startTest(m.slug,'module','standard')}>Standard starten · 12 MC + 4 U</button></>}</div></>}</>:<p role={moduleErrors[m.slug]?'alert':'status'}>{moduleErrors[m.slug]??'Modul wird geladen…'}</p>}</section>;});
 return <div className="learning-root"><div className="learning-topbar"><button className="learning-brand" disabled={busy} onClick={()=>navigate('start')}>AP2 <span>lernen</span></button><nav aria-label="Hauptnavigation">{([{view:'start',label:'Start'},{view:'learn',label:'Lernen'},{view:'exams',label:'Originalprüfungen'},{view:'tests',label:'Tests'}] as {view:View;label:string}[]).map(item=><button key={item.view} disabled={busy} onClick={()=>navigate(item.view)} aria-current={locationState.view===item.view?'page':undefined}>{item.label}</button>)}</nav><span className="phase">Sommer 2017</span></div>
 {locationState.view==='review'&&bundle&&personalLoaded?<div className="review-shell" inert={routing}><div className="mode-banner"><strong>Review Mode · {config.title} · Daten und Quellen prüfen</strong><button className="primary" disabled={busy} onClick={()=>navigate('study')}>Zurück zum Lernen</button></div><ReviewWorkspace key={config.slug} config={config} suppliedExam={bundle.exam} suppliedAnswerKey={bundle.keys} selectedNumber={locationState.number} onQuestionChange={number=>{const next={...locationState,number};history.replaceState(null,'',routeUrl(next,location.href));setLocationState(next);}} onBusy={setReviewBusy} uSolutions={solutions} onHome={()=>navigate('start')}/></div>:
 <main className="learning-main">
 {testError&&<p role="alert" className="session-warning">{testError}</p>}
 {locationState.view==='study'&&<div className="compact-module"><span>Freies Lernen / Sommer 2017 / {config.title} / Aufgabe {locationState.number}</span><label>Modul <select aria-label="Lernmodul" disabled={busy} value={config.slug} onChange={e=>navigate('study',moduleProgress(bundles[e.target.value]?.exam.questions??[],attempts,sessions).resumeNumber,e.target.value)}>{MODULES.map(m=><option key={m.slug} value={m.slug}>{m.title}</option>)}</select></label></div>}
 {locationState.view==='start'?<><div className="eyebrow">DEIN LERNPLATZ</div><h1>Verstehen. Üben.<br/><span>Sicherer werden.</span></h1>{testHistory(undefined,'unfinished')}<h2>Schnell starten</h2><div className="mode-cards"><button disabled={busy} onClick={()=>navigate('learn')}><strong>Freies Lernen</strong><span>Aufgaben auswählen, Lösungen ansehen und in deinem Tempo üben.</span></button><button disabled={busy} onClick={()=>navigate('exams')}><strong>Originalprüfung</strong><span>Eine vollständige Prüfung in Originalreihenfolge bearbeiten.</span></button><button disabled={busy} onClick={()=>navigate('tests')}><strong>Modultests</strong><span>Eine neue gemischte Auswahl ohne frühere Antworten starten.</span></button></div><h2>Deine Module</h2><div className="module-cards">{cards('dashboard')}</div>{testHistory(undefined,'submitted')}</>:
 locationState.view==='learn'?<><h1>Freies Lernen</h1><p>Modul und Teil wählen. Dein persönlicher Lernfortschritt bleibt unabhängig von Prüfungen und Tests.</p><div className="module-cards">{cards('learn')}</div></>:
 locationState.view==='exams'?<><h1>Originalprüfungen</h1><p>Sommer 2017 · Alle Aufgaben des gewählten Moduls in Originalreihenfolge und unabhängige Antworten. Lösungen erst nach der Abgabe.</p><div className="module-cards">{cards('original')}</div>{testHistory('original')}</>:
 locationState.view==='tests'?<><h1>Modultests</h1><p>Übungstest aus Originalaufgaben · aktuell nur Sommer 2017</p><p>Kurz: 6 Auswahlaufgaben + 2 offene Aufgaben. Standard: 12 + 4. Zufällige Auswahl ohne Wiederholungen innerhalb eines Tests.</p><div className="module-cards">{cards('module')}</div>{testHistory('module')}</>:
 locationState.view==='session'?<>{testLoading||!bundle?<p>Lädt die gespeicherte Sitzung…</p>:selectedTest&&<ExamWorkspace key={selectedTest.test_id} initialSession={selectedTest} config={config} exam={bundle.exam} solutions={bundle.solutions} repository={repository} onUpdated={updatedTest} onBusy={setBusy}/>}</>:
 !bundle||!personalLoaded||!original||!current||!exam?<p role={moduleErrors[config.slug]?'alert':'status'}>{moduleErrors[config.slug]??'Lernbereich wird geladen…'}</p>:
 <><div className="learning-heading"><div><span className="eyebrow">SOMMER 2017 · {config.title}</span><h1>{currentPart?.title} · {currentPart?.label}</h1></div><span className="practice-label">Study Mode</span></div><nav className="part-nav" aria-label="Prüfungsteile">{moduleParts(config,exam.questions).map(part=><button key={part.title} disabled={busy||!part.questions.length} onClick={()=>navigate('study',part.questions[0].question_number)}>{part.title} · {part.questions.length} Aufgaben</button>)}</nav><nav className="learning-question-nav" aria-label="Aufgaben">{exam.questions.filter(q=>currentPart?.questionNumbers.includes(q.question_number)).map(q=><button disabled={busy} key={q.question_id} onClick={()=>navigate('study',q.question_number)} aria-label={`Aufgabe ${q.question_number}`} aria-current={q.question_id===current.question_id?'true':undefined} className={progress.done.has(q.question_id)?'completed':''}>{q.question_number}{progress.done.has(q.question_id)?' ✓':''}</button>)}</nav>
 <section className="reader"><div className="reader-head"><h2>Aufgabe {current.question_number}</h2><div className="source-links">{questionSources(current).map(source=><a key={source.source_page} className="outline" href={asset(current.source_pdf)+`#page=${source.source_page}`} target="_blank" rel="noreferrer">Original-PDF · Seite {source.source_page} ↗</a>)}</div></div><div className="question-art"><CropImage question={current} edited={!!review&&JSON.stringify(current.regions)!==JSON.stringify(original.regions)}/></div>
 {solution&&<details><summary>{config.descriptionLabel??'Gemeinsame Aufgabenbeschreibung'} & Anlagen</summary><a href={asset(current.source_pdf)+`#page=${config.descriptionPage}`} target="_blank" rel="noreferrer">{config.descriptionLabel??'Aufgabenbeschreibung'} · Seite {config.descriptionPage} ↗</a>{config.attachmentPages.map(page=><p key={page}><a href={asset(current.source_pdf)+`#page=${page}`} target="_blank" rel="noreferrer">Anlage · Seite {page} ↗</a></p>)}</details>}
 {currentPart?.kind==='multi_part'&&!solution?<p role="alert">Offizielle U-Lösung fehlt. Keine Bewertung möglich.</p>:<Practice key={original.question_id} questionId={original.question_id} number={original.question_number} answer={answer} u={solution} session={sessions.find(s=>s.question_id===original.question_id)} history={attempts.filter(a=>a.question_id===original.question_id)} onSession={saveSession} onAttempt={saveAttempt} onAnnotate={annotate} onBusy={setBusy}/>}
 </section><div className="study-pagination"><button disabled={busy||exam.questions.indexOf(original)===0} onClick={()=>navigate('study',exam.questions[exam.questions.indexOf(original)-1].question_number)}>← Vorherige Aufgabe</button><button disabled={busy||exam.questions.indexOf(original)===exam.questions.length-1} onClick={()=>navigate('study',exam.questions[exam.questions.indexOf(original)+1].question_number)}>Nächste Aufgabe →</button></div></>}

 <footer className="learning-footer"><span>Sommer 2017 · Fortschritt bleibt auf diesem Gerät</span>{locationState.view==='study'&&<button className="outline" disabled={busy||!bundle||!personalLoaded} onClick={()=>navigate('review')}>Review / Quellen</button>}<button className="outline" disabled={busy||!personalLoaded} onClick={()=>{const blob=new Blob([JSON.stringify({schema_version:2,attempts,sessions,testSessions},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ap2-learning-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Lernfortschritt exportieren</button></footer>
 </main>}
 {launch&&<section className="session-confirm" role="alertdialog" aria-label="Neue Sitzung bestätigen"><h2>Vorhandene Sitzung verwerfen und neu beginnen?</h2><p>Die laufende oder pausierte Sitzung wird als verworfen gespeichert. Ihre Antworten werden nicht in den neuen Versuch übernommen.</p><button className="primary" disabled={routing} onClick={()=>void startTest(launch.module,launch.type,launch.mode,{id:launch.replaceId,revision:launch.replaceRevision})}>Verwerfen und neu starten</button><button className="outline" disabled={routing} onClick={()=>setLaunch(null)}>Abbrechen</button></section>}
 </div>;
}
