import {validAttempt,type Attempt} from './model';
export type QuestionState='unanswered'|'correct'|'incorrect'|'partial';
export interface CurrentQuestionState {state:QuestionState;attempt_id?:string}
export interface ModuleDescriptor {exam:string;module:string;question_ids:string[]}
export interface ModuleProgress extends ModuleDescriptor {id:string;userId:string;generation:number;run_id:string;questionStates:Record<string,CurrentQuestionState>;started_at:string;reset_at:string|null;updated_at:string;revision:number}
export interface ModuleRun extends ModuleDescriptor {run_id:string;userId:string;progress_id:string;generation:number;started_at:string;legacy_attempt_ids:string[]}
export const progressId=(d:Pick<ModuleDescriptor,'exam'|'module'>)=>d.exam+'/'+d.module;
export const emptyStates=(ids:string[]):Record<string,CurrentQuestionState>=>Object.fromEntries(ids.map(id=>[id,{state:'unanswered'}]));
export function isFreeAttempt(a:Attempt){const v=a as unknown as Record<string,unknown>;return !['test_id','test_session_id','exam_session_id'].some(k=>v[k]!==undefined&&v[k]!==null);}
export function eligibleAttempt(a:Attempt){return validAttempt(a)&&a.correctness!==null&&isFreeAttempt(a)&&(!a.self_assessed||a.subparts.length>0&&a.subparts.every(p=>['richtig','teilweise','falsch'].includes(p.correctness)));}
export function stateFor(a?:Attempt):CurrentQuestionState{return a&&eligibleAttempt(a)?{state:a.correctness==='richtig'?'correct':a.correctness==='falsch'?'incorrect':'partial',attempt_id:a.attempt_id}:{state:'unanswered'};}
export function inRun(a:Attempt,run:ModuleRun){return a.userId===run.userId&&run.question_ids.includes(a.question_id)&&(!a.exam||a.exam===run.exam)&&(!a.module||a.module===run.module)&&eligibleAttempt(a)&&(a.progress_run_id===run.run_id||!a.progress_run_id&&run.generation===1&&run.legacy_attempt_ids.includes(a.attempt_id));}
export function latestInRun(attempts:Attempt[],run:ModuleRun,qid:string){return attempts.filter(a=>a.question_id===qid&&inRun(a,run)).sort((a,b)=>(a.progress_order??0)-(b.progress_order??0)||a.timestamp.localeCompare(b.timestamp)||a.attempt_id.localeCompare(b.attempt_id)).at(-1);}
export function summarizeProgress(p:ModuleProgress|undefined,ids:string[]=p?.question_ids??[]){const states=ids.map(id=>p?.questionStates[id]?.state??'unanswered');const correct=states.filter(s=>s==='correct').length,incorrect=states.filter(s=>s==='incorrect').length,partial=states.filter(s=>s==='partial').length,completed=correct+incorrect+partial;return {total:ids.length,completed,correct,incorrect,partial,open:ids.length-completed,rate:completed?Math.round(correct/completed*100):null};}
export function nextQuestion(p:ModuleProgress|undefined,ids:string[]){return ids.find(id=>(p?.questionStates[id]?.state??'unanswered')==='unanswered')??ids.find(id=>['incorrect','partial'].includes(p?.questionStates[id]?.state??''))??ids[0];}
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown):v is string=>typeof v==='string'&&!!v.trim();
const date=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
export function validDescriptor(v:unknown):v is ModuleDescriptor{return object(v)&&text(v.exam)&&text(v.module)&&Array.isArray(v.question_ids)&&v.question_ids.length>0&&v.question_ids.every(text)&&new Set(v.question_ids).size===v.question_ids.length;}
export function validModuleRun(v:unknown):v is ModuleRun {return validDescriptor(v)&&object(v)&&text(v.userId)&&text(v.run_id)&&v.progress_id===progressId(v)&&Number.isSafeInteger(v.generation)&&(v.generation as number)>0&&date(v.started_at)&&Array.isArray(v.legacy_attempt_ids)&&v.legacy_attempt_ids.every(text)&&(v.generation===1||v.legacy_attempt_ids.length===0);}
export function validModuleProgress(v:unknown):v is ModuleProgress {return validDescriptor(v)&&object(v)&&text(v.userId)&&v.id===progressId(v)&&text(v.run_id)&&Number.isSafeInteger(v.generation)&&(v.generation as number)>0&&Number.isSafeInteger(v.revision)&&(v.revision as number)>0&&date(v.started_at)&&date(v.updated_at)&&(v.reset_at===null||date(v.reset_at))&&object(v.questionStates)&&Object.keys(v.questionStates).length===v.question_ids.length&&v.question_ids.every(id=>{const s=(v.questionStates as Record<string,unknown>)[id];return object(s)&&['unanswered','correct','incorrect','partial'].includes(s.state as string)&&(s.state==='unanswered'?s.attempt_id===undefined:text(s.attempt_id));});}
