import {useEffect,useRef,useState} from 'react';
import {toggleSourceExam,type SourceExams} from './sourceExams';
import {yearSelectionLabel} from './examRegistry';
export default function SourceYearSelection({value,years,disabled=false,onChange}:{value:SourceExams;years:{id:string;label:string}[];disabled?:boolean;onChange:(next:SourceExams)=>void}){
 const [open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const ids=years.map(y=>y.id),selected=value==='all'?ids:value,unknown=selected.filter(id=>!ids.includes(id));
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[open]);
 return <div className="source-year-picker" ref={root}><button ref={trigger} type="button" className="outline" disabled={disabled} aria-expanded={open} aria-controls="source-year-popup" onClick={()=>setOpen(v=>!v)}>Jahrgänge: {yearSelectionLabel(value,years)} ▾</button>
 {open&&<fieldset id="source-year-popup" className="source-year-popup" disabled={disabled}><legend>Aufgaben aus</legend><label><input type="checkbox" checked={value==='all'} onChange={e=>onChange(e.target.checked?'all':[])}/>Alle Jahre</label><div className="selection-actions"><button type="button" className="outline" onClick={()=>onChange('all')}>Alle auswählen</button><button type="button" className="outline" onClick={()=>onChange([])}>Auswahl löschen</button></div><div className="source-year-scroll">{years.map(year=><label key={year.id}><input type="checkbox" checked={selected.includes(year.id)} onChange={()=>onChange(toggleSourceExam(value,ids,year.id))}/>{year.label}</label>)}</div></fieldset>}
 {value!=='all'&&!value.length&&<p role="alert">Mindestens einen Prüfungsjahrgang auswählen.</p>}{!!unknown.length&&<p role="alert">Ein ausgewählter Prüfungsjahrgang ist nicht verfügbar. Bitte die Auswahl anpassen.</p>}</div>;
}
