// Uses an isolated browser. Private baseline stays local and is never copied to evidence.
const {chromium}=require('playwright'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const baseline=JSON.parse(await fs.readFile(process.env.BASELINE_PATH||'private/phase2f-before-2018.json','utf8')),base=process.env.APP_URL||'http://127.0.0.1:5173/',dir=process.env.EVIDENCE_DIR||'docs/evidence/phase2f/browser';await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),checks={},errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async query=>{await page.goto(base+query);await page.getByRole('navigation',{name:'Hauptnavigation'}).waitFor();};
const dbAll=()=>page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,names=[...db.objectStoreNames],tx=db.transaction(names),out={};for(const name of names){const q=tx.objectStore(name).getAll();q.onsuccess=()=>out[name]=q.result;}tx.oncomplete=()=>{db.close();resolve(out);};};}));
const current=async()=>{const id=new URL(page.url()).searchParams.get('session');return (await dbAll()).testSessions.find(s=>s.test_id===id);};
const saved=()=>page.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();
const shot=name=>page.screenshot({path:dir+'/'+name+'.png',fullPage:true});
try{
 await go('?view=start');await page.getByRole('button',{name:'Freies Lernen',exact:false}).first().waitFor();
 await page.evaluate(data=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,names=Object.keys(data),tx=db.transaction(names,'readwrite');for(const name of names)for(const row of data[name])tx.objectStore(name).put(row);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};}),baseline);
 const old=baseline.testSessions[0];await go('?view=session&exam='+old.exam+'&module='+old.module+'&session='+old.test_id+'&years=all');await page.getByRole('heading',{name:'Sitzung pausiert'}).waitFor();assert.deepEqual(await dbAll(),baseline);await page.reload();await page.getByRole('heading',{name:'Sitzung pausiert'}).waitFor();assert.deepEqual(await current(),old);checks.old_records_exactly_unchanged=true;checks.old_all_years_test_not_reassembled=true;
 // Do not publish screenshots or contents of imported private baseline.
 await go('?view=exams&exam=2018-sommer&module=wiso');await page.getByRole('button',{name:'Neue Originalprüfung · WiSo',exact:true}).waitFor();assert.equal(await page.getByText('Noch nicht verfügbar',{exact:true}).count(),2);await shot('sommer2018-modules');checks.blocked_modules_not_enterable=true;
 const keys=await (await page.request.get(base+'data/2018_sommer_wiso_answers.json')).json(),q1=keys.answers.find(a=>String(a.question_number)==='1');assert.equal(q1.official_answer_status,'auto_ready');
 await go('?view=study&exam=2018-sommer&module=wiso&q=1');await page.getByText('Prüfungsaufgaben-Beschreibung & Anlagen',{exact:true}).click();assert.ok((await page.getByRole('link',{name:'Prüfungsaufgaben-Beschreibung · Seite 3 ↗',exact:true}).getAttribute('href')).includes('attachment-3-1.png'));checks.mc_shared_context_available=true;await page.getByRole('radio',{name:String(q1.official_answer),exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.learning-result').filter({hasText:'Richtig'}).waitFor();await page.getByText('Offizielle Antwortquelle',{exact:true}).click();await page.getByRole('img',{name:'Offizielle Antwortquelle Q1',exact:true}).waitFor();await shot('wiso-q1');checks.wiso_mc_official_source=true;
 await go('?view=study&exam=2018-sommer&module=wiso&q=U1');await page.locator('.subparts textarea').first().fill('Synthetische Browserprüfung');await page.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await page.getByRole('img',{name:'Offizielle Lösung U1',exact:true}).waitFor();for(const select of await page.locator('.part-assessment select').all())await select.selectOption('richtig');await page.getByRole('button',{name:'Bewertung speichern',exact:true}).click();await page.getByRole('button',{name:'Neuer Versuch',exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:'Neuer Versuch',exact:true}).waitFor();assert.equal(new URL(page.url()).searchParams.get('q'),'U1');await shot('wiso-u1');checks.wiso_u_self_assessment_persists=true;
 await go('?view=exams&exam=2018-sommer&module=wiso');await page.getByRole('button',{name:'Neue Originalprüfung · WiSo',exact:true}).click();await saved();let s=await current();await page.locator('.session-attachments summary').click();assert.ok((await page.locator('.session-attachments a').first().getAttribute('href')).includes('attachment-3-1.png'));checks.exam_mc_shared_context_available=true;assert.equal(s.question_ids.length,24);assert.deepEqual(s.source_mix.map(q=>q.question_number),[...Array.from({length:18},(_,i)=>String(i+1)),...Array.from({length:6},(_,i)=>'U'+(i+1))]);await page.getByRole('radio',{name:String(q1.official_answer),exact:true}).check();await saved();assert.equal(await page.locator('.submitted-answer').count(),0);await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();const paused=await current();await page.reload();await page.getByRole('heading',{name:'Sitzung pausiert'}).waitFor();assert.deepEqual(await current(),paused);await page.getByRole('button',{name:'Sitzung fortsetzen',exact:true}).click();await saved();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await saved();assert.equal((await current()).result.richtig,1);await shot('wiso-original-result');checks.original_order_pause_refresh_submit=true;
 const mixes=[];
 for(const years of ['all','2018-sommer','2017-sommer','2017-18-winter']){
  await go('?view=tests&years='+years+'&module=wiso&exam=2018-sommer');const filter=page.getByRole('combobox',{name:'Aufgaben aus',exact:true});assert.equal(await filter.inputValue(),years);await filter.selectOption(years==='all'?'2018-sommer':'all');await page.goBack();assert.equal(await filter.inputValue(),years);await page.goForward();assert.notEqual(await filter.inputValue(),years);await page.goBack();await page.reload();assert.equal(await filter.inputValue(),years);
  const card=page.locator('.exam-card').filter({has:page.getByRole('heading',{name:'WiSo',exact:true})});await card.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await saved();s=await current();const actual=[...new Set(s.source_mix.map(q=>q.exam))].sort();assert.deepEqual(actual,years==='all'?['2017-18-winter','2017-sommer','2018-sommer']:[years]);assert.equal(new Set(s.question_ids).size,8);assert.deepEqual(s.sourceExams,years==='all'?'all':[years]);assert.ok(s.source_mix.every(q=>q.question_source_id&&q.solution_source_id&&q.official_answer_revision&&q.question_snapshot));mixes.push({filter:years,source_mix:s.source_mix.map(q=>({exam:q.exam,question_id:q.question_id}))});
  const mc=s.question_ids.find(id=>s.question_models[id].kind==='multiple_choice'),position=s.question_ids.indexOf(mc)+1,number=s.question_models[mc].number,label='Prüfungsaufgabe '+number+(actual.length>1?' · '+({'2017-sommer':'Sommer 2017','2017-18-winter':'Winter 2017/18','2018-sommer':'Sommer 2018'}[s.source_mix.find(q=>q.question_id===mc).exam])+' · Position '+position:'');await page.getByRole('button',{name:label,exact:true}).click();await saved();await page.getByRole('radio',{name:String(s.official_answers[mc]),exact:true}).check();await saved();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await saved();assert.equal((await current()).result.richtig,1);await shot('test-'+years);
 }
 checks.three_season_all_years=true;checks.single_year_exclusive=true;checks.back_forward_refresh=true;checks.immutable_provenance_snapshots=true;
 const after=await dbAll();assert.deepEqual(after.attempts.filter(a=>baseline.attempts.some(b=>b.attempt_id===a.attempt_id)),baseline.attempts);assert.deepEqual(after.testSessions.find(s=>s.test_id===old.test_id),old);for(const table of ['records','reviews','answerReviews'])assert.deepEqual(after[table],baseline[table]);checks.old_personal_and_review_data_unchanged=true;
 await go('?view=tests&years=2018-sommer&module=wiso');await page.getByRole('combobox',{name:'Aufgaben aus',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.mobile_no_overflow=true;assert.deepEqual(errors,[]);
 await fs.writeFile(dir+'/acceptance.json',JSON.stringify({url:base,checks,mixes,isolated_browser:true,private_baseline_not_published:true,errors},null,2));console.log('Passed Phase2F browser acceptance',checks);
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
