const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir=process.env.EVIDENCE_DIR||'docs/evidence/full-pdf/browser';fs.mkdirSync(dir,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
const index=await(await p.request.get(base+'data/full_pdf_sources.json')).json();let documents=0;for(const doc of Object.values(index.documents)){const r=await p.request.get(base+doc.path,{headers:{Range:'bytes=0-7'}});assert.ok([200,206].includes(r.status()),doc.path);assert.match(r.headers()['content-type'],/pdf/);assert.ok((await r.body()).subarray(0,5).equals(Buffer.from('%PDF-')),doc.path);documents++;}
for(const [exam,module] of [['2017-18-winter','arbeitsplanung'],['2023-sommer','funktionsanalyse'],['2024-25-winter','wiso']]){await p.goto(base+`?view=study&exam=${exam}&module=${module}&q=1`);const link=p.locator('.reader>.reader-head .source-links a').first();await link.waitFor();assert.match(await link.getAttribute('href'),/\.pdf#page=\d+$/);await p.screenshot({path:dir+'/'+exam+'-'+module+'.png'});await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();const solution=p.locator('.learning-result .mc-source').locator('..').locator('a');await solution.waitFor();assert.match(await solution.getAttribute('href'),/\.pdf#page=\d+$/);}
await p.goto(base+'?view=study&exam=2021-sommer&module=arbeitsplanung&q=U1');await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.locator('.u-solution-image').waitFor();for(const href of await p.locator('.learning-result .source-links a').evaluateAll(els=>els.map(e=>e.getAttribute('href'))))assert.match(href,/\.pdf#page=\d+$/);await p.locator('.external-attachments summary').first().click();assert.match(await p.locator('.external-attachments a').first().getAttribute('href'),/\.pdf#page=1$/);
await p.goto(base+'?view=bank');await p.getByLabel('Modul',{exact:true}).selectOption('arbeitsplanung');await p.getByLabel('Jahrgang',{exact:true}).selectOption('2017-18-winter');await p.getByRole('button',{name:'Training starten',exact:true}).click();await p.locator('.training-workspace .reader-head a').first().waitFor();assert.match(await p.locator('.training-workspace .reader-head a').first().getAttribute('href'),/\.pdf#page=\d+$/);await p.reload();await p.locator('.training-workspace .reader-head a').first().waitFor();assert.match(await p.locator('.training-workspace .reader-head a').first().getAttribute('href'),/\.pdf#page=\d+$/);
await p.goto(base+'?view=exams&exam=2017-18-winter&module=arbeitsplanung');await p.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).click();await p.getByRole('radio',{name:'1',exact:true}).waitFor();assert.match(await p.getByRole('link',{name:/Zeitvorgabe/}).getAttribute('href'),/\.pdf#page=2$/);await p.getByRole('radio',{name:'1',exact:true}).check();await p.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await p.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await p.getByRole('link',{name:'Offizielle Antwortquelle ↗',exact:true}).waitFor();assert.match(await p.getByRole('link',{name:'Offizielle Antwortquelle ↗',exact:true}).getAttribute('href'),/\.pdf#page=10$/);
await p.setViewportSize({width:390,height:844});await p.goto(base+'?view=study&exam=2024-25-winter&module=wiso&q=1');await p.locator('.reader>.reader-head .source-links a').waitFor();await p.screenshot({path:dir+'/mobile.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/checks.json',JSON.stringify({documents,all_http_pdf_headers_verified:true,original_pdf_navigation:true,mc_pdf:true,u_pdf:true,attachment_pdf:true,training_refresh:true,legacy_exam_answer_fallback:true,isolated_browser:true,errors},null,2));console.log('Full PDF browser checks passed',documents);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
