const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
 const base=process.env.APP_URL||'http://127.0.0.1:5173/';const evidence=process.env.EVIDENCE_DIR||'docs/evidence/phase2e/lifecycle';await fs.mkdir(evidence,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks={};
 const nav=name=>page.getByRole('navigation',{name:'Hauptnavigation',exact:true}).getByRole('button',{name,exact:true});
 const card=name=>page.getByRole('region',{name:'Sommer 2017',exact:true}).locator('.exam-card').filter({has:page.getByRole('heading',{name,exact:true})});
 const snapshot=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,names=['records','attempts','learningSessions','reviews','answerReviews','testSessions'],tx=db.transaction(names,'readonly'),queries=Object.fromEntries(names.map(n=>[n,tx.objectStore(n).getAll()]));tx.oncomplete=()=>{resolve({...Object.fromEntries(names.map(n=>[n,queries[n].result])),version:db.version});db.close();};};}));
 const current=async()=>{const id=new URL(page.url()).searchParams.get('session');return(await snapshot()).testSessions.find(s=>s.test_id===id);};const ready=()=>page.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();const saved=()=>page.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();
 const start=async(name='Arbeitsplanung')=>{await nav('Originalprüfungen').click();await card(name).getByRole('button',{name:'Neue Originalprüfung · '+name,exact:true}).click();await ready();return await current();};
 try{
  await page.goto(base+'?view=study&exam=2017-sommer&module=arbeitsplanung&q=1');await page.getByRole('heading',{name:'Aufgabe 1',exact:true}).waitFor();await page.getByRole('radio',{name:'4',exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();await page.getByText('Notiz',{exact:true}).click();await page.getByLabel('Lernnotiz',{exact:true}).fill('Unabhängige alte Lernnotiz');await page.getByRole('button',{name:'Reflexion speichern',exact:true}).click();await page.getByText('Reflexion gespeichert',{exact:true}).waitFor();const baseline=await snapshot();assert.equal(baseline.version,60);
  const first=await start();await page.getByRole('radio',{name:'3',exact:true}).check();await saved();let before=await current();
  for(const action of ['Versuch verwerfen','Versuch löschen']){await page.getByRole('button',{name:action,exact:true}).click();assert.equal(await page.getByRole('radio',{name:'3',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Abbrechen',exact:true}).click();assert.deepEqual(await current(),before);}checks.active_cancel_keeps_answers=true;
  await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();before=await current();for(const action of ['Versuch verwerfen','Versuch löschen']){await page.getByRole('button',{name:action,exact:true}).click();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();assert.deepEqual(await current(),before);}checks.paused_cancel_preserves_timer=true;
  await page.getByRole('button',{name:'Sitzung fortsetzen',exact:true}).click();await saved();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('region',{name:'Ergebnis',exact:true}).waitFor();before=await current();assert.equal(before.status,'completed');assert.equal(before.result.falsch,1);
  await page.getByRole('button',{name:'Versuch löschen',exact:true}).click();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();assert.deepEqual(await current(),before);await page.getByRole('button',{name:'Versuch verwerfen',exact:true}).click();await page.getByRole('button',{name:'Verwerfen bestätigen',exact:true}).click();await page.getByRole('heading',{name:'Versuch verworfen',exact:true}).waitFor();const discarded=(await snapshot()).testSessions.find(s=>s.test_id===first.test_id);assert.equal(discarded.status,'discarded');assert.deepEqual(discarded.answers,before.answers);assert.deepEqual(discarded.result,before.result);assert.equal(discarded.completed_at,before.completed_at);checks.completed_discard_preserves_result=true;
  await nav('Start').click();assert.equal(await page.locator(`[data-test-id="${first.test_id}"]`).count(),0);await nav('Originalprüfungen').click();assert.equal(await page.locator(`[data-test-id="${first.test_id}"]`).count(),0);await page.getByRole('button',{name:'Verworfene Versuche anzeigen',exact:true}).click();await page.locator(`[data-test-id="${first.test_id}"]`).waitFor();await page.reload();assert.equal(await page.locator(`[data-test-id="${first.test_id}"]`).count(),0);await page.getByRole('button',{name:'Verworfene Versuche anzeigen',exact:true}).click();const discardedRow=page.locator(`[data-test-id="${first.test_id}"]`);await discardedRow.getByRole('button',{name:'Versuch löschen',exact:true}).click();await page.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await discardedRow.waitFor({state:'detached'});assert.equal((await snapshot()).testSessions.some(s=>s.test_id===first.test_id),false);checks.hidden_discarded_history_and_delete=true;
  const paused=await start('Funktionsanalyse');await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();await page.getByRole('button',{name:'Versuch löschen',exact:true}).click();await page.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await page.getByRole('heading',{name:'Modultests',exact:true}).waitFor();assert.equal((await snapshot()).testSessions.some(s=>s.test_id===paused.test_id),false);checks.paused_delete=true;
  const raced=await start();const url=page.url();const other=await context.newPage();await other.goto(url);await other.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();await page.getByRole('button',{name:'Versuch löschen',exact:true}).click();await other.getByRole('radio',{name:'1',exact:true}).check();await other.locator('.save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();await page.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await page.getByRole('alert').filter({hasText:'anderen Fenster'}).waitFor();assert.equal((await current()).answers[raced.question_ids[0]].choice,'1');assert.equal(await page.getByRole('radio',{name:'1',exact:true}).isChecked(),true);await other.close();checks.stale_confirmation_refuses_delete_and_refreshes=true;
  await page.getByRole('button',{name:'Versuch löschen',exact:true}).click();await page.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await page.getByRole('heading',{name:'Modultests',exact:true}).waitFor();assert.equal((await snapshot()).testSessions.some(s=>s.test_id===raced.test_id),false);checks.active_delete=true;
  const completed=await start();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('region',{name:'Ergebnis',exact:true}).waitFor();await nav('Start').click();const completedRow=page.locator(`[data-test-id="${completed.test_id}"]`);await completedRow.waitFor();await completedRow.getByRole('button',{name:'Versuch löschen',exact:true}).click();await page.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await completedRow.waitFor({state:'detached'});assert.equal((await snapshot()).testSessions.some(s=>s.test_id===completed.test_id),false);checks.completed_history_delete=true;
  const active=await start('Funktionsanalyse');await page.getByRole('button',{name:'Versuch verwerfen',exact:true}).click();await page.getByRole('button',{name:'Verwerfen bestätigen',exact:true}).click();await page.getByRole('heading',{name:'Versuch verworfen',exact:true}).waitFor();assert.equal((await snapshot()).testSessions.find(s=>s.test_id===active.test_id).status,'discarded');checks.active_discard=true;
  const pausedDiscard=await start();await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();await page.getByRole('button',{name:'Versuch verwerfen',exact:true}).click();await page.getByRole('button',{name:'Verwerfen bestätigen',exact:true}).click();await page.getByRole('heading',{name:'Versuch verworfen',exact:true}).waitFor();assert.equal((await snapshot()).testSessions.find(s=>s.test_id===pausedDiscard.test_id).status,'discarded');checks.paused_discard=true;
  const otherSessionsBefore=(await snapshot()).testSessions;
  await nav('Tests').click();const moduleCard=page.locator('.exam-card').filter({has:page.getByRole('heading',{name:'Arbeitsplanung',exact:true})});await moduleCard.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await ready();const moduleTest=await current();assert.equal(moduleTest.test_type,'module');assert.equal(moduleTest.question_ids.length,8);assert.deepEqual(moduleTest.answers,{});
  await page.getByRole('radio',{name:'3',exact:true}).check();await saved();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('region',{name:'Ergebnis',exact:true}).waitFor();const moduleCompleted=await current();assert.equal(moduleCompleted.status,'completed');assert.ok(moduleCompleted.result);await nav('Tests').click();let moduleRow=page.locator(`[data-test-id="${moduleTest.test_id}"]`);await moduleRow.waitFor();await nav('Start').click();await moduleRow.waitFor();checks.module_completed_in_history_and_dashboard=true;
  await moduleRow.getByRole('button',{name:'Versuch verwerfen',exact:true}).click();await page.getByRole('button',{name:'Verwerfen bestätigen',exact:true}).click();await moduleRow.waitFor({state:'detached'});const moduleDiscarded=(await snapshot()).testSessions.find(s=>s.test_id===moduleTest.test_id);assert.equal(moduleDiscarded.status,'discarded');assert.deepEqual(moduleDiscarded.answers,moduleCompleted.answers);assert.deepEqual(moduleDiscarded.result,moduleCompleted.result);await nav('Tests').click();if(await page.getByRole('button',{name:'Verworfene Versuche ausblenden',exact:true}).count())await page.getByRole('button',{name:'Verworfene Versuche ausblenden',exact:true}).click();assert.equal(await moduleRow.count(),0);await page.reload();await page.getByRole('heading',{name:'Modultests',exact:true}).waitFor();assert.equal(await moduleRow.count(),0);await nav('Start').click();assert.equal(await moduleRow.count(),0);checks.module_discard_hidden_by_default=true;
  await nav('Tests').click();await page.getByRole('button',{name:'Verworfene Versuche anzeigen',exact:true}).click();await moduleRow.waitFor();await moduleRow.getByRole('button',{name:'Versuch löschen',exact:true}).click();await page.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await moduleRow.waitFor({state:'detached'});const afterModuleDelete=await snapshot();assert.equal(afterModuleDelete.testSessions.some(s=>s.test_id===moduleTest.test_id),false);assert.deepEqual(afterModuleDelete.testSessions,otherSessionsBefore);checks.module_permanent_delete_keeps_other_sessions=true;
  const final=await snapshot();for(const name of ['records','attempts','learningSessions','reviews','answerReviews'])assert.deepEqual(final[name],baseline[name]);assert.equal(final.testSessions.filter(s=>s.status==='completed').length,0);checks.all_ordinary_data_unchanged=true;
  await nav('Tests').click();if(await page.getByRole('button',{name:'Verworfene Versuche anzeigen',exact:true}).count())await page.getByRole('button',{name:'Verworfene Versuche anzeigen',exact:true}).click();await page.screenshot({path:evidence+'/discarded-history.png',fullPage:true});assert.deepEqual(errors,[]);await fs.writeFile(evidence+'/browser-acceptance.json',JSON.stringify({url:base,checks,page_errors:errors},null,2));console.log(JSON.stringify(checks,null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
