const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5175/',dir=process.env.EVIDENCE_DIR||'docs/evidence/expansion2026-release/browser';fs.mkdirSync(dir,{recursive:true});const server=process.env.APP_URL?null:require('node:child_process').spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','5175','--strictPort'],{stdio:'ignore',windowsHide:true});if(server)await new Promise(r=>setTimeout(r,1500));const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage({viewport:{width:1440,height:1000}}),checks=[];try{
 for(const exam of ['2025-26-winter','2026-sommer'])for(const module of ['arbeitsplanung','funktionsanalyse','wiso']){
  await p.goto(base+`?view=study&exam=${exam}&module=${module}&q=1`);await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).waitFor();const source=p.getByRole('link',{name:/Original-PDF · Seite/}).first();assert.ok((await source.getAttribute('href')).includes('.pdf#page='));await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.locator('.mc-source').waitFor();await p.goto(base+`?view=study&exam=${exam}&module=${module}&q=U1`);await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.locator('.u-solution-image').waitFor();checks.push({exam,module,MC_source:true,U_source:true,full_pdf:true});
 }
 await p.goto(base+'?view=bank');await p.getByTestId('bank-count').filter({hasText:'1560 Aufgaben gefunden'}).waitFor();await p.screenshot({path:dir+'/bank-1560.png'});
 for(const exam of ['2025-26-winter','2026-sommer']){await p.goto(base+`?view=exams&exam=${exam}&module=arbeitsplanung`);await p.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).waitFor();await p.screenshot({path:dir+'/'+exam+'.png'});}
 await p.goto(base+'?view=tests&years=2025-26-winter,2026-sommer&module=arbeitsplanung');await p.getByRole('button',{name:'Kurz starten · 6 MC + 2 U'}).first().waitFor();await p.getByRole('button',{name:'Kurz starten · 6 MC + 2 U'}).first().click();await p.waitForURL(/view=session/);
 const mix=await p.evaluate(async()=>{const r=indexedDB.open('ap2-private-learning');const db=await new Promise(res=>r.onsuccess=()=>res(r.result));const tx=db.transaction('testSessions','readonly'),req=tx.objectStore('testSessions').getAll();return new Promise(res=>req.onsuccess=()=>{db.close();res(req.result[0].source_mix.map(q=>q.exam))})});assert.deepEqual([...new Set(mix)].sort(),['2025-26-winter','2026-sommer']);checks.push({cross_year_test_sources:[...new Set(mix)],bank_count:1560});fs.writeFileSync(dir+'/checks.json',JSON.stringify(checks,null,2));console.log(checks);
 await p.goto(base+'?view=start');const resume=p.getByTestId('home-resume');await resume.getByRole('button',{name:'Fortsetzen',exact:true}).waitFor();assert.equal(await resume.getByRole('button',{name:'Versuch verwerfen',exact:true}).count(),1);assert.equal(await resume.getByRole('button',{name:'Versuch löschen',exact:true}).count(),1);await p.screenshot({path:dir+'/active-test-home.png'});checks.push('Active test retains resume/discard/delete in first section');fs.writeFileSync(dir+'/checks.json',JSON.stringify(checks,null,2));
 }catch(e){await p.screenshot({path:dir+'/failure.png',fullPage:true});throw e;}finally{await b.close();server?.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
