const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5173/',dir='docs/evidence/phase2i1';await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),checks={},errors=[];p.on('pageerror',e=>errors.push(e.message));
const all=()=>p.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,tx=db.transaction([...db.objectStoreNames]),out={};for(const name of db.objectStoreNames){const q=tx.objectStore(name).getAll();q.onsuccess=()=>out[name]=q.result}tx.oncomplete=()=>{db.close();resolve(out)}}}));
try{
 await p.goto(base+'?view=study&exam=2017-sommer&module=arbeitsplanung&q=1');await p.getByRole('radio',{name:'1',exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.getByText('Antwort und Ergebnis gespeichert',{exact:true}).waitFor();
 await p.goto(base+'?view=tests&years=2017-sommer&module=arbeitsplanung');const card=p.locator('.exam-card').filter({has:p.getByRole('heading',{name:'Arbeitsplanung',exact:true})});await card.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await p.getByRole('button',{name:'Pausieren',exact:true}).click();await p.getByRole('heading',{name:'Sitzung pausiert'}).waitFor();const before=await all();
 await p.goto(base+'?view=answer-review');await p.getByRole('heading',{name:'Arbeitsplanung · Q3',exact:true}).waitFor();assert.equal(await p.locator('input[type=radio]:checked').count(),0);assert.equal(await p.getByRole('button',{name:'Speichern',exact:true}).isDisabled(),true);await p.getByRole('img',{name:'Originale Antwortquelle Arbeitsplanung Q3',exact:true}).waitFor();await p.screenshot({path:dir+'/review-initial.png',fullPage:true});checks.no_candidate_preselection=true;
 const queue=await(await p.request.get(base+'data/manual_answer_review_queue.json')).json();
 for(let i=0;i<8;i++){const q=queue.items[i];await p.getByRole('heading',{name:q.module+' · Q'+q.question_number,exact:true}).waitFor();await p.getByRole('radio',{name:String(i%5+1),exact:true}).check();await p.getByRole('button',{name:'Speichern',exact:true}).click();await p.getByText('Gespeichert · Confirmed · gesperrt',{exact:true}).waitFor();if(i<7)await p.getByRole('button',{name:'Next →',exact:true}).click();}
 await p.reload();await p.getByText('8/8 bestätigt',{exact:true}).waitFor();assert.equal(await p.getByRole('radio',{name:'3',exact:true}).isChecked(),true);checks.eight_synthetic_confirmations_persist=true;
 const after=await all();assert.equal(after.answerReviews.length,8);for(const r of after.answerReviews){assert.equal(r.confirmation_method,'manual_source_review');assert.equal(r.locked,true);assert.equal(r.user_corrected,true)}for(const name of ['attempts','learningSessions','testSessions','records','reviews'])assert.deepEqual(after[name],before[name]);checks.old_learning_tests_reviews_unchanged=true;
 const pending=p.waitForEvent('download');await p.getByRole('button',{name:'Bestätigungen exportieren (8/8)',exact:true}).click();const d=await pending,stream=await d.createReadStream(),chunks=[];for await(const x of stream)chunks.push(x);const exported=JSON.parse(Buffer.concat(chunks));assert.equal(exported.confirmations.length,8);assert.ok(exported.confirmations.every(r=>!('userId' in r)&&r.evidence_hash));checks.export_contains_only_bound_confirmations=true;
 await p.route('**/data/manual_answer_review_queue.json',async route=>{const q=structuredClone(queue);q.items[0].parser_revision='synthetic-new-parser';q.items[0].official_answer=5;await route.fulfill({json:q})});await p.goto(base+'?view=answer-review');await p.getByText(/Machine suggestion changed/).waitFor();assert.equal(await p.getByRole('radio',{name:'1',exact:true}).isChecked(),true);assert.equal((await all()).answerReviews.find(r=>r.question_id===queue.items[0].question_id).official_answer,1);checks.changed_machine_does_not_overwrite=true;
 await p.route('**/'+queue.items[0].source_crop,route=>route.fulfill({status:200,body:'corrupt'}));await p.reload();await p.getByText(/Quellbild konnte nicht verifiziert/).waitFor();assert.equal(await p.getByRole('button',{name:'Speichern',exact:true}).isDisabled(),true);checks.source_hash_failure_disables_save=true;
 const clean=await browser.newContext({viewport:{width:390,height:844}}),mobile=await clean.newPage();await mobile.goto(base+'?view=answer-review');await mobile.getByRole('heading',{name:'Arbeitsplanung · Q3',exact:true}).waitFor();await mobile.getByRole('img',{name:'Originale Antwortquelle Arbeitsplanung Q3',exact:true}).waitFor();assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:dir+'/review-mobile.png',fullPage:true});checks.mobile_no_overflow=true;await clean.close();assert.deepEqual(errors,[]);await fs.writeFile(dir+'/acceptance.json',JSON.stringify({checks,synthetic_records_only:true,real_user_confirmations:0,production_modules_promoted:0,pdf_rescan:0,errors},null,2));console.log(checks);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
