const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
 const base=process.env.APP_URL||'http://127.0.0.1:5173/';const evidence=process.env.EVIDENCE_DIR||'docs/evidence/phase2c';await fs.mkdir(evidence,{recursive:true});
 const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks={};
 const nav=name=>page.getByRole('navigation',{name:'Hauptnavigation',exact:true}).getByRole('button',{name,exact:true});
 const card=name=>page.locator('.exam-card').filter({has:page.getByRole('heading',{name,exact:true})});
 const ready=()=>page.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();
 const saved=()=>page.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();
 const snapshot=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result;const tx=db.transaction(['attempts','learningSessions','testSessions','reviews','answerReviews'],'readonly');const a=tx.objectStore('attempts').getAll(),s=tx.objectStore('learningSessions').getAll(),t=tx.objectStore('testSessions').getAll(),r1=tx.objectStore('reviews').getAll(),r2=tx.objectStore('answerReviews').getAll();tx.oncomplete=()=>{resolve({attempts:a.result,sessions:s.result,tests:t.result,reviews:r1.result,answerReviews:r2.result,version:db.version});db.close();};};}));
 const current=async()=>{const id=new URL(page.url()).searchParams.get('session');return (await snapshot()).tests.find(t=>t.test_id===id);};
 try{
  await page.goto(base+'?q=1');await page.getByRole('heading',{name:'Aufgabe 1',exact:true}).waitFor();for(const name of ['Start','Lernen','Originalprüfungen','Tests'])assert.equal(await nav(name).count(),1);assert.equal(await page.locator('.module-nav').count(),0);checks.navigation_four_modes=true;
  await page.getByRole('radio',{name:'4',exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();
  await page.getByText('Notiz',{exact:true}).click();await page.getByLabel('Lernnotiz',{exact:true}).fill('Alte freie Lernnotiz');await page.getByRole('button',{name:'Reflexion speichern',exact:true}).click();await page.getByText('Reflexion gespeichert',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Teil B · 8 Aufgaben',exact:true}).click();assert.equal(await page.getByLabel('U1 Bewertung 1',{exact:true}).count(),0);await page.getByLabel('U1 Teil 1',{exact:true}).fill('Freier Entwurf');await page.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await page.getByLabel('U1 Bewertung 1',{exact:true}).waitFor();checks.free_assessment_only_after_reveal=true;
  const baseline=await snapshot();
  await nav('Originalprüfungen').click();await card('Arbeitsplanung').getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).click();await ready();let s=await current();const originalId=s.test_id;
  assert.equal(s.question_ids.length,36);assert.deepEqual(s.question_ids.map(id=>s.question_models[id].number),[...Array.from({length:28},(_,i)=>String(i+1)),...Array.from({length:8},(_,i)=>'U'+(i+1))]);assert.deepEqual(s.answers,{});assert.equal(await page.locator('input[type=radio]:checked').count(),0);assert.equal(await page.locator('.mc-source,.u-solution-image').count(),0);checks.original_order_fresh_no_leak=true;
  assert.equal(s.duration_minutes,105);await page.getByRole('radio',{name:'3',exact:true}).check();await saved();await page.getByRole('button',{name:'Prüfungsaufgabe U1',exact:true}).click();await saved();await page.getByLabel('Prüfung U1 Teil 1',{exact:true}).fill('Prüfungsantwort');await saved();assert.equal(await page.locator('.part-assessment').count(),0);
  await page.reload();await ready();assert.equal(await page.getByLabel('Prüfung U1 Teil 1',{exact:true}).inputValue(),'Prüfungsantwort');assert.equal((await current()).current_question,s.question_ids[28]);checks.answer_cursor_refresh=true;
  await page.getByRole('button',{name:'Pausieren',exact:true}).click();await page.getByRole('heading',{name:'Sitzung pausiert',exact:true}).waitFor();const paused=(await current()).elapsed_time;await page.reload();await ready();await page.waitForTimeout(1100);assert.equal((await current()).elapsed_time,paused);assert.equal(await page.locator('.session-question').count(),0);await page.getByRole('button',{name:'Sitzung fortsetzen',exact:true}).click();await saved();checks.pause_resume_persistent=true;
  const sessionUrl=page.url();await nav('Lernen').click();await card('Arbeitsplanung').getByRole('button',{name:/Teil A/}).click();await page.locator('.result-banner.richtig').waitFor();await page.goBack();await page.goBack();await ready();assert.equal(new URL(page.url()).searchParams.get('session'),originalId);await page.goForward();await page.getByRole('heading',{name:'Freies Lernen',exact:true}).waitFor();await page.goBack();await ready();checks.leave_free_back_forward_safe=true;
  await page.evaluate(id=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,tx=db.transaction('testSessions','readwrite'),store=tx.objectStore('testSessions');const g=store.get(['local',id]);g.onsuccess=()=>store.put({...g.result,active_since:Date.now()-106*60000});tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};}),originalId);await page.reload();await ready();await page.getByText('Die Richtzeit ist erreicht.',{exact:false}).waitFor();assert.equal((await current()).status,'active');checks.timer_105_advisory_no_autosubmit=true;
  await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();assert.equal((await current()).status,'active');await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('heading',{name:'Vorläufiges Ergebnis',exact:true}).waitFor();s=await current();assert.equal(s.result.pending,1);assert.equal(s.result.falsch,1);assert.equal(s.result.unbeantwortet,34);checks.submit_pending_not_wrong=true;
  await page.locator('.u-solution-image').evaluate(img=>img.decode());assert.equal(await page.getByRole('link',{name:/Originalaufgabe · PDF-Seite/}).count(),1);for(let i=1;i<=3;i++)await page.getByLabel(`Prüfung U1 Bewertung ${i}`,{exact:true}).selectOption('richtig');await saved();assert.equal((await current()).result.pending,0);await page.getByLabel('Prüfung U1 Bewertung 2',{exact:true}).selectOption('teilweise');await saved();assert.equal((await current()).result.teilweise,1);await page.reload();await ready();assert.equal(await page.getByLabel('Prüfung U1 Bewertung 2',{exact:true}).inputValue(),'teilweise');await page.getByRole('button',{name:'Prüfungsaufgabe 1',exact:true}).click();await saved();await page.locator('.mc-source').evaluate(img=>img.decode());assert.equal(await page.getByRole('radio',{name:'3',exact:true}).isDisabled(),true);checks.result_source_decode_editable_U=true;
  await page.screenshot({path:evidence+'/original-result.png',fullPage:true});
  await nav('Tests').click();await card('Arbeitsplanung').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await ready();const first=await current();assert.equal(first.question_ids.length,8);assert.equal(new Set(first.question_ids).size,8);assert.equal(Object.values(first.question_models).filter(m=>m.kind==='multiple_choice').length,6);assert.deepEqual(first.answers,{});assert.ok(await page.getByText('Auswahlkennung:',{exact:false}).count());checks.kurz_unique_mixed_blank=true;
  await nav('Tests').click();await card('Arbeitsplanung').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await page.getByRole('alertdialog',{name:'Neue Sitzung bestätigen',exact:true}).waitFor();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();assert.equal((await snapshot()).tests.find(t=>t.test_id===first.test_id).status,'active');await card('Arbeitsplanung').getByRole('button',{name:'Fortsetzen · Arbeitsplanung',exact:true}).click();await ready();assert.equal((await current()).test_id,first.test_id);checks.resume_cancel_keeps_existing=true;
  await nav('Tests').click();await card('Arbeitsplanung').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await page.getByRole('button',{name:'Verwerfen und neu starten',exact:true}).click();await ready();const second=await current();assert.notEqual(second.test_id,first.test_id);assert.notEqual(second.seed,first.seed);assert.notDeepEqual(second.question_ids,first.question_ids);assert.equal((await snapshot()).tests.find(t=>t.test_id===first.test_id).status,'abandoned');checks.new_seed_abandons_not_deletes=true;
  const mc=second.question_ids.find(id=>second.question_models[id].kind==='multiple_choice');await page.getByRole('button',{name:'Prüfungsaufgabe '+second.question_models[mc].number,exact:true}).click();await saved();const other=await context.newPage();await other.goto(page.url());await other.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();await other.getByRole('radio',{name:'1',exact:true}).check();await other.locator('.save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();await page.getByRole('radio',{name:'2',exact:true}).check();await page.getByRole('alert').filter({hasText:'Nicht gespeichert'}).waitFor();assert.equal((await current()).answers[mc].choice,'1');assert.equal(await page.getByRole('radio',{name:'1',exact:true}).isChecked(),true);await other.close();checks.revision_conflict_reloads_without_overwrite=true;
  await nav('Tests').click();await card('Funktionsanalyse').getByRole('button',{name:'Standard starten · 12 MC + 4 U',exact:true}).click();await ready();const standard=await current();assert.equal(standard.question_ids.length,16);assert.equal(new Set(standard.question_ids).size,16);assert.equal(Object.values(standard.question_models).filter(m=>m.kind==='multi_part').length,4);assert.equal(standard.module,'funktionsanalyse');assert.deepEqual(standard.answers,{});checks.standard_FA_12_4_unique=true;
  await nav('Originalprüfungen').click();await card('Funktionsanalyse').getByRole('button',{name:'Neue Originalprüfung · Funktionsanalyse',exact:true}).click();await ready();assert.equal((await current()).question_ids.length,36);assert.equal((await current()).duration_minutes,105);await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();await nav('Start').click();await page.getByRole('heading',{name:'Weiterlernen',exact:true}).waitFor();assert.ok(await page.getByRole('button',{name:'Fortsetzen',exact:true}).count());checks.FA_original_and_dashboard_resume=true;
  if(!process.env.APP_URL){
   const slow=await context.newPage();await slow.route('**/src/storage/storage.ts*',async route=>{const response=await route.fetch();const body=await response.text();const patched=body.replace('async updateTestSession(userId, id, revision, action) {','async updateTestSession(userId, id, revision, action) { await new Promise(resolve => setTimeout(resolve, 1500));');assert.notEqual(patched,body);await route.fulfill({response,body:patched});});
   const slowUrl=new URL(base);slowUrl.searchParams.set('view','session');slowUrl.searchParams.set('exam','2017-sommer');slowUrl.searchParams.set('module','arbeitsplanung');slowUrl.searchParams.set('session',second.test_id);await slow.goto(slowUrl.href);await slow.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();
   let warned=false;slow.once('dialog',async dialog=>{assert.equal(dialog.type(),'beforeunload');warned=true;await dialog.dismiss();});
   await slow.getByRole('radio',{name:'4',exact:true}).check();await slow.reload({timeout:4000}).catch(()=>{});assert.equal(warned,true);await slow.locator('.save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();await slow.reload();await slow.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();assert.equal(await slow.getByRole('radio',{name:'4',exact:true}).isChecked(),true);await slow.close();checks.pending_reload_guard_preserves_answer=true;
  }
  const shortUrl=new URL(base);for(const [key,value] of Object.entries({view:'session',exam:'2017-sommer',module:'arbeitsplanung',session:second.test_id}))shortUrl.searchParams.set(key,value);await page.goto(shortUrl.href);await ready();
  const shortU=second.question_ids.find(id=>second.question_models[id].kind==='multi_part');const shortModel=second.question_models[shortU];await page.getByRole('button',{name:'Prüfungsaufgabe '+shortModel.number,exact:true}).click();await saved();await page.getByLabel(`Prüfung ${shortModel.number} Teil ${shortModel.subpart_ids[0]}`,{exact:true}).fill('Modultest-Antwort');await saved();
  await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();assert.equal(await page.getByLabel(`Prüfung ${shortModel.number} Teil ${shortModel.subpart_ids[0]}`,{exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('heading',{name:'Vorläufiges Ergebnis',exact:true}).waitFor();assert.equal((await current()).result.pending,1);await page.locator('.u-solution-image').evaluate(img=>img.decode());for(const part of shortModel.subpart_ids)await page.getByLabel(`Prüfung ${shortModel.number} Bewertung ${part}`,{exact:true}).selectOption('richtig');await saved();assert.equal((await current()).result.pending,0);assert.equal((await current()).result.total,8);checks.kurz_submitted_U_self_assessed_source=true;
  await nav('Tests').click();await card('Funktionsanalyse').getByRole('button',{name:'Fortsetzen · Funktionsanalyse',exact:true}).click();await ready();const standardMC=standard.question_ids.find(id=>standard.question_models[id].kind==='multiple_choice');await page.getByRole('button',{name:'Prüfungsaufgabe '+standard.question_models[standardMC].number,exact:true}).click();await saved();await page.getByRole('radio',{name:String(standard.official_answers[standardMC]??1),exact:true}).check();await saved();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('region',{name:'Ergebnis',exact:true}).waitFor();assert.equal((await current()).result.total,16);assert.equal((await current()).result.unbeantwortet,15);await page.locator('.mc-source').evaluate(img=>img.decode());checks.standard_submitted_result_source=true;await page.screenshot({path:evidence+'/modultest-result.png',fullPage:true});
  await nav('Start').click();const recent=page.getByRole('region',{name:'Gespeicherte Sitzungen',exact:true}).filter({has:page.getByRole('heading',{name:'Letzte Prüfungen',exact:true})});assert.ok(await recent.getByRole('heading',{name:'Arbeitsplanung · Modultest kurz',exact:true}).count());assert.ok(await recent.getByRole('heading',{name:'Funktionsanalyse · Modultest standard',exact:true}).count());
  const final=await snapshot();assert.deepEqual(final.attempts,baseline.attempts);assert.deepEqual(final.sessions,baseline.sessions);assert.deepEqual(final.reviews,baseline.reviews);assert.deepEqual(final.answerReviews,baseline.answerReviews);assert.equal(final.version,50);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:evidence+'/dashboard-mobile.png',fullPage:true});assert.deepEqual(errors,[]);checks.personal_data_isolated_mobile_clean=true;
  await fs.writeFile(evidence+'/browser-acceptance.json',JSON.stringify({url:base,checks,passed:Object.keys(checks).length,page_errors:errors},null,2));console.log(JSON.stringify({passed:Object.keys(checks).length,checks},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
