const {chromium}=require('playwright');const fs=require('node:fs/promises');const assert=require('node:assert/strict');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5173/',dir=process.env.EVIDENCE_DIR||'docs/evidence/module-year-filter';await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
try{for(const years of ['all','2017-18-winter','2017-sommer']){const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'?view=tests&years='+years+'&module=arbeitsplanung');const filter=page.getByRole('combobox',{name:'Aufgaben aus',exact:true});await filter.waitFor();assert.equal(await filter.inputValue(),years);assert.equal(await page.getByRole('combobox',{name:'Prüfungsjahr',exact:true}).count(),0);assert.equal(await page.getByRole('navigation',{name:'Prüfungsjahr filtern'}).count(),0);
const current=()=>page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,t=db.transaction('testSessions'),q=t.objectStore('testSessions').get(['local',new URL(location.href).searchParams.get('session')]);t.oncomplete=()=>{resolve(q.result);db.close();};};}));const saved=()=>page.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();const tests=()=>page.getByRole('navigation',{name:'Hauptnavigation'}).getByRole('button',{name:'Tests',exact:true}).click();
await filter.selectOption(years==='all'?'2017-18-winter':'all');await page.goBack();assert.equal(await filter.inputValue(),years);await page.goForward();assert.notEqual(await filter.inputValue(),years);await page.goBack();await page.reload();assert.equal(await filter.inputValue(),years);
await page.locator('.exam-card .session-launch').first().waitFor();await page.screenshot({path:dir+'/'+years+'.png',fullPage:true});
for(const title of ['Arbeitsplanung','Funktionsanalyse','WiSo']){const card=page.locator('.exam-card').filter({has:page.getByRole('heading',{name:title,exact:true})});const label=await card.locator('.eyebrow').innerText();assert.ok(label.length<60);if(years==='all')assert.equal(label,'Alle verfügbaren Jahrgänge · 2 Prüfungen');await card.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await saved();const s=await current();assert.deepEqual(s.sourceExams,years==='all'?'all':[years]);assert.deepEqual([...new Set(s.source_mix.map(q=>q.exam))].sort(),years==='all'?['2017-18-winter','2017-sommer']:[years]);assert.equal(new Set(s.question_ids).size,8);await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();await page.reload();await page.getByRole('heading',{name:'Sitzung pausiert'}).waitFor();assert.deepEqual((await current()).question_ids,s.question_ids);await tests();assert.equal(await filter.inputValue(),years);results.push({filter:years,module:title,sourceExams:s.sourceExams,source_mix:s.source_mix.map(q=>({exam:q.exam,question_id:q.question_id})),unique:s.question_ids.length});}
if(years==='all'){await filter.selectOption('2017-18-winter');await page.locator('.exam-card').filter({has:page.getByRole('heading',{name:'Arbeitsplanung',exact:true})}).getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await page.getByRole('button',{name:'Verwerfen und neu starten',exact:true}).click();await saved();assert.ok((await current()).source_mix.every(q=>q.exam==='2017-18-winter'));await tests();}
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await context.close();}
await fs.writeFile(dir+'/acceptance.json',JSON.stringify({url:base,checks:{url_back_forward_refresh:true,all_cross_year:true,single_year_exclusive:true,source_mix_matches_filter:true,replacement_uses_new_filter:true,paused_session_preserved:true,mobile_no_overflow:true},results},null,2));console.log('Passed: 9 real module tests, route restoration, replacement filter and source_mix checks');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
