const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5173/',dir='docs/evidence/phase2i1/release';await fs.mkdir(dir,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true}),c=await b.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage(),checks={},answers=[];try{
 for(const [slug,title,number] of [['arbeitsplanung','Arbeitsplanung','3'],['funktionsanalyse','Funktionsanalyse','7']]){
  const key=await(await p.request.get(base+'data/2018_19_winter_'+slug+'_reviewed_answers.json')).json();assert.equal(key.answers.length,28);assert.ok(key.answers.every(a=>['auto_ready','confirmed'].includes(a.official_answer_status)&&a.official_answer>=1&&a.official_answer<=5));for(const a of key.answers.filter(a=>a.confirmation_method==='manual_source_review'))answers.push({module:title,question:a.question_number,answer:a.official_answer,source_crop:a.source_crop});
  await p.goto(base+'?view=study&exam=2018-19-winter&module='+slug+'&q='+number);const answer=key.answers.find(a=>String(a.question_number)===number);await p.getByRole('radio',{name:String(answer.official_answer),exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.locator('.learning-result').filter({hasText:'Richtig'}).waitFor();await p.getByText('Offizielle Antwortquelle',{exact:true}).click();await p.getByRole('img',{name:'Offizielle Antwortquelle Q'+number,exact:true}).waitFor();await p.screenshot({path:dir+'/'+slug+'-mc.png',fullPage:true});checks[slug+'_confirmed_mc_scores']=true;
  await p.goto(base+'?view=study&exam=2018-19-winter&module='+slug+'&q=U1');await p.locator('.subparts textarea').first().fill('Isolierte Abnahme');await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.getByRole('img',{name:'Offizielle Lösung U1',exact:true}).waitFor();await p.locator('.part-assessment select').first().selectOption('richtig');await p.getByRole('button',{name:'Bewertung speichern',exact:true}).click();await p.getByRole('button',{name:'Neuer Versuch',exact:true}).waitFor();checks[slug+'_u_solution_and_assessment']=true;
  const tc=await b.newContext(),t=await tc.newPage();await t.goto(base+'?view=tests&years=2017-sommer,2018-19-winter&module='+slug);await t.locator('.exam-card').filter({has:t.getByRole('heading',{name:title,exact:true})}).getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await t.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();const exams=await t.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,q=db.transaction('testSessions').objectStore('testSessions').getAll();q.onsuccess=()=>{resolve(q.result[0].source_mix.map(s=>s.exam));db.close()}}}));assert.deepEqual([...new Set(exams)].sort(),['2017-sommer','2018-19-winter']);checks[slug+'_cross_year_test']=true;await tc.close();
 }
 await p.goto(base+'?view=study&exam=2018-19-winter&module=funktionsanalyse&q=13');await p.getByText('Gemeinsame Aufgabenbeschreibung & Anlagen',{exact:true}).click();assert.ok((await p.getByRole('link',{name:'Anlage · Seite 8 ↗',exact:true}).getAttribute('href')).includes('attachment-8-1.png'));checks.fa_q13_context=true;
 await p.goto(base+'?view=exams&exam=2018-19-winter&module=funktionsanalyse');assert.equal(await p.getByText('Noch nicht verfügbar',{exact:true}).count(),0);await p.getByRole('button',{name:'Neue Originalprüfung · Funktionsanalyse',exact:true}).click();await p.getByRole('button',{name:'Prüfungsaufgabe 13',exact:true}).click();await p.locator('.session-attachments summary').click();await p.getByRole('link',{name:'Anlage · Seite 8 ↗',exact:true}).waitFor();checks.original_fa_context=true;
 await p.goto(base+'?view=exams&exam=2018-19-winter&module=arbeitsplanung');await p.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).waitFor();await p.screenshot({path:dir+'/winter-all-modules.png',fullPage:true});checks.three_modules_available=true;
 await fs.writeFile(dir+'/acceptance.json',JSON.stringify({checks,manual_answers:answers,user_confirmations_imported:8,pdf_rescan:0,isolated_personal_test_data:true},null,2));console.log(checks);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
