const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
 const base=process.env.APP_URL||'http://127.0.0.1:5173/';const evidence=process.env.EVIDENCE_DIR||'docs/evidence/phase2e/modules';await fs.mkdir(evidence,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks={};
 const nav=n=>page.getByRole('navigation',{name:'Hauptnavigation',exact:true}).getByRole('button',{name:n,exact:true});const ready=()=>page.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();
 const current=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const id=new URL(location.href).searchParams.get('session'),r=indexedDB.open('ap2-private-learning');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction('testSessions'),q=tx.objectStore('testSessions').get(['local',id]);tx.oncomplete=()=>{resolve(q.result);db.close();};};}));
 const json=async path=>{const r=await page.request.get(new URL(path,base).href);assert.equal(r.status(),200);return r.json();};
 try{for(const [slug,title,count] of [['funktionsanalyse','Funktionsanalyse',36],['wiso','WiSo',24]]){
  const prefix='data/2017_18_winter_'+slug;const keys=await json(prefix+'_answers.json'),solutions=await json(prefix+'_u_solutions.json');const key=keys.answers.find(a=>String(a.question_number)==='1'),u=solutions.solutions.find(s=>s.question_number==='U1');assert.ok(key.official_answer);assert.ok(u);
  const route=new URL(base);route.search=new URLSearchParams({view:'study',exam:'2017-18-winter',module:slug,q:'1'});await page.goto(route.href);await page.getByRole('heading',{name:'Aufgabe 1',exact:true}).waitFor();assert.equal(await page.locator('.mc-source').count(),0);await page.getByRole('radio',{name:String(key.official_answer),exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();await page.getByText('Offizielle Antwortquelle',{exact:true}).click();await page.locator('.mc-source').evaluate(img=>img.decode());checks[slug+'_Q1_correct_source_decoded']=true;
  route.searchParams.set('q','U1');await page.goto(route.href);await page.getByRole('heading',{name:'Aufgabe U1',exact:true}).waitFor();assert.equal(await page.locator('.u-solution-image').count(),0);for(const part of u.subparts)await page.getByLabel('U1 Teil '+part.id,{exact:true}).fill('Eigener Lösungsweg');await page.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await page.locator('.u-solution-image').evaluate(img=>img.decode());for(const part of u.subparts)await page.getByLabel('U1 Bewertung '+part.id,{exact:true}).selectOption('richtig');await page.getByRole('button',{name:'Bewertung speichern',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();await page.reload();await page.locator('.result-banner.richtig').waitFor();assert.equal(new URL(page.url()).searchParams.get('exam'),'2017-18-winter');assert.equal(new URL(page.url()).searchParams.get('module'),slug);assert.equal(new URL(page.url()).searchParams.get('q'),'U1');assert.equal(await page.getByLabel('U1 Teil '+u.subparts[0].id,{exact:true}).inputValue(),'Eigener Lösungsweg');checks[slug+'_U1_selfassessment_reload']=true;await page.screenshot({path:evidence+'/'+slug+'-u1.png',fullPage:true});
  await nav('Originalprüfungen').click();const winter=page.getByRole('region',{name:'Winter 2017/18',exact:true});await winter.getByRole('button',{name:'Neue Originalprüfung · '+title,exact:true}).click();await ready();let s=await current();assert.equal(s.question_ids.length,count);assert.equal(s.exam,'2017-18-winter');assert.deepEqual(s.answers,{});assert.equal(await page.locator('.mc-source,.u-solution-image,.submitted-answer').count(),0);await page.getByRole('button',{name:'Prüfungsaufgabe U1',exact:true}).click();await page.locator('.save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();assert.equal(await page.locator('.u-solution-image,.submitted-answer').count(),0);assert.equal(await page.getByLabel('Prüfung U1 Teil '+u.subparts[0].id,{exact:true}).inputValue(),'');const originalUrl=page.url();await page.reload();await ready();assert.equal(page.url(),originalUrl);assert.equal((await current()).current_question,s.question_ids.find(id=>s.question_models[id].number==='U1'));checks[slug+'_original_count_no_leak_reload']=true;
  await nav('Tests').click();const card=page.locator('.exam-card').filter({has:page.getByRole('heading',{name:title,exact:true})});await card.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await ready();s=await current();assert.equal(s.test_type,'module');assert.equal(s.question_ids.length,8);assert.equal(new Set(s.question_ids).size,8);assert.deepEqual([...new Set(s.source_mix.map(x=>x.exam))].sort(),['2017-18-winter','2017-sommer']);assert.equal(Object.values(s.question_models).filter(q=>q.kind==='multiple_choice').length,6);assert.equal(Object.values(s.question_models).filter(q=>q.kind==='multi_part').length,2);assert.deepEqual(s.answers,{});checks[slug+'_kurz_two_seasons_unique_6_2']=true;await page.screenshot({path:evidence+'/'+slug+'-mixed-kurz.png',fullPage:true});
 }
 assert.deepEqual(errors,[]);await fs.writeFile(evidence+'/acceptance.json',JSON.stringify({url:base,checks,page_errors:errors},null,2));console.log(JSON.stringify(checks,null,2));
 }catch(error){await page.screenshot({path:evidence+'/failure.png',fullPage:true});await fs.writeFile(evidence+'/failure.txt',page.url()+'\n'+await page.locator('body').innerText());throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
