const {chromium}=require('playwright'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5173/',dir='docs/evidence/phase2i/browser';await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),checks={},mixes=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const go=async q=>{await p.goto(base+q);await p.getByRole('navigation',{name:'Hauptnavigation'}).waitFor()};
const all=()=>p.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,tx=db.transaction('testSessions'),q=tx.objectStore('testSessions').getAll();q.onsuccess=()=>resolve(q.result);tx.oncomplete=()=>db.close()}}));
const current=async()=>{const id=new URL(p.url()).searchParams.get('session');return(await all()).find(s=>s.test_id===id)};
const saved=()=>p.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();
try{
 await go('?view=exams&exam=2018-19-winter&module=wiso');await p.getByRole('button',{name:'Neue Originalprüfung · WiSo',exact:true}).waitFor();assert.equal(await p.getByText('Noch nicht verfügbar',{exact:true}).count(),2);await p.screenshot({path:dir+'/winter-modules.png',fullPage:true});checks.only_validated_module_available=true;
 const answer=(await(await p.request.get(base+'data/2018_19_winter_wiso_answers.json')).json()).answers.find(a=>a.question_number===1);
 await go('?view=study&exam=2018-19-winter&module=wiso&q=1');await p.getByRole('radio',{name:String(answer.official_answer),exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.locator('.learning-result').filter({hasText:'Richtig'}).waitFor();await p.getByText('Offizielle Antwortquelle',{exact:true}).click();await p.getByRole('img',{name:'Offizielle Antwortquelle Q1',exact:true}).waitFor();await p.screenshot({path:dir+'/wiso-q1.png',fullPage:true});checks.mc_scored_from_official_source=true;
 await go('?view=study&exam=2018-19-winter&module=wiso&q=U2');await p.locator('.subparts textarea').first().fill('Synthetic acceptance response');await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.getByRole('img',{name:'Offizielle Lösung U2',exact:true}).waitFor();for(const s of await p.locator('.part-assessment select').all())await s.selectOption('teilweise');await p.getByRole('button',{name:'Bewertung speichern',exact:true}).click();await p.getByRole('button',{name:'Neuer Versuch',exact:true}).waitFor();await p.reload();await p.getByRole('button',{name:'Neuer Versuch',exact:true}).waitFor();await p.screenshot({path:dir+'/wiso-u2.png',fullPage:true});checks.u_source_self_assessment_persists=true;
 await go('?view=exams&exam=2018-19-winter&module=wiso');await p.getByRole('button',{name:'Neue Originalprüfung · WiSo',exact:true}).click();await saved();let s=await current();assert.equal(s.question_ids.length,24);assert.deepEqual(s.source_mix.map(q=>q.question_number),[...Array.from({length:18},(_,i)=>String(i+1)),...Array.from({length:6},(_,i)=>'U'+(i+1))]);await p.getByRole('radio',{name:String(answer.official_answer),exact:true}).check();await saved();await p.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();const paused=await current();await p.reload();await p.getByRole('heading',{name:'Sitzung pausiert'}).waitFor();assert.deepEqual(await current(),paused);await p.getByRole('button',{name:'Sitzung fortsetzen',exact:true}).click();await saved();await p.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await p.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await saved();assert.equal((await current()).result.richtig,1);checks.original_exam_order_resume_score=true;
 const preserved=await all();
 for(const years of ['all','2018-19-winter','2018-sommer','2017-sommer,2018-19-winter']){
  const c=await browser.newContext(),page=await c.newPage();await page.goto(base+'?view=tests&years='+years+'&exam=2018-19-winter&module=wiso');const card=page.locator('.exam-card').filter({has:page.getByRole('heading',{name:'WiSo',exact:true})});await card.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await page.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();const session=await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,q=db.transaction('testSessions').objectStore('testSessions').getAll();q.onsuccess=()=>{resolve(q.result[0]);db.close()}}}));const expected=years==='all'?['2017-18-winter','2017-sommer','2018-19-winter','2018-sommer']:years.split(',').sort();assert.deepEqual([...new Set(session.source_mix.map(q=>q.exam))].sort(),expected);assert.equal(new Set(session.question_ids).size,8);mixes.push({filter:years,source_mix:session.source_mix.map(q=>({exam:q.exam,question_id:q.question_id}))});await page.reload();await page.locator('.exam-workspace').waitFor();await page.screenshot({path:dir+'/test-'+years.replaceAll(',','_')+'.png',fullPage:true});await c.close();
 }
 assert.deepEqual(await all(),preserved);checks.all_single_multi_year_filters=true;checks.existing_session_unchanged=true;
 await go('?view=settings');assert.equal(await p.getByRole('button',{name:'Mit Google anmelden',exact:true}).isDisabled(),true);checks.firebase_not_configured=true;
 await go('?view=tests&years=2018-19-winter&module=wiso');await p.setViewportSize({width:390,height:844});await p.getByRole('button',{name:'Alle auswählen',exact:true}).waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.mobile_no_overflow=true;assert.deepEqual(errors,[]);await fs.writeFile(dir+'/acceptance.json',JSON.stringify({url:base,checks,mixes,isolated_browser:true,synthetic_records_only:true,errors},null,2));console.log(checks);
}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
