const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir=process.env.EVIDENCE_DIR||'docs/evidence/bank-summary/browser';fs.mkdirSync(dir,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage({viewport:{width:1440,height:1000}});try{
const goto=async q=>p.goto(base+q);
await goto('?view=study&exam=2024-sommer&module=funktionsanalyse&q=25');await p.getByRole('heading',{name:/Aufgabe 25/}).waitFor();assert.equal(await p.locator('.external-attachments').count(),0);assert.match(await p.locator('.reader-head .source-links a').first().getAttribute('href'),/\.pdf#page=/);
await goto('?view=study&exam=2024-sommer&module=funktionsanalyse&q=U3');await p.locator('.external-attachments').first().waitFor();await p.locator('.external-attachments summary').first().click();await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.locator('.u-solution-image').waitFor();await p.screenshot({path:dir+'/sommer2024-fa-u3.png',fullPage:true});
await goto('?view=answer-review&scope=winter-2024-25-fa-mapping-v2');await p.getByRole('heading',{name:/Funktionsanalyse.*Q1/}).waitFor();await p.getByRole('radio',{name:'1',exact:true}).waitFor({state:'visible'});await p.waitForFunction(()=>{const el=document.querySelector('input[type=radio]');return el&&!el.disabled&&!el.closest('fieldset')?.disabled});assert.equal(await p.locator('input[type=radio]:checked').count(),0);await p.screenshot({path:dir+'/winter-fa-answer-review.png',fullPage:true});
const queue=await(await p.request.get(base+'data/overnight_review_queue.json')).json();assert.equal(queue.items.filter(i=>i.type==='official_answer').length,17);assert.equal(queue.items.filter(i=>i.type==='attachment_mapping').length,0);
fs.writeFileSync(dir+'/review-checks.json',JSON.stringify({summer_fa_question25_no_attachment:true,summer_fa_u3_attachment_and_solution:true,winter_fa_review_crop_verified:true,no_candidate_preselected:true,answered_mapping_requests_removed:true,new_answer_review:17,isolated_browser:true},null,2));console.log('Review integration browser checks passed');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
