const {chromium}=require('playwright'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5173/',dir=process.env.EVIDENCE_DIR||'docs/evidence/phase2g/after';await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),checks={},measurements=[],errors=[];
const context=()=>browser.newContext({viewport:{width:1440,height:1000}});
const go=async(p,q)=>{await p.goto(base+q);await p.getByRole('navigation',{name:'Hauptnavigation'}).waitFor();};
const saved=p=>p.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();
const all=p=>p.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,t=db.transaction('testSessions'),q=t.objectStore('testSessions').getAll();t.oncomplete=()=>{resolve(q.result);db.close();};};}));
const current=async p=>(await all(p)).find(s=>s.test_id===new URL(p.url()).searchParams.get('session'));
const card=(p,title)=>p.locator('.exam-card').filter({has:p.getByRole('heading',{name:title,exact:true})});
try{
 {const c=await context(),p=await c.newPage();let release;const gate=new Promise(r=>release=r);await p.route('**/data/2017_18_winter_arbeitsplanung_segmented.json',async route=>{await gate;await route.continue();});await go(p,'?view=tests&years=2017-sommer,2017-18-winter&module=arbeitsplanung');const start=card(p,'Arbeitsplanung').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true});await start.waitFor();assert.equal(await start.isDisabled(),true);release();await start.click();await saved(p);checks.selected_sources_must_finish_loading=true;await c.close();}
 for(const mode of ['study','original','module']){const c=await context(),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));
  if(mode==='study')await go(p,'?view=study&exam=2017-sommer&module=arbeitsplanung&q=1');
  else if(mode==='original'){await go(p,'?view=exams&exam=2017-sommer&module=arbeitsplanung');await p.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).click();await saved(p);}
  else{await go(p,'?view=tests&years=2017-sommer&module=arbeitsplanung');await card(p,'Arbeitsplanung').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await saved(p);await p.getByRole('button',{name:/^Prüfungsaufgabe \d+$/}).first().click();await saved(p);}
  for(const width of [320,360,390]){await p.setViewportSize({width,height:844});await p.getByRole('radio',{name:'1',exact:true}).waitFor();await p.locator('.choice-options').scrollIntoViewIfNeeded();const m=await p.evaluate(()=>{const field=document.querySelector('.choice-options').getBoundingClientRect();return {viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,field:{left:field.left,right:field.right},options:[...document.querySelectorAll('.choice-options label')].map(e=>{const r=e.getBoundingClientRect(),radio=e.querySelector('input').getBoundingClientRect();return {left:r.left,right:r.right,height:r.height,radioWidth:radio.width};})};});assert.ok(m.scrollWidth<=width,JSON.stringify(m));assert.equal(m.options.length,5);assert.ok(m.options.every(x=>x.left>=m.field.left-.5&&x.right<=m.field.right+.5&&x.height>=44&&x.radioWidth>=18));measurements.push({mode,...m});await p.screenshot({path:dir+'/'+mode+'-'+width+'.png'});}
  await c.close();
 }
 checks.mobile_nine_scenarios_no_overflow=true;
 const c=await context(),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));
 await go(p,'?view=exams&exam=2018-sommer&module=wiso');await p.getByRole('button',{name:/Archivierte \/ verworfene Versuche anzeigen/}).click();await p.screenshot({path:dir+'/original-spacing.png',fullPage:true});const gap=await p.evaluate(()=>document.querySelector('.test-history').getBoundingClientRect().top-document.querySelector('.module-cards').getBoundingClientRect().bottom);assert.ok(gap>=24);checks.section_gap=gap;
 await p.getByRole('button',{name:'Neue Originalprüfung · WiSo',exact:true}).click();await saved(p);const template=await current(p);
 const fixtures=Array.from({length:120},(_,i)=>{const s=structuredClone(template);s.test_id='fixture-'+i;s.exam_session_id=s.test_id;s.test_type=i%2?'module':'original';s.exam=i%3?'2017-sommer':'2017-18-winter';s.source_mix=s.source_mix.map(q=>({...q,exam:s.exam}));s.started_at=new Date(Date.UTC(2026,0,1,0,i)).toISOString();s.status=['active','paused','completed','abandoned','discarded'][i%5];s.active_since=null;s.revision=0;if(s.status==='discarded'){s.previous_status='completed';s.discarded_from='completed';s.discarded_at=s.started_at;}return s;});
 await p.evaluate(rows=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,t=db.transaction('testSessions','readwrite'),s=t.objectStore('testSessions');s.clear();for(const row of rows)s.put(row);t.oncomplete=()=>{db.close();resolve();};t.onerror=()=>reject(t.error);};}),fixtures);
 await go(p,'?view=history');const normal=p.getByRole('region',{name:'Normale Versuche'});await normal.locator('article').first().waitFor();assert.equal(await normal.locator('article').count(),20);assert.equal(await p.getByRole('region',{name:'Archivierte Versuche'}).count(),0);await p.getByRole('button',{name:'Mehr anzeigen',exact:true}).click();assert.equal(await normal.locator('article').count(),40);await p.screenshot({path:dir+'/history-pagination.png',fullPage:true});checks.history_120_initial20_then40=true;
 await p.getByRole('combobox',{name:'Verlauf Typ'}).selectOption('module');await p.getByRole('combobox',{name:'Verlauf Jahrgang'}).selectOption('2017-18-winter');await p.getByRole('combobox',{name:'Verlauf Status'}).selectOption('completed');const ids=await normal.locator('article').evaluateAll(es=>es.map(e=>e.dataset.testId));assert.ok(ids.length);assert.ok(ids.every(id=>{const s=fixtures.find(s=>s.test_id===id);return s.test_type==='module'&&s.exam==='2017-18-winter'&&s.status==='completed';}));await p.screenshot({path:dir+'/history-filters.png',fullPage:true});checks.history_filters=true;
 await p.getByRole('combobox',{name:'Verlauf Typ'}).selectOption('all');await p.getByRole('combobox',{name:'Verlauf Jahrgang'}).selectOption('all');await p.getByRole('combobox',{name:'Verlauf Status'}).selectOption('archived');const archive=p.getByRole('region',{name:'Archivierte Versuche'});assert.equal(await archive.locator('article').count(),20);const restore=archive.locator('article').filter({has:p.getByRole('button',{name:'Wiederherstellen',exact:true})}).first(),restoreId=await restore.getAttribute('data-test-id');await restore.getByRole('button',{name:'Wiederherstellen',exact:true}).click();await p.getByRole('button',{name:'Wiederherstellen bestätigen',exact:true}).click();await p.getByRole('alertdialog').waitFor({state:'hidden'});let restored=(await all(p)).find(s=>s.test_id===restoreId);assert.equal(restored.status,'completed');assert.equal(restored.discarded_at,undefined);checks.restore_uses_previous_completed_status=true;
 await p.getByRole('combobox',{name:'Verlauf Status'}).selectOption('completed');const row=p.locator('article[data-test-id="'+restoreId+'"]');await row.waitFor();const tops=await row.locator('.record-actions>button,.record-actions .session-actions>button').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().top));assert.ok(tops.length>=3);assert.ok(Math.max(...tops)-Math.min(...tops)<3);await p.screenshot({path:dir+'/restored-actions.png',fullPage:true});checks.desktop_actions_one_row=true;
 await row.getByRole('button',{name:'Versuch verwerfen',exact:true}).click();await p.getByRole('button',{name:'Verwerfen bestätigen',exact:true}).click();await p.getByRole('alertdialog').waitFor({state:'hidden'});assert.equal((await all(p)).find(s=>s.test_id===restoreId).status,'discarded');await p.getByRole('combobox',{name:'Verlauf Status'}).selectOption('archived');await p.locator('article[data-test-id="'+restoreId+'"]').getByRole('button',{name:'Versuch löschen',exact:true}).click();await p.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await p.getByRole('alertdialog').waitFor({state:'hidden'});assert.equal((await all(p)).some(s=>s.test_id===restoreId),false);assert.equal((await all(p)).length,119);checks.discard_and_permanent_delete=true;
 await go(p,'?view=start');await p.getByRole('heading',{name:'Weiterlernen',exact:true}).waitFor();assert.ok(await p.locator('.session-history article').count()<=5);await p.screenshot({path:dir+'/dashboard-bounded.png',fullPage:true});checks.dashboard_max5=true;await c.close();
 const mixResults=[];
 for(const years of ['all','2018-sommer','2017-sommer,2017-18-winter']){const c=await context(),p=await c.newPage();await go(p,'?view=tests&years='+years+'&module=wiso');await p.getByRole('button',{name:'Auswahl löschen',exact:true}).click();await p.getByText('Mindestens einen Prüfungsjahrgang auswählen.',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).count(),0);await p.goBack();await p.getByRole('button',{name:'Alle auswählen',exact:true}).waitFor();await p.reload();assert.equal(new URL(p.url()).searchParams.get('years'),years);await card(p,'WiSo').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await saved(p);const s=await current(p);assert.deepEqual([...new Set(s.source_mix.map(q=>q.exam))].sort(),years==='all'?['2017-18-winter','2017-sommer','2018-sommer']:years.split(',').sort());await p.getByRole('button',{name:'Pausieren',exact:true}).click();await saved(p);const paused=await current(p);await p.getByRole('navigation',{name:'Hauptnavigation'}).getByRole('button',{name:'Tests',exact:true}).click();await p.getByRole('button',{name:'Alle auswählen',exact:true}).click();await p.getByRole('checkbox',{name:'Sommer 2018',exact:true}).uncheck();await p.goBack();await p.goForward();await p.reload();assert.deepEqual(new URL(p.url()).searchParams.get('years').split(',').sort(),['2017-18-winter','2017-sommer']);assert.deepEqual((await all(p)).find(t=>t.test_id===s.test_id),paused);await p.screenshot({path:dir+'/multi-year-'+years.replaceAll(',','_')+'.png',fullPage:true});mixResults.push({filter:years,sourceMix:[...new Set(s.source_mix.map(q=>q.exam))],oldSessionUnchanged:true});await c.close();}
 checks.all_single_multi_source_mix=true;checks.empty_selection_blocks=true;checks.url_back_forward_refresh=true;checks.old_sessions_immutable=true;
 const finalContext=await context(),settings=await finalContext.newPage();await go(settings,'?view=settings');await settings.getByRole('button',{name:'Mit Google anmelden',exact:true}).waitFor();assert.equal(await settings.getByRole('button',{name:'Mit Google anmelden',exact:true}).isDisabled(),true);await settings.screenshot({path:dir+'/firebase-not-configured.png',fullPage:true});checks.firebase_explicit_not_configured=true;
 await go(settings,'?view=study&exam=2017-sommer&module=arbeitsplanung&q=1');await settings.getByRole('radio',{name:'1',exact:true}).check();await settings.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await settings.getByText('Antwort und Ergebnis gespeichert',{exact:true}).waitFor();await settings.getByRole('button',{name:'Synchronisierung & Backup',exact:true}).click();
 const downloadPromise=settings.waitForEvent('download');await settings.getByRole('button',{name:'Lernfortschritt exportieren',exact:true}).click();const download=await downloadPromise,stream=await download.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);const backup=Buffer.concat(chunks),data=JSON.parse(backup);for(const key of ['records','reviews','answerReviews','attempts','learningSessions','testSessions','settings'])assert.ok(Array.isArray(data[key]));assert.equal(data.attempts.length,1);
 const importContext=await context(),importPage=await importContext.newPage();await go(importPage,'?view=settings');await importPage.getByLabel('Lernfortschritt importieren',{exact:false}).setInputFiles({name:'synthetic-backup.json',mimeType:'application/json',buffer:backup});await importPage.getByRole('button',{name:'Import bestätigen',exact:true}).click();await importPage.getByRole('status').filter({hasText:'Nur im lokalen Profil importiert'}).waitFor();await importPage.reload();await go(importPage,'?view=study&exam=2017-sommer&module=arbeitsplanung&q=1');await importPage.getByRole('button',{name:'Neuer Versuch',exact:true}).waitFor();const imported=await importPage.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,t=db.transaction('attempts'),q=t.objectStore('attempts').getAll();t.oncomplete=()=>{resolve(q.result);db.close();};};}));assert.deepEqual(imported,data.attempts);checks.backup_ui_roundtrip_keeps_attempt_id_and_source=true;await importPage.screenshot({path:dir+'/backup-restored.png',fullPage:true});await importContext.close();await finalContext.close();assert.deepEqual(errors,[]);
 await fs.writeFile(dir+'/acceptance.json',JSON.stringify({url:base,checks,mobile:measurements,moduleTests:mixResults,real_cloud_tested:false,isolated_browser:true},null,2));console.log('Passed Phase2G UX acceptance',checks);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
