const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir='docs/evidence/phase3b/browser';fs.mkdirSync(dir,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));
const go=async(s)=>{await p.goto(base+s);};const shot=async(name)=>p.screenshot({path:dir+'/'+name+'.png',fullPage:false});
const read=async(store)=>p.evaluate(store=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,t=db.transaction(store),q=t.objectStore(store).getAll();t.oncomplete=()=>{resolve(q.result);db.close()};t.onerror=()=>reject(t.error)};r.onerror=()=>reject(r.error)}),store);
const stage=async(n,count)=>{await p.locator(`[data-stage="${n}"] .stage-count`).filter({hasText:new RegExp('^'+count+'$')}).waitFor();};
const ready=async()=>{await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).waitFor();};
const choice=async(n)=>{await ready();const reset=p.getByRole('button',{name:'Aufgabe erneut versuchen',exact:true});if(await reset.count()){await reset.click();await p.waitForFunction(()=>!document.querySelector('.choice-options input:checked')&&!document.querySelector('.choice-options')?.disabled);}await p.getByRole('radio',{name:String(n),exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.locator('.result-banner').waitFor();};
try{
 const inventory=await(await p.request.get(base+'data/question_inventory.json')).json(),q=inventory.find(q=>q.examId==='2017-sommer'&&q.module==='arbeitsplanung'&&q.number==='1'),key=await(await p.request.get(base+'data/2017_sommer_arbeitsplanung_answers.json')).json(),answer=key.answers.find(a=>a.question_id===q.question_id).official_answer,wrong=answer===1?2:1;
 await go('?view=bank');await p.getByTestId('bank-count').filter({hasText:'1332 Aufgaben gefunden'}).waitFor();assert.equal(await p.locator('.bank-question,.bank-results,.question-art').count(),0);assert.equal(await p.locator('.bank-filters select').count(),4);assert.equal(await p.getByLabel('Format',{exact:true}).count(),0);await shot('after-bank');checks.push('Landing: four dynamic filters, 1332 incl unknown, no question cards/list, compact statistics');
 await p.getByLabel('Modul',{exact:true}).selectOption('arbeitsplanung');await p.getByLabel('Jahrgang',{exact:true}).selectOption('2017-sommer');await p.getByTestId('bank-count').filter({hasText:'36 Aufgaben gefunden'}).waitFor();const modulesBefore=await read('moduleProgress');await p.getByRole('button',{name:'Training starten',exact:true}).click();await ready();const firstURL=p.url(),firstRun=new URL(firstURL).searchParams.get('run');assert.ok(firstRun);await p.getByTestId('training-progress').filter({hasText:'0 / 36'}).waitFor();const current=(await read('trainingRuns')).find(r=>r.run_id===firstRun),currentQ=current.snapshots[current.current_question],currentAnswer=currentQ.answer.official_answer;assert.equal(currentQ.config.examId,'2017-sommer');
 await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.getByRole('heading',{name:'Offizielle Lösung',exact:true}).waitFor();assert.equal((await read('attempts')).length,0);assert.match(await p.getByTestId('training-progress').innerText(),/^0/);assert.deepEqual(await read('moduleProgress'),modulesBefore);checks.push('Training reveal creates no attempt and no ModuleProgress completion');
 await p.getByLabel('Lernnotiz',{exact:true}).fill('Phase 3B dauerhafte Notiz');await p.getByRole('button',{name:'Notiz speichern',exact:true}).click();await p.getByText('Gespeichert',{exact:true}).waitFor();await choice(currentAnswer);await p.getByTestId('training-progress').filter({hasText:'1 / 36'}).waitFor();assert.deepEqual(await read('moduleProgress'),modulesBefore);const a=(await read('attempts'))[0];assert.equal(a.training_run_id,firstRun);assert.equal(a.progress_run_id,undefined);
 await p.getByRole('button',{name:'Nächste Aufgabe →',exact:true}).click();await ready();await p.getByRole('radio',{name:'3',exact:true}).check();await p.getByText('Entwurf gespeichert',{exact:true}).waitFor();await p.reload();await ready();assert.equal(await p.getByRole('radio',{name:'3',exact:true}).isChecked(),true);const frozen=(await read('trainingRuns')).find(r=>r.run_id===firstRun);assert.equal(frozen.current_question,frozen.question_ids[1]);assert.deepEqual(await read('moduleProgress'),modulesBefore);await shot('training-persistence');
 await go('?view=bank');await p.getByLabel('Modul',{exact:true}).selectOption('arbeitsplanung');await p.getByLabel('Jahrgang',{exact:true}).selectOption('2017-sommer');await p.getByRole('button',{name:'Training fortsetzen',exact:true}).click();await ready();assert.equal(new URL(p.url()).searchParams.get('run'),firstRun);await p.goBack();await p.getByRole('heading',{name:'Aufgabenbank',exact:true}).waitFor();await p.goForward();await ready();assert.equal(await p.getByRole('radio',{name:'3',exact:true}).isChecked(),true);checks.push('Stable filter resumes same run; drafts/current question survive refresh/back/forward; ModuleProgress untouched');
 const oldAttempts=await read('attempts'),oldNotes=await read('questionNotes');await p.getByRole('button',{name:'Training neu starten',exact:true}).click();await p.getByRole('button',{name:'Neue Runde starten',exact:true}).click();await ready();assert.notEqual(new URL(p.url()).searchParams.get('run'),firstRun);await p.getByTestId('training-progress').filter({hasText:'0 / 36'}).waitFor();assert.deepEqual(await read('attempts'),oldAttempts);assert.deepEqual(await read('questionNotes'),oldNotes);assert.equal((await read('trainingRuns')).length,2);await shot('training-restart-note');checks.push('Restart creates new run only; previous run, attempts, notes retained');
 const editor=p.locator('.classification-editor');assert.equal(await editor.getAttribute('open'),null);assert.ok(await p.locator('.question-note').first().evaluate((e)=>!!e.nextElementSibling?.classList.contains('classification-editor')));await editor.locator('summary').first().click();await p.getByLabel('Primärer Aufgabentyp',{exact:true}).selectOption('diagram');await p.getByRole('button',{name:'Klassifikation speichern',exact:true}).click();await p.getByText('Gespeichert · menschlich bestätigt · gesperrt',{exact:true}).waitFor();await shot('classification-edit');await p.reload();await ready();await editor.locator('summary').first().click();await p.getByText('Menschlich bestätigt · gesperrt',{exact:true}).waitFor();assert.equal(await p.getByLabel('Primärer Aufgabentyp',{exact:true}).inputValue(),'diagram');checks.push('Inline classification below note, default collapsed, editable dynamic taxonomy, locked save persists');
 const study='?view=study&exam=2017-sommer&module=arbeitsplanung&q=';
 await go(study+'1');await choice(wrong);await go('?view=wrong');await stage(1,1);await shot('after-wrong-stage1');
 for(const [from,to] of [[1,2],[2,3],[3,'mastered']]){await p.locator(`[data-stage="${from}"]`).getByRole('button',{name:'Jetzt üben',exact:true}).click();await ready();const runURL=p.url(),run=(await read('trainingRuns')).find(r=>r.run_id===new URL(runURL).searchParams.get('run'));assert.equal(run.question_ids.length,1);await choice(answer);await p.reload();await ready();assert.equal(new URL(p.url()).searchParams.get('run'),run.run_id);assert.deepEqual((await read('trainingRuns')).find(r=>r.run_id===run.run_id).question_ids,run.question_ids);await go('?view=wrong');await stage(to,1);await stage(from,0);}
 await shot('wrong-mastered');await go(study+'1');await choice(wrong);await go('?view=wrong');await stage(1,1);await stage('mastered',0);await p.locator('[data-stage="1"]').getByRole('button',{name:'Jetzt üben',exact:true}).click();await ready();const beforeRemove=await read('attempts');await p.getByRole('button',{name:'Aus Fehlertraining entfernen',exact:true}).click();await p.getByRole('button',{name:'Aus Fehlertraining entfernt',exact:true}).waitFor();await go('?view=wrong');await stage(1,0);assert.deepEqual(await read('attempts'),beforeRemove);await go(study+'1');await choice(wrong);await go('?view=wrong');await stage(1,1);checks.push('Wrong1 → correct2 → correct3 → mastered; mastered stays; wrong resets1; dismiss preserves history; new wrong reactivates1; stage membership frozen');
 await go(study+'U1');await ready();await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.getByRole('heading',{name:'Offizielle Lösung · U1',exact:true}).waitFor();assert.equal(await p.locator('.part-assessment').count(),0);await p.locator('.subparts textarea,.subparts input').first().fill('Teilantwort');await p.getByText('Entwurf gespeichert',{exact:true}).waitFor();const assessments=p.locator('.part-assessment select');for(let i=0;i<await assessments.count();i++)await assessments.nth(i).selectOption('teilweise');await p.getByRole('button',{name:'Bewertung speichern',exact:true}).click();await p.locator('.result-banner.teilweise').waitFor();await go('?view=wrong');await stage(1,2);checks.push('Empty U solution no assessment; partial formal U enters stage1');
 await go('?view=tests&years=all&module=arbeitsplanung');const toggle=p.getByRole('button',{name:/^Jahrgänge:/});await toggle.click();await p.getByRole('button',{name:'Auswahl löschen',exact:true}).click();await p.locator('.source-year-scroll').getByLabel('Winter 2021/22',{exact:true}).check();await p.locator('.source-year-scroll').getByLabel('Sommer 2021',{exact:true}).check();await p.keyboard.press('Escape');await p.reload();await p.getByRole('button',{name:'Jahrgänge: 2 Jahrgänge ausgewählt ▾',exact:true}).waitFor();await shot('year-selector-unchanged');checks.push('Existing compact Modultest multi-year selector preserved');
 await p.setViewportSize({width:390,height:844});await go('?view=bank');await p.getByTestId('bank-count').waitFor();await shot('bank-mobile');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await go('?view=wrong');await stage(1,2);await shot('wrong-mobile');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await go('?view=training&run='+firstRun);await ready();await shot('training-mobile');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('Desktop/mobile no horizontal overflow');
 assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/checks.json',JSON.stringify({checks,isolated_browser:true,real_user_data_touched:false,errors,run_id:firstRun,run_count:(await read('trainingRuns')).length},null,2));console.log(checks);
}catch(e){await shot('failure');throw e}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
