const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir=process.env.EVIDENCE_DIR||'docs/evidence/expansion2026/browser';fs.mkdirSync(dir,{recursive:true});const server=process.env.APP_URL?null:require('child_process').spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','5174','--strictPort'],{stdio:'ignore',windowsHide:true});if(server)await new Promise(r=>setTimeout(r,1500));const b=await chromium.launch({channel:'chrome',headless:true}),c=await b.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage(),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));try{
 for(const [scope,n] of [['winter-2025-26',47],['sommer-2026',45]]){
  await p.goto(base+'?view=answer-review&scope='+scope,{waitUntil:'domcontentloaded',timeout:90000});const nav=p.getByRole('navigation',{name:'Antwort-Review Aufgaben'});await nav.waitFor();assert.equal(await nav.getByRole('button').count(),n);await p.locator('.manual-crop img').waitFor();await p.getByRole('radio',{name:'1',exact:true}).waitFor();await p.waitForFunction(()=>!document.querySelector('.manual-options input')?.disabled);assert.equal(await p.locator('input:checked').count(),0);assert.equal(await p.getByRole('button',{name:'Speichern',exact:true}).isDisabled(),true);await p.locator('#review-question').scrollIntoViewIfNeeded();await p.screenshot({path:dir+'/'+scope+'-review.png'});
  await p.getByRole('button',{name:'Next →',exact:true}).click();const url=p.url();await p.locator('.manual-crop img').waitFor();await p.reload();await p.locator('.manual-crop img').waitFor();assert.equal(p.url(),url);assert.equal(await p.locator('input:checked').count(),0);checks.push({scope,items:n,source_hash_verification:true,no_candidate_preselected:true,refresh_item_preserved:true});
 }
 await p.setViewportSize({width:390,height:844});await p.locator('#review-question').scrollIntoViewIfNeeded();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:dir+'/review-mobile.png'});
 await p.goto(base+'?view=bank');await p.getByTestId('bank-count').filter({hasText:'1368 Aufgaben gefunden'}).waitFor();checks.push('Production bank remains1368; no unconfirmed new questions admitted');
 await p.goto(base+'?view=study&exam=2017-sommer&module=arbeitsplanung&q=1');await p.getByRole('checkbox',{name:'Diese Aufgabe ist mir unsicher',exact:true}).waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);assert.equal(await p.getByRole('checkbox',{name:'Diese Aufgabe ist mir unsicher',exact:true}).isChecked(),false);checks.push('Existing study/uncertainty UI intact; isolated new browser starts clean');assert.deepEqual(errors,[]);
 fs.writeFileSync(dir+'/checks.json',JSON.stringify({checks,errors,actual_manual_confirmations:0,isolated_browser:true,real_personal_data_touched:false},null,2));console.log(checks);
 }finally{await b.close();server?.kill()}})().catch(e=>{console.error(e);process.exit(1)});
