const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir='docs/evidence/phase3a/browser';const browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}});const checks=[];
const read=store=>p.evaluate(store=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,t=db.transaction(store),q=t.objectStore(store).getAll();t.oncomplete=()=>{resolve(q.result);db.close()};t.onerror=()=>reject(t.error)};r.onerror=()=>reject(r.error)}),store);
const wrongCount=async(n)=>{await p.goto(base+'?view=wrong');await p.locator('[data-testid=bank-count]').filter({hasText:new RegExp('^'+n+' Aufgaben gefunden$')}).waitFor()};
try{for(const type of ['original','module']){await p.goto(base+(type==='original'?'?view=exams&exam=2017-sommer&module=arbeitsplanung':'?view=tests&years=2017-sommer&module=arbeitsplanung'));if(type==='original')await p.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).click();else await p.locator('.exam-card[data-module=arbeitsplanung]').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await p.locator('.exam-workspace').waitFor();const url=p.url(),session=(await read('testSessions')).find(s=>s.status==='active'),qid=session.question_ids.find(id=>session.question_models[id].kind==='multiple_choice'),number=session.question_models[qid].number;await p.getByRole('button',{name:type==='original'?'Prüfungsaufgabe '+number:new RegExp('^Prüfungsaufgabe '+number+'(?: ·|$)') ,exact:type==='original'}).click();const correct=session.official_answers[qid];await p.getByRole('radio',{name:String(correct===1?2:1),exact:true}).check();await p.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await p.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await p.locator('.session-results').waitFor();await wrongCount(1);
await p.goto(url);await p.getByRole('button',{name:'Versuch verwerfen',exact:true}).click();await p.getByRole('button',{name:'Verwerfen bestätigen',exact:true}).click();await p.getByRole('button',{name:'Wiederherstellen',exact:true}).waitFor();await wrongCount(0);await p.goto(url);await p.getByRole('button',{name:'Wiederherstellen',exact:true}).click();await p.getByRole('button',{name:'Wiederherstellen bestätigen',exact:true}).click();await p.locator('.session-results').waitFor();await wrongCount(1);
await p.goto(url);await p.getByRole('button',{name:'Versuch löschen',exact:true}).click();await p.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await wrongCount(0);assert.ok(!(await read('testSessions')).some(s=>s.test_id===session.test_id));assert.equal((await read('attempts')).length,0);checks.push(type+': formal MC result enters, discard removes, restore restores once, permanent delete removes wrong contribution');}
await p.screenshot({path:dir+'/invalid-tests-excluded.png'});fs.writeFileSync(dir+'/test-lifecycle.json',JSON.stringify({checks,isolated_browser:true},null,2));console.log(checks);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
