const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
 const base=process.env.APP_URL||'http://127.0.0.1:5173/';const evidence=process.env.EVIDENCE_DIR||'docs/evidence/phase2e/navigation';await fs.mkdir(evidence,{recursive:true});
 const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks={};
 const nav=name=>page.getByRole('navigation',{name:'Hauptnavigation',exact:true}).getByRole('button',{name,exact:true});
 const snapshot=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,names=['attempts','learningSessions','reviews','answerReviews','testSessions'],tx=db.transaction(names,'readonly'),requests=Object.fromEntries(names.map(n=>[n,tx.objectStore(n).getAll()]));tx.oncomplete=()=>{resolve(Object.fromEntries(names.map(n=>[n,requests[n].result])));db.close();};};}));
 const current=async()=>{const id=new URL(page.url()).searchParams.get('session');return(await snapshot()).testSessions.find(s=>s.test_id===id);};const saved=()=>page.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();
 try{
  await page.goto(base+'?view=study&q=1');await page.getByRole('heading',{name:'Aufgabe 1',exact:true}).waitFor();await page.getByRole('radio',{name:'4',exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();const before=await snapshot();
  for(const module of ['funktionsanalyse','wiso']){await page.getByLabel('Lernmodul',{exact:true}).selectOption('2017-sommer/'+module);await page.waitForURL(u=>u.searchParams.get('module')===module);await page.getByRole('heading',{name:'Aufgabe 1',exact:true}).waitFor();await page.locator('.question-art img').evaluate(i=>i.decode());const keys=await(await page.request.get(new URL('data/2017_sommer_'+module+'_answers.json',base).href)).json();await page.getByRole('radio',{name:String(keys.answers.find(a=>a.question_number===1).official_answer),exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();}checks.summer_three_modules_work=true;
  await nav('Originalprüfungen').click();const summer=page.getByRole('region',{name:'Sommer 2017',exact:true}),winter=page.getByRole('region',{name:'Winter 2017/18',exact:true});assert.equal(await summer.locator('.exam-card').count(),3);assert.equal(await winter.locator('.exam-card').count(),3);
  await winter.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).click();await saved();let original=await current();assert.equal(original.exam,'2017-18-winter');assert.equal(original.question_ids.length,36);assert.equal(original.status,'active');assert.deepEqual(original.answers,{});await page.getByRole('radio',{name:'2',exact:true}).check();await saved();assert.equal(await page.locator('.submitted-answer').count(),0);await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();await page.reload();await page.getByRole('heading',{name:'Sitzung pausiert',exact:true}).waitFor();assert.equal((await current()).test_id,original.test_id);await page.getByRole('button',{name:'Sitzung fortsetzen',exact:true}).click();await saved();checks.winter_original_36_resume=true;
  await nav('Lernen').click();await page.getByRole('region',{name:'Winter 2017/18',exact:true}).locator('.exam-card').filter({has:page.getByRole('heading',{name:'Arbeitsplanung',exact:true})}).getByRole('button',{name:/Teil A/}).click();await page.waitForURL(u=>u.searchParams.get('exam')==='2017-18-winter'&&u.searchParams.get('view')==='study');await page.reload();await page.getByRole('heading',{name:'Aufgabe 1',exact:true}).waitFor();assert.equal(new URL(page.url()).searchParams.get('exam'),'2017-18-winter');const answer=await(await page.request.get(new URL('data/2017_18_winter_arbeitsplanung_answers.json',base).href)).json();await page.getByRole('radio',{name:String(answer.answers.find(a=>a.question_number===1).official_answer),exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();await page.getByText('Offizielle Antwortquelle',{exact:true}).click();await page.locator('.mc-source').evaluate(i=>i.decode());checks.winter_study_choice_and_source=true;
  await page.getByRole('button',{name:'Teil B · 8 Aufgaben',exact:true}).click();await page.getByRole('button',{name:'Aufgabe U5',exact:true}).click();await page.locator('.question-art img').evaluate(i=>i.decode());const fields=page.locator('.practice .subparts textarea');await fields.first().fill('Mein Lösungsweg');await page.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await page.locator('.u-solution-image').evaluate(i=>i.decode());for(const select of await page.locator('.practice .part-assessment select').all())await select.selectOption('teilweise');await page.getByRole('button',{name:'Bewertung speichern',exact:true}).click();await page.locator('.result-banner.teilweise').waitFor();await page.screenshot({path:evidence+'/winter-u5.png',fullPage:true});checks.winter_U5_source_and_self_assessment=true;
  await nav('Tests').click();const card=page.locator('.exam-card').filter({has:page.getByRole('heading',{name:'Arbeitsplanung',exact:true})});await card.getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await saved();const test=await current();assert.deepEqual(new Set(test.source_mix.map(s=>s.exam)),new Set(['2017-sommer','2017-18-winter']));assert.equal(new Set(test.question_ids).size,8);assert.equal(test.question_ids.filter(id=>test.question_models[id].kind==='multiple_choice').length,6);await page.screenshot({path:evidence+'/mixed-ap-test.png',fullPage:true});
  for(const id of test.question_ids){const index=test.question_ids.indexOf(id);await page.getByRole('navigation',{name:'Prüfungsaufgaben',exact:true}).getByRole('button').nth(index).click();await saved();const model=test.question_models[id];if(model.kind==='multiple_choice')await page.getByRole('radio',{name:String(test.official_answers[id]||1),exact:true}).check();else await page.getByLabel('Prüfung '+model.number+' Teil '+model.subpart_ids[0],{exact:true}).fill('Selbst beantwortet');await saved();assert.equal(await page.locator('.submitted-answer').count(),0);}
  await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await saved();assert.equal((await current()).status,'completed');for(const id of test.question_ids.filter(id=>test.question_models[id].kind==='multi_part')){await page.getByRole('navigation',{name:'Prüfungsaufgaben',exact:true}).getByRole('button').nth(test.question_ids.indexOf(id)).click();await saved();for(const select of await page.locator('.submitted-answer select').all()){await select.selectOption('richtig');await saved();}}assert.equal((await current()).result.richtig,8);await page.screenshot({path:evidence+'/mixed-ap-result.png',fullPage:true});checks.mixed_ap_8_answers_both_seasons_result=true;
  const after=await snapshot();for(const row of before.attempts)assert.deepEqual(after.attempts.find(a=>a.attempt_id===row.attempt_id),row);for(const row of before.learningSessions)assert.deepEqual(after.learningSessions.find(a=>a.question_id===row.question_id),row);checks.old_summer_learning_unchanged=true;
  await nav('Start').click();await page.getByRole('heading',{name:'Letzte Prüfungen',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.mobile_and_recent_history=true;assert.deepEqual(errors,[]);await fs.writeFile(evidence+'/acceptance.json',JSON.stringify({url:base,checks,source_mix:test.source_mix,seed:test.seed,page_errors:errors},null,2));console.log(checks);
 }catch(e){await page.screenshot({path:evidence+'/failure.png',fullPage:true});await fs.writeFile(evidence+'/failure.txt',page.url()+'\n'+await page.locator('body').innerText());throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
