const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
 const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir=process.env.EVIDENCE_DIR||'docs/evidence/phase3c/browser';fs.mkdirSync(dir,{recursive:true});
 const server=process.env.APP_URL?null:require('child_process').spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5174','--strictPort'],{stdio:'ignore',windowsHide:true});if(server)await new Promise(r=>setTimeout(r,1500));
 const profile=fs.mkdtempSync(require('path').join(require('os').tmpdir(),'phase3c-browser-'));let context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:1440,height:1000}}),p=await context.newPage();const checks=[],errors=[];p.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message)});p.on('console',m=>{if(m.type()==='error')console.error('CONSOLE',m.text())});
 const button=n=>p.getByRole('button',{name:n,exact:true}),toggle=()=>p.getByRole('checkbox',{name:'Diese Aufgabe ist mir unsicher',exact:true}),go=s=>p.goto(base+s),study=n=>'?view=study&exam=2017-sommer&module=arbeitsplanung&q='+n;
 const read=store=>p.evaluate(store=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,t=db.transaction(store),q=t.objectStore(store).getAll();t.oncomplete=()=>{resolve(q.result);db.close()};t.onerror=()=>reject(t.error)};r.onerror=()=>reject(r.error)}),store);
 const shot=n=>p.screenshot({path:dir+'/'+n+'.png',fullPage:false});
 const mark=async active=>{await toggle().waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);if(await toggle().isChecked()!==active)await toggle().click();await p.waitForFunction(active=>document.querySelector('.question-uncertainty input')?.checked===active,active);await p.locator('.question-uncertainty').getByText('Gespeichert',{exact:true}).waitFor();};
 const choice=async answer=>{const retry=button('Aufgabe erneut versuchen');await button('Lösung anzeigen').waitFor();if(await retry.count()){await retry.click();await p.waitForFunction(()=>!document.querySelector('.choice-options input:checked')&&!document.querySelector('.choice-options')?.disabled)}await p.getByRole('radio',{name:String(answer),exact:true}).check();await button('Antwort abgeben').click();await p.locator('.result-banner').waitFor();};
 const count=async n=>p.getByTestId('uncertainty-count').filter({hasText:new RegExp('^'+n+' Aufgaben$')}).waitFor();
 try{
 const inventory=await(await p.request.get(base+'data/question_inventory.json')).json(),key=await(await p.request.get(base+'data/2017_sommer_arbeitsplanung_answers.json')).json();
 const q=n=>inventory.find(q=>q.examId==='2017-sommer'&&q.module==='arbeitsplanung'&&q.number===String(n)),answer=n=>key.answers.find(a=>a.question_id===q(n).question_id).official_answer;
 await go(study(1));await mark(true);await button('Lösung anzeigen').click();await p.locator('.mc-source').waitFor();assert.equal((await read('attempts')).length,0);await p.reload();await toggle().waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);assert.equal(await toggle().isChecked(),true);assert.equal((await read('attempts')).length,0);assert.equal((await read('moduleProgress')).some(r=>Object.keys(r.completed||{}).length),false);checks.push('Blank marking and solution viewing persist without Attempt/completion');
 await choice(answer(1));const immutable=(await read('attempts'))[0];assert.equal(immutable.unsure,true);await mark(false);assert.deepEqual((await read('attempts'))[0],immutable);await mark(true);await shot('after-submitted');await button('Aufgabe erneut versuchen').click();assert.equal(await toggle().isChecked(),true);await go(study(2));await go(study(1));await toggle().waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);assert.equal(await toggle().isChecked(),true);checks.push('Post-submit toggle works; Attempt snapshot immutable; retry/question switch preserve state');
 await go('?view=wrong');await count(1);await go(study(2));await mark(true);await choice(answer(2)===1?2:1);await go('?view=wrong');await count(1);await p.locator('[data-stage="1"] .stage-count').filter({hasText:/^1$/}).waitFor();
 for(const stage of [2,3,'mastered']){await go(study(2));await choice(answer(2));await go('?view=wrong');await p.locator(`[data-stage="${stage}"] .stage-count`).filter({hasText:/^1$/}).waitFor();await count(stage==='mastered'?2:1)}await shot('collection-desktop');checks.push('Wrong stage1/2/3 excluded; three formal corrects reach mastered and marked question re-enters Unsicher');
 await go(study(1));await mark(false);await go('?view=wrong');await count(1);await button('Unsichere Aufgaben jetzt üben').click();await p.getByRole('heading',{name:'Unsicher Training',exact:true}).waitFor();const runId=new URL(p.url()).searchParams.get('run'),run=(await read('trainingRuns')).find(r=>r.run_id===runId);assert.deepEqual(run.question_ids,[q(2).question_id]);await mark(false);await p.reload();await toggle().waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);assert.equal(await toggle().isChecked(),false);assert.deepEqual((await read('trainingRuns')).find(r=>r.run_id===runId).question_ids,run.question_ids);await mark(true);await shot('training-snapshot');await button('Training neu starten').click();await button('Neue Runde starten').click();await p.waitForURL(u=>u.searchParams.get('run')!==runId);await p.waitForFunction(()=>document.querySelector('.question-uncertainty input')?.checked===true);assert.equal(await toggle().isChecked(),true);checks.push('Collection cancellation immediate; frozen run survives change/reload; restart keeps persistent marking');
 await go(study(2));await p.getByLabel('Lernnotiz',{exact:true}).fill('Phase3C preserved note');await button('Notiz speichern').click();await p.locator('.question-note').getByText('Gespeichert',{exact:true}).waitFor();const notes=await read('questionNotes');await button('Modul neu starten').click();await button('Modul zurücksetzen bestätigen').click();await toggle().waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);assert.equal(await toggle().isChecked(),true);assert.deepEqual(await read('questionNotes'),notes);checks.push('Module reset preserves uncertainty and QuestionNote');
 await go('?view=exams&exam=2017-sommer&module=arbeitsplanung');await button('Neue Originalprüfung · Arbeitsplanung').click();await p.locator('.exam-workspace').waitFor();assert.equal(await toggle().count(),0);await p.getByRole('radio',{name:'1',exact:true}).check();await button('Prüfung abgeben').click();await button('Jetzt abgeben').click();await toggle().waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);await mark(true);await shot('submitted-exam');checks.push('Active Originalprüfung hides historical uncertainty; submitted review can edit current state');
 await go('?view=tests&years=2017-sommer&module=arbeitsplanung');await p.locator('[data-module="arbeitsplanung"]').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await p.locator('.exam-workspace').waitFor();assert.equal(await toggle().count(),0);await button('Prüfung abgeben').click();await button('Jetzt abgeben').click();await mark(true);await shot('submitted-modultest');checks.push('Active Modultest hides historical state; submitted review can independently mark unanswered question');
 const statesBeforeClose=await read('questionUncertainty');await context.close();context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:390,height:844}});p=await context.newPage();await go(study(2));await toggle().waitFor();await p.waitForFunction(()=>!document.querySelector('.question-uncertainty input')?.disabled);assert.equal(await toggle().isChecked(),true);assert.deepEqual(await read('questionUncertainty'),statesBeforeClose);assert.equal(await p.getByLabel('Lernnotiz',{exact:true}).inputValue(),'Phase3C preserved note');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await toggle().scrollIntoViewIfNeeded();await shot('practice-mobile');await go('?view=wrong');await p.getByTestId('uncertainty-count').waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:dir+'/collection-mobile.png',fullPage:true});checks.push('Actual browser close/reopen preserves state and notes; mobile no overflow');
 assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/acceptance.json',JSON.stringify({base,checks,isolated_persistent_browser:true,real_user_data_touched:false,errors},null,2));console.log(checks);
 }catch(e){await shot('failure');throw e}finally{await context.close();server?.kill()}
})().catch(e=>{console.error(e);process.exit(1)});
