const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
 const base=process.env.APP_URL||'http://127.0.0.1:5173/';const evidence=process.env.EVIDENCE_DIR||'docs/evidence/phase2d/browser';await fs.mkdir(evidence,{recursive:true});
 const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks={};
 const nav=name=>page.getByRole('navigation',{name:'Hauptnavigation',exact:true}).getByRole('button',{name,exact:true});const card=name=>page.locator('.exam-card').filter({has:page.getByRole('heading',{name,exact:true})});
 const saved=()=>page.locator('.exam-workspace .save-status').filter({hasText:'Sitzung gespeichert'}).waitFor();const ready=()=>page.getByRole('region',{name:'Prüfungssitzung',exact:true}).waitFor();
 const snapshot=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,names=['attempts','learningSessions','testSessions','reviews','answerReviews'],tx=db.transaction(names,'readonly'),requests=Object.fromEntries(names.map(n=>[n,tx.objectStore(n).getAll()]));tx.oncomplete=()=>{resolve(Object.fromEntries(names.map(n=>[n,requests[n].result])));db.close();};};}));
 const current=async()=>{const id=new URL(page.url()).searchParams.get('session');return(await snapshot()).testSessions.find(s=>s.test_id===id);};
 try{
  await page.goto(base+'?view=study&q=1');await page.getByRole('heading',{name:'Aufgabe 1',exact:true}).waitFor();await page.getByRole('radio',{name:'4',exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();await page.getByText('Notiz',{exact:true}).click();await page.getByLabel('Lernnotiz',{exact:true}).fill('AP bleibt geschützt');await page.getByRole('button',{name:'Reflexion speichern',exact:true}).click();await page.getByText('Reflexion gespeichert',{exact:true}).waitFor();
  await nav('Originalprüfungen').click();await card('Funktionsanalyse').getByRole('button',{name:'Neue Originalprüfung · Funktionsanalyse',exact:true}).click();await ready();await page.getByRole('button',{name:'Pausieren',exact:true}).click();await saved();const baseline=await snapshot();
  const data=await(await page.request.get(new URL('data/2017_sommer_wiso_segmented.json',base).href)).json();const answers=await(await page.request.get(new URL('data/2017_sommer_wiso_answers.json',base).href)).json();const solutions=await(await page.request.get(new URL('data/2017_sommer_wiso_u_solutions.json',base).href)).json();assert.equal(data.questions.length,24);assert.equal(answers.answers.length,18);assert.equal(solutions.solutions.length,6);
  await nav('Lernen').click();assert.equal(await page.locator('.module-cards .exam-card').count(),3);await card('WiSo').getByRole('button',{name:/Gebundene Aufgaben/}).click();const key=answers.answers.find(a=>a.official_answer_status==='auto_ready');assert.ok(key);await page.getByRole('button',{name:'Aufgabe '+key.question_number,exact:true}).click();assert.equal(await page.locator('.mc-source').count(),0);await page.getByRole('radio',{name:String(key.official_answer),exact:true}).check();await page.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();await page.getByText('Offizielle Antwortquelle',{exact:true}).click();await page.locator('.mc-source').evaluate(img=>img.decode());checks.wiso_registry_18_6_real_MC_grade=true;
  await page.getByRole('button',{name:'Ungebundene Aufgaben · 6 Aufgaben',exact:true}).click();await page.getByRole('button',{name:'Aufgabe U6',exact:true}).click();await page.locator('.question-art img').evaluate(img=>img.decode());assert.equal(await page.getByRole('link',{name:'Original-PDF · Seite 5 ↗',exact:true}).count(),1);assert.equal(await page.getByRole('link',{name:'Original-PDF · Seite 4 ↗',exact:true}).count(),1);await page.screenshot({path:evidence+'/wiso-u6-complete.png',fullPage:true});checks.U6_composite_and_two_source_links=true;
  await page.getByRole('button',{name:'Review / Quellen',exact:true}).click();await page.getByRole('button',{name:'Prüfen / Bearbeiten',exact:true}).click();await page.getByText('Du bearbeitest nur den Hauptbereich',{exact:false}).waitFor();await page.getByText('Vorschau des neuen Ausschnitts',{exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('.review-editor canvas')].length===2&&[...document.querySelectorAll('.review-editor canvas')].every(c=>c.getContext('2d').getImageData(0,0,1,1).data[3]===255));
  const continuationBefore=await page.locator('.review-editor canvas[data-source-page="4"]').evaluate(c=>c.toDataURL());const left=page.getByLabel('Ausschnitt Links',{exact:true});await left.fill(String(Number(await left.inputValue())+1));await page.waitForFunction(()=>[...document.querySelectorAll('.review-editor canvas')].every(c=>c.getContext('2d').getImageData(0,0,1,1).data[3]===255));assert.equal(await page.locator('.review-editor canvas[data-source-page="4"]').evaluate(c=>c.toDataURL()),continuationBefore);await page.screenshot({path:evidence+'/wiso-u6-review-primary-only.png',fullPage:true});await page.getByRole('button',{name:'Speichern · Confirmed',exact:true}).click();await page.getByRole('button',{name:'Zurück zum Lernen',exact:true}).click();await page.waitForURL(u=>u.searchParams.get('view')==='study');await page.getByRole('region',{name:'Antwort bearbeiten',exact:true}).waitFor();await page.locator('.question-art canvas[data-source-page="4"]').waitFor();await page.reload();await page.locator('.question-art canvas[data-source-page="4"]').waitFor();await page.waitForFunction(()=>document.querySelector('.question-art canvas[data-source-page="4"]')?.getContext('2d').getImageData(0,0,1,1).data[3]===255);assert.equal(await page.locator('.question-art canvas[data-source-page="4"]').evaluate(c=>c.toDataURL()),continuationBefore);checks.review_primary_edit_preserves_continuation_after_reload=true;
  const u6=solutions.solutions.find(s=>s.question_number==='U6');await page.getByLabel('U6 Teil '+u6.subparts[0].id,{exact:true}).fill('Eigene Antwort');await page.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await page.locator('.u-solution-image').evaluate(img=>img.decode());for(const p of u6.subparts)await page.getByLabel('U6 Bewertung '+p.id,{exact:true}).selectOption('richtig');await page.getByRole('button',{name:'Bewertung speichern',exact:true}).click();await page.locator('.result-banner.richtig').waitFor();checks.WiSo_U_solution_and_self_assessment=true;
  await nav('Originalprüfungen').click();await card('WiSo').getByRole('button',{name:'Neue Originalprüfung · WiSo',exact:true}).click();await ready();let s=await current();assert.equal(s.question_ids.length,24);assert.deepEqual(s.question_ids.map(id=>s.question_models[id].number),[...Array.from({length:18},(_,i)=>String(i+1)),...Array.from({length:6},(_,i)=>'U'+(i+1))]);assert.deepEqual(s.answers,{});checks.original24_registered_order=true;checks.duration_minutes=s.duration_minutes;
  await page.getByRole('button',{name:'Prüfungsaufgabe U6',exact:true}).click();await saved();await page.getByLabel('Prüfung U6 Teil '+u6.subparts[0].id,{exact:true}).fill('Prüfungsantwort');await saved();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('heading',{name:'Vorläufiges Ergebnis',exact:true}).waitFor();assert.equal((await current()).result.pending,1);assert.equal(await page.getByRole('link',{name:'Originalaufgabe · PDF-Seite 5 ↗',exact:true}).count(),1);assert.equal(await page.getByRole('link',{name:'Originalaufgabe · PDF-Seite 4 ↗',exact:true}).count(),1);checks.original_U_pending_with_complete_sources=true;
  await nav('Tests').click();await card('WiSo').getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await ready();s=await current();assert.equal(s.question_ids.length,8);assert.equal(Object.values(s.question_models).filter(q=>q.kind==='multiple_choice').length,6);assert.equal(new Set(s.question_ids).size,8);await nav('Tests').click();await card('WiSo').getByRole('button',{name:'Standard starten · 12 MC + 4 U',exact:true}).click();await page.getByRole('button',{name:'Verwerfen und neu starten',exact:true}).click();await ready();s=await current();assert.equal(s.question_ids.length,16);assert.equal(Object.values(s.question_models).filter(q=>q.kind==='multi_part').length,4);assert.equal(new Set(s.question_ids).size,16);checks.unchanged_test_sizes_6_2_and_12_4=true;
  const mc=s.question_ids.find(id=>s.question_models[id].kind==='multiple_choice');await page.getByRole('button',{name:'Prüfungsaufgabe '+s.question_models[mc].number,exact:true}).click();await saved();await page.getByRole('radio',{name:String(s.official_answers[mc]??1),exact:true}).check();await saved();await page.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await page.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await page.getByRole('region',{name:'Ergebnis',exact:true}).waitFor();assert.equal((await current()).result.total,16);checks.WiSo_modultest_submit_result=true;
  const final=await snapshot();const ids=new Set(data.questions.map(q=>q.question_id));for(const store of ['attempts','learningSessions','reviews','answerReviews'])assert.deepEqual(final[store].filter(x=>!ids.has(x.question_id)),baseline[store]);assert.deepEqual(final.testSessions.filter(s=>s.module!=='wiso'),baseline.testSessions);checks.AP_FA_private_data_and_sessions_unchanged=true;
  await nav('Start').click();assert.equal(await page.getByText(/Winter/).count(),0);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:evidence+'/dashboard-wiso-mobile.png',fullPage:true});checks.no_winter_production_mobile_clean=true;assert.deepEqual(errors,[]);
  await fs.writeFile(evidence+'/acceptance.json',JSON.stringify({url:base,checks,page_errors:errors},null,2));console.log(JSON.stringify(checks,null,2));
 }catch(error){await page.screenshot({path:evidence+'/failure.png',fullPage:true});await fs.writeFile(evidence+'/failure.txt',page.url()+'\n'+await page.locator('body').innerText());throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
