const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),base=process.env.APP_URL||'http://127.0.0.1:5174/',dir='docs/evidence/winter2020-21/browser';fs.mkdirSync(dir,{recursive:true});const checks=[];try{
 const c=await b.newContext({viewport:{width:1400,height:950}}),p=await c.newPage();const url=(exam,module,q=1)=>base+`?view=study&exam=${exam}&module=${module}&q=${q}`;const note=p.getByRole('textbox',{name:'Lernnotiz',exact:true});
 await p.goto(url('2020-sommer','arbeitsplanung'));await note.fill('Old note remains');await p.getByRole('button',{name:'Notiz speichern',exact:true}).click();await p.locator('.question-note').getByText('Gespeichert',{exact:true}).waitFor();
 for(const [module,n] of [['arbeitsplanung',36],['funktionsanalyse',36],['wiso',24]]){await p.goto(url('2020-21-winter',module));await p.getByRole('region',{name:'Aktueller Lernfortschritt',exact:true}).getByText(`0 / ${n}`,{exact:true}).waitFor();assert.equal(await note.inputValue(),'');checks.push(module+' clean progress');}
 await p.goto(url('2020-21-winter','arbeitsplanung'));await note.fill('Winter persistent note');await p.getByRole('button',{name:'Notiz speichern',exact:true}).click();await p.locator('.question-note').getByText('Gespeichert',{exact:true}).waitFor();await p.getByRole('radio',{name:'1',exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.getByRole('button',{name:'Aufgabe erneut versuchen',exact:true}).click();await p.reload();await note.waitFor();assert.equal(await note.inputValue(),'Winter persistent note');await p.goto(url('2020-sommer','arbeitsplanung'));await note.waitFor();assert.equal(await note.inputValue(),'Old note remains');checks.push('Notes isolated and persistent after retry/refresh');
 await p.goto(url('2020-21-winter','wiso','U1'));await note.waitFor();assert.equal(await p.locator('.official-correction').count(),0);await p.locator('.subparts textarea').first().fill('Test');await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.locator('.official-correction').getByText(/4 Punkten/).waitFor();await p.getByText('Offizielle Änderungsmitteilung ansehen',{exact:true}).click();await p.screenshot({path:dir+'/wiso-correction-study.png',fullPage:true});checks.push('WiSo correction only after solution reveal');
 await p.goto(base+'?view=exams&exam=2020-21-winter&module=wiso');await p.getByRole('button',{name:'Neue Originalprüfung · WiSo',exact:true}).click();await p.locator('.exam-workspace').waitFor();await p.getByRole('navigation',{name:'Prüfungsaufgaben',exact:true}).getByRole('button',{name:'Prüfungsaufgabe U1',exact:true}).click();assert.equal(await p.locator('.official-correction').count(),0);assert.equal(await p.locator('.question-note').count(),0);await p.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await p.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await p.locator('.official-correction').waitFor();await p.screenshot({path:dir+'/wiso-correction-exam-review.png',fullPage:true});checks.push('Correction hidden in active exam, visible after submission');await c.close();
 const mobile=await b.newContext({viewport:{width:390,height:844},isMobile:true}),mp=await mobile.newPage();await mp.goto(base+'?view=learn&exam=2020-21-winter');await mp.getByRole('heading',{name:'Funktionsanalyse',exact:true}).waitFor();assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:dir+'/mobile-year.png',fullPage:true});await mp.goto(url('2020-21-winter','funktionsanalyse','U7'));await mp.getByRole('textbox',{name:'Lernnotiz',exact:true}).waitFor();assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:dir+'/mobile-fa-u7.png',fullPage:true});checks.push('Mobile 390px no overflow');await mobile.close();fs.writeFileSync(dir+'/correction-progress-notes.json',JSON.stringify({checks,isolated_context:true,real_user_data_touched:false},null,2));console.log(checks);
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});

