const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir='docs/evidence/overnight/browser';fs.mkdirSync(dir,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});const c=await b.newContext({viewport:{width:1400,height:950},acceptDownloads:true});const p=await c.newPage(),checks=[];try{
 const data=await(await p.request.get(base+'data/overnight_review_queue.json')).json();const target=data.items.find(i=>i.type==='official_answer');await p.goto(base+'?view=review-queue&item='+target.id);await p.getByRole('heading',{name:'Morgen Review Queue',exact:true}).waitFor();await p.getByRole('radio').first().waitFor();await p.waitForFunction(()=>document.querySelector('input[type=radio]')&&!document.querySelector('input[type=radio]').disabled);
 assert.equal(await p.getByRole('radio').filter({has:p.locator(':checked')}).count(),0);assert.equal(await p.getByRole('button',{name:'Bestätigen / Änderung speichern',exact:true}).isDisabled(),true);checks.push('No machine candidate preselected; source hash required');await p.screenshot({path:dir+'/answer-review-desktop.png',fullPage:true});
 await p.getByRole('radio').first().check();p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:'Next →',exact:true}).click();assert.ok(p.url().includes(target.id));checks.push('Unsaved choice protected');await p.getByRole('button',{name:'Bestätigen / Änderung speichern',exact:true}).click();await p.getByRole('status').filter({hasText:'Gespeichert'}).waitFor();await p.reload();await p.waitForFunction(()=>document.querySelector('input[type=radio]')?.checked);checks.push('Synthetic local confirmation persists, no production update');
 const download=p.waitForEvent('download');await p.getByRole('button',{name:'Alle Entscheidungen exportieren',exact:true}).click();const d=await download;const exported=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert.equal(exported.confirmations.length,1);assert.equal(exported.scopes.flatMap(s=>s.confirmations).length,1);assert.equal(exported.confirmations[0].locked,true);checks.push('Unified export scopes and locked source binding');
 const counts=await p.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('ap2-private-learning');req.onsuccess=()=>{const db=req.result;const names=['attempts','testSessions','questionNotes','moduleRuns'].filter(n=>db.objectStoreNames.contains(n));const results={};Promise.all(names.map(n=>new Promise(ok=>{const r=db.transaction(n).objectStore(n).count();r.onsuccess=()=>{results[n]=r.result;ok()}}))).then(()=>{db.close();resolve(results)})};req.onerror=()=>reject(req.error)}));assert.ok(Object.values(counts).every(n=>n===0));checks.push({personal_learning_unchanged:counts});
 const mapping=data.items.find(i=>i.type==='attachment_mapping');await p.route('**/assets/review/**',r=>r.fulfill({status:200,contentType:'image/png',body:'wrong bytes'}));await p.goto(base+'?view=review-queue&item='+mapping.id);await p.getByRole('alert').filter({hasText:'nicht verifiziert'}).first().waitFor();assert.equal(await p.getByRole('button',{name:'Bestätigen',exact:true}).isDisabled(),true);checks.push('Tampered mapping evidence cannot be confirmed');await p.unroute('**/assets/review/**');await p.reload();await p.waitForFunction(()=>[...document.querySelectorAll('button')].find(b=>b.textContent==='Bestätigen')?.disabled===false);await p.screenshot({path:dir+'/boundary-review-desktop.png',fullPage:true});
 await p.setViewportSize({width:390,height:844});await p.goto(base+'?view=review-queue&item='+data.items.find(i=>i.type==='official_answer'&&i.id!==target.id).id);await p.getByRole('radio').first().waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:dir+'/answer-review-mobile.png',fullPage:true});checks.push('Mobile no horizontal overflow');await p.getByRole('button',{name:'Next →',exact:true}).click();const current=p.url();await p.getByRole('radio').first().check();p.once('dialog',d=>d.dismiss());await p.goBack();await p.waitForURL(current);assert.equal(await p.getByRole('radio').first().isChecked(),true);checks.push('Browser Back protects unsaved review draft');
 fs.writeFileSync(dir+'/checks.json',JSON.stringify({checks,isolated_context:true,synthetic_confirmation_not_exported_to_production:true},null,2));console.log('Overnight browser acceptance passed',checks.length)
}finally{await c.close();await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
