const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5174/',dir=process.env.EVIDENCE_DIR||'docs/evidence/phase2j1/browser';fs.mkdirSync(dir,{recursive:true});const profile=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'ap2-notes-acceptance-'));let context;const checks=[],errors=[];
const launch=()=>chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:1440,height:1000}});
const read=(p,store)=>p.evaluate(store=>new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,t=db.transaction(store),q=t.objectStore(store).getAll();t.oncomplete=()=>{resolve(q.result);db.close()};t.onerror=()=>reject(t.error)}}),store);
const go=(p,q)=>p.goto(base+q);
const study='?view=study&exam=2017-sommer&module=arbeitsplanung&q=';
const savedNote=async(p,text)=>{await p.getByRole('textbox',{name:'Lernnotiz',exact:true}).fill(text);await p.getByRole('button',{name:'Notiz speichern',exact:true}).click();await p.locator('.question-note [role=status]').filter({hasText:/^Gespeichert$/}).waitFor();};
const note=async(p,text)=>{await p.getByRole('textbox',{name:'Lernnotiz',exact:true}).waitFor();await p.waitForFunction(text=>document.querySelector('[aria-label="Lernnotiz"]')?.value===text,text);};
try{context=await launch();let p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));const questions=await(await p.request.get(base+'data/2017_sommer_arbeitsplanung_segmented.json')).json(),qid=questions.questions.find(q=>q.question_number==='1').question_id,qid2=questions.questions.find(q=>q.question_number==='2').question_id;
await p.route('**/__notes_seed',r=>r.fulfill({contentType:'text/html',body:'<html>Isolated acceptance seed</html>'}));await go(p,'__notes_seed');
const legacy=await p.evaluate(async({qid,qid2})=>{const attempt=(id,q,n,t)=>({userId:'local',attempt_id:id,question_id:q,timestamp:t,user_answer:{choice:1},correctness:'falsch',partial_status:false,unsure:false,confidence:'sure',hints_used:[],error_reason:'Historical reason stays unchanged',note:n,self_assessed:false,auto_scored:true,subparts:[]});const rows=[attempt('old-1',qid,'Old attempt note','2025-01-01'),attempt('old-2',qid2,'Earlier note','2025-01-01'),attempt('old-3',qid2,'Latest nonempty note','2025-02-01'),attempt('old-4',qid2,'','2025-03-01')];await new Promise((resolve,reject)=>{const r=indexedDB.open('ap2-private-learning',70);r.onupgradeneeded=()=>{const db=r.result;for(const [name,id] of Object.entries({records:'questionId',reviews:'question_id',answerReviews:'question_id',attempts:'attempt_id',learningSessions:'question_id',testSessions:'test_id',settings:'id'})){const s=db.createObjectStore(name,{keyPath:['userId',id]});s.createIndex('userId','userId');if(name==='attempts')s.createIndex('[userId+question_id]',['userId','question_id']);if(name==='testSessions'){s.createIndex('[userId+module]',['userId','module']);s.createIndex('[userId+status]',['userId','status']);}}for(const name of ['syncMeta','outbox','tombstones','syncConflicts']){const s=db.createObjectStore(name,{keyPath:['userId','entity','id']});s.createIndex('userId','userId');}db.createObjectStore('deviceState',{keyPath:'key'});};r.onsuccess=()=>{const db=r.result,t=db.transaction(['attempts','learningSessions'],'readwrite');rows.forEach(a=>t.objectStore('attempts').put(a));t.objectStore('learningSessions').put({userId:'local',question_id:qid,draft:{note:'Session priority note'},revealed:false});t.oncomplete=()=>{db.close();resolve()};t.onerror=()=>reject(t.error)};r.onerror=()=>reject(r.error)});return rows;},{qid,qid2});
await go(p,study+'1');await note(p,'Session priority note');assert.deepEqual(await read(p,'attempts'),legacy);checks.push('Real v7 → v8 migration: session wins, old attempts/error_reason unchanged');await go(p,study+'2');await note(p,'Latest nonempty note');checks.push('Migration: latest nonempty attempt wins, latest empty ignored');await go(p,study+'1');await savedNote(p,'Meine dauerhafte Notiz · Revision 1');await p.reload();await note(p,'Meine dauerhafte Notiz · Revision 1');await go(p,study+'2');await go(p,study+'1');await note(p,'Meine dauerhafte Notiz · Revision 1');
for(let i=0;i<2;i++){await p.getByRole('radio',{name:'1',exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.getByRole('button',{name:'Neuer Versuch',exact:true}).waitFor();assert.equal(await p.getByText('Warum falsch?',{exact:true}).count(),0);assert.equal(await p.getByText('Fehlerursache',{exact:true}).count(),0);await p.getByRole('button',{name:'Neuer Versuch',exact:true}).click();await note(p,'Meine dauerhafte Notiz · Revision 1');await p.waitForFunction(()=>document.querySelectorAll('input[type=radio]:checked').length===0);}
await p.locator('.question-note').scrollIntoViewIfNeeded();await p.screenshot({path:dir+'/note-after-new-attempt.png'});checks.push('Saved note survives refresh, question switch and two new attempts; Why-wrong removed');await savedNote(p,'Meine dauerhafte Notiz · Revision 2');await go(p,'?view=study&exam=2019-20-winter&module=funktionsanalyse&q=21');await note(p,'');await go(p,study+'1');await note(p,'Meine dauerhafte Notiz · Revision 2');
await context.close();context=await launch();p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await go(p,study+'1');await note(p,'Meine dauerhafte Notiz · Revision 2');checks.push('Latest note survives module/year switch and actual browser close/relaunch');
for(const mode of ['original','module']){await go(p,mode==='original'?'?view=exams&exam=2017-sommer&module=arbeitsplanung':'?view=tests&years=2017-sommer&module=arbeitsplanung');if(mode==='original')await p.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).click();else await p.locator('.exam-card').filter({has:p.getByRole('heading',{name:'Arbeitsplanung',exact:true})}).getByRole('button',{name:'Kurz starten · 6 MC + 2 U',exact:true}).click();await p.locator('.exam-workspace').waitFor();assert.equal(await p.getByRole('textbox',{name:'Lernnotiz',exact:true}).count(),0);assert.equal(await p.getByText('Meine dauerhafte Notiz · Revision 2',{exact:true}).count(),0);await p.getByRole('button',{name:'Prüfung abgeben',exact:true}).click();await p.getByRole('button',{name:'Jetzt abgeben',exact:true}).click();await p.getByText('Notiz ansehen / bearbeiten',{exact:true}).click();await p.getByRole('textbox',{name:'Lernnotiz',exact:true}).waitFor();if(mode==='original'){await note(p,'Meine dauerhafte Notiz · Revision 2');await p.screenshot({path:dir+'/completed-review-note.png',fullPage:true});await p.getByRole('textbox',{name:'Lernnotiz',exact:true}).fill('Review edit survives deletion');await p.waitForFunction(()=>document.querySelector('.study-pagination button:last-child')?.disabled);assert.equal(await p.getByRole('button',{name:'Versuch löschen',exact:true}).isDisabled(),true);await p.getByRole('button',{name:'Notiz speichern',exact:true}).click();await p.locator('.question-note [role=status]').filter({hasText:/^Gespeichert$/}).waitFor();}checks.push(mode+': note hidden before submission, available in review');const currentUrl=new URL(p.url()),tid=currentUrl.searchParams.get('session');await p.getByRole('button',{name:'Versuch verwerfen',exact:true}).click();await p.getByRole('button',{name:'Verwerfen bestätigen',exact:true}).click();await p.getByRole('button',{name:'Versuch löschen',exact:true}).click();await p.getByRole('button',{name:'Dauerhaft löschen',exact:true}).click();await p.waitForFunction(tid=>new Promise(resolve=>{const r=indexedDB.open('ap2-private-learning');r.onsuccess=()=>{const db=r.result,q=db.transaction('testSessions').objectStore('testSessions').get(['local',tid]);q.onsuccess=()=>{resolve(!q.result);db.close()}}}),tid);assert.ok(!(await read(p,'testSessions')).some(s=>s.test_id===tid));assert.equal((await read(p,'questionNotes')).find(n=>n.question_id===qid).text,'Review edit survives deletion');}
checks.push('Discard/delete both test types preserve question notes and ordinary attempts');const after=await read(p,'attempts');for(const old of legacy)assert.deepEqual(after.find(a=>a.attempt_id===old.attempt_id),old);assert.ok(after.filter(a=>!a.attempt_id.startsWith('old-')).every(a=>a.error_reason===''));
await go(p,'?view=study&exam=2019-20-winter&module=funktionsanalyse&q=21');await p.getByRole('radio',{name:'2',exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.locator('.result-banner.richtig').waitFor();await p.getByText('Offizielle Antwortquelle',{exact:true}).click();await p.getByRole('img',{name:'Offizielle Antwortquelle Q21',exact:true}).waitFor();await p.screenshot({path:dir+'/fa-q21-confirmed.png',fullPage:true});checks.push('FA Q21 user-confirmed 2 scores correctly with official source crop');assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/checks.json',JSON.stringify({checks,isolated_profile:true,real_user_data_touched:false,pdf_rescans:0,errors},null,2));console.log(checks);
}finally{await context?.close()}})().catch(e=>{console.error(e);process.exit(1)});
