const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const base=process.env.APP_URL||'http://127.0.0.1:5173/',dir=process.env.EVIDENCE_DIR||'docs/evidence/phase2j/browser';fs.mkdirSync(dir,{recursive:true});const b=await chromium.launch({channel:'chrome',headless:true});const c=await b.newContext({viewport:{width:1400,height:1000}}),p=await c.newPage(),checks=[];try{
 for(const exam of ['2017-sommer','2017-18-winter','2018-sommer','2018-19-winter','2019-sommer','2019-20-winter']){
  await p.goto(base+'?view=exams&exam='+exam+'&module=arbeitsplanung');await p.locator('[data-module]').first().waitFor();const order=await p.locator('[data-module]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-module')));assert.deepEqual(order,['arbeitsplanung','funktionsanalyse','wiso']);checks.push({exam,order});
 }
 await p.getByText('Noch nicht verfügbar',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Neue Originalprüfung · Funktionsanalyse',exact:true}).count(),0);await p.screenshot({path:dir+'/winter-modules.png',fullPage:true});checks.push('FA unavailable; AP/WiSo available');
 await p.goto(base+'?view=study&exam=2019-20-winter&module=arbeitsplanung&q=20');await p.getByText('Prüfungsaufgaben-Beschreibung & Anlagen',{exact:true}).click();const link=p.getByRole('link',{name:'Anlage · Seite 8 ↗',exact:true});assert.ok((await link.getAttribute('href')).includes('attachment-8-'));checks.push('AP Q20 shared drawing linked');
 await p.goto(base+'?view=answer-review&scope=winter-2019-20&item=2019-20-fa-p12-21');await p.getByRole('radio',{name:'1',exact:true}).waitFor();await p.getByRole('img',{name:'Originale Antwortquelle Funktionsanalyse Q21',exact:true}).waitFor();assert.equal(await p.locator('input:checked').count(),0);await p.screenshot({path:dir+'/fa-q21-review.png',fullPage:true});checks.push('Actual Q21 crop verified; candidate not preselected');
 // Synthetic local interaction in a throwaway browser only. Not user confirmation or production evidence.
 await p.getByRole('radio',{name:'1',exact:true}).check();await p.getByRole('button',{name:'Speichern',exact:true}).click();await p.getByText('Gespeichert · Confirmed · gesperrt',{exact:true}).waitFor();await p.reload();await p.getByRole('radio',{name:'1',exact:true}).waitFor();assert.ok(await p.getByRole('radio',{name:'1',exact:true}).isChecked());checks.push('Synthetic isolated save survives refresh; no confirmation imported');
 const downloadEvent=p.waitForEvent('download');await p.getByRole('button',{name:'Bestätigungen exportieren (1/1)',exact:true}).click();const download=await downloadEvent;const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk;const payload=JSON.parse(text);assert.equal(payload.scope,'winter-2019-20');assert.equal(payload.confirmations.length,1);assert.equal(payload.confirmations[0].question_id,'2019-20-fa-p12-21');checks.push('Export scope/source binding correct (discarded test export)');
 await p.goto(base+'?view=answer-review&item=2018-19-fa-p12-27');await p.getByRole('heading',{name:'Funktionsanalyse · Q27',exact:true}).waitFor();assert.equal(await p.getByRole('navigation',{name:'Antwort-Review Aufgaben'}).getByRole('button').count(),8);checks.push('Legacy 8-item URL still works');
 fs.writeFileSync(dir+'/review-navigation-checks.json',JSON.stringify({checks,isolated_context:true,actual_manual_confirmations:0},null,2));console.log('Review/navigation checks passed');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
