const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),base=process.env.APP_URL||'http://127.0.0.1:5174/',dir=process.env.EVIDENCE_DIR||'docs/evidence/sommer2021/browser';fs.mkdirSync(dir,{recursive:true});const checks=[];try{const c=await b.newContext({viewport:{width:1400,height:950}}),p=await c.newPage();const url=(exam,q=1)=>base+`?view=study&exam=${exam}&module=arbeitsplanung&q=${q}`;const note=p.getByRole('textbox',{name:'Lernnotiz',exact:true});
await p.goto(url('2020-21-winter'));await note.fill('Vorherige persönliche Notiz');await p.getByRole('button',{name:'Notiz speichern',exact:true}).click();await p.locator('.question-note').getByText('Gespeichert',{exact:true}).waitFor();await p.getByRole('radio',{name:'1',exact:true}).check();await p.getByRole('button',{name:'Antwort abgeben',exact:true}).click();await p.locator('.result-banner').waitFor();
await p.goto(url('2021-sommer'));await p.getByRole('region',{name:'Aktueller Lernfortschritt',exact:true}).getByText('0 / 36',{exact:true}).waitFor();assert.equal(await note.inputValue(),'');await note.fill('Neue Notiz Sommer 2021');await p.getByRole('button',{name:'Notiz speichern',exact:true}).click();await p.locator('.question-note').getByText('Gespeichert',{exact:true}).waitFor();await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).click();await p.getByRole('button',{name:'Aufgabe erneut versuchen',exact:true}).click();await p.getByText('Neuer Versuch. Frühere Ergebnisse bleiben erhalten.',{exact:true}).waitFor();await p.reload();await note.waitFor();assert.equal(await note.inputValue(),'Neue Notiz Sommer 2021');await p.getByRole('region',{name:'Aktueller Lernfortschritt',exact:true}).getByText('0 / 36',{exact:true}).waitFor();await p.screenshot({path:dir+'/clean-progress.png',fullPage:true});
await p.goto(url('2020-21-winter'));await note.waitFor();assert.equal(await note.inputValue(),'Vorherige persönliche Notiz');await p.getByRole('region',{name:'Aktueller Lernfortschritt',exact:true}).getByText('1 / 36',{exact:true}).waitFor();checks.push('New AP starts 0/36; old attempt/progress and note remain; new note survives retry/refresh');
await p.goto(url('2021-sommer','U1'));await p.getByText('Stirnradgetriebe mit Stückliste · Blatt 1 von 2',{exact:true}).click();const link=p.getByRole('link',{name:'Originalanlage groß öffnen ↗',exact:true});assert.match(await link.getAttribute('href'),/clockwise-v1/);const response=await p.request.get(new URL(await link.getAttribute('href'),base).href);assert.equal(response.status(),200);await p.locator('.external-attachments').screenshot({path:dir+'/shared-drawing.png'});checks.push('AP U1 shared external drawing upright and available');
await p.goto(base+'?view=exams&exam=2021-sommer&module=arbeitsplanung');await p.getByRole('button',{name:'Neue Originalprüfung · Arbeitsplanung',exact:true}).click();await p.locator('.exam-workspace').waitFor();await p.getByRole('button',{name:'Prüfungsaufgabe U1',exact:true}).click();await p.locator('.external-attachments').waitFor();assert.equal(await p.getByRole('button',{name:'Lösung anzeigen',exact:true}).count(),0);checks.push('Original exam includes mapped drawing and hides solutions');
await p.goto(base+'?view=answer-review&scope=sommer-2021');await p.locator('.manual-crop img').waitFor();await p.getByText(/WiSo: 0\/1 manuell · 17\/18/).waitFor();assert.equal(await p.locator('.manual-options input:checked').count(),0);assert.equal(await p.getByRole('button',{name:'Speichern',exact:true}).isDisabled(),true);await p.screenshot({path:dir+'/review-fa-q4.png',fullPage:true});await p.getByRole('button',{name:'FA Q23',exact:true}).click();await p.locator('.manual-crop img').waitFor();await p.getByRole('button',{name:'WiSo Q18',exact:true}).click();await p.locator('.manual-crop img').waitFor();await p.screenshot({path:dir+'/review-wiso-q18.png',fullPage:true});checks.push('Exactly three pending manual reviews; verified crops; candidates not selected; WiSo 17/18');
await c.close();const mobile=await b.newContext({viewport:{width:390,height:844},isMobile:true}),mp=await mobile.newPage();await mp.goto(url('2021-sommer','U1'));await mp.locator('.practice').waitFor();await mp.getByText('Stirnradgetriebe mit Stückliste · Blatt 1 von 2',{exact:true}).click();assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:dir+'/mobile-u1.png',fullPage:true});checks.push('Mobile 390px no horizontal overflow including drawing');await mobile.close();fs.writeFileSync(dir+'/isolation-review.json',JSON.stringify({checks,isolated_context:true,real_user_data_touched:false},null,2));console.log(checks)}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
