import 'fake-indexeddb/auto';
import Dexie from 'dexie';
import {it,expect} from 'vitest';
import {IndexedDBProgressRepository} from './storage';
import {createSession} from '../exams/model';
import {MODULES} from '../learning/modules';
import ap from '../../public/data/2017_sommer_arbeitsplanung_segmented.json';
import keys from '../../public/data/2017_sommer_arbeitsplanung_answers.json';
import u from '../../public/data/2017_sommer_arbeitsplanung_u_solutions.json';
import type {SegmentedExam} from '../segmented/types';
import type {OfficialAnswer} from '../segmented/answers';
import type {USolution} from '../learning/model';
const make=()=>createSession({type:'original',config:MODULES[0],exam:ap as unknown as SegmentedExam,officialAnswers:keys.answers as OfficialAnswer[],solutions:u.solutions as USolution[]});
it('migrates real v4 without changing any old table and keeps tests independent',async()=>{
 const name='legacy-exam-'+crypto.randomUUID();const old=new Dexie(name);
 old.version(1).stores({records:'[userId+questionId],userId'});old.version(2).stores({reviews:'[userId+question_id],userId'});old.version(3).stores({answerReviews:'[userId+question_id],userId'});old.version(4).stores({attempts:'[userId+attempt_id],userId,[userId+question_id]',learningSessions:'[userId+question_id],userId'});
 const fixtures={records:{userId:'local',questionId:'old-id',fields:{note:{value:'keep',locked:true}}},reviews:{userId:'local',question_id:'old-id',tags:['keep']},answerReviews:{userId:'local',question_id:'old-id',official_answer:4,locked:true},attempts:{userId:'local',attempt_id:'old-attempt',question_id:'old-id',note:'keep'},learningSessions:{userId:'local',question_id:'old-id',draft:{choice:'4'}}};
 for(const [table,value] of Object.entries(fixtures))await old.table(table).put(value);old.close();
 const repo=new IndexedDBProgressRepository(name);const s=await repo.createTestSession(make());await repo.updateTestSession('local',s.test_id,s.revision,{type:'answer',questionId:s.question_ids[0],answer:{choice:'3'}});repo.close();
 const check=new Dexie(name);await check.open();expect(check.verno).toBe(5);for(const [table,value] of Object.entries(fixtures))expect(await check.table(table).toArray()).toEqual([value]);check.close();await Dexie.delete(name);
});
it('prevents silent replacement and stale-tab overwrites transactionally',async()=>{
 const name='session-conflict-'+crypto.randomUUID(),repo=new IndexedDBProgressRepository(name);const s=await repo.createTestSession(make());
 await expect(repo.createTestSession(make())).rejects.toThrow();
 const [a,b]=await Promise.allSettled([repo.updateTestSession('local',s.test_id,0,{type:'answer',questionId:s.question_ids[0],answer:{choice:'2'}}),repo.updateTestSession('local',s.test_id,0,{type:'answer',questionId:s.question_ids[0],answer:{choice:'4'}})]);
 expect([a,b].filter(r=>r.status==='fulfilled')).toHaveLength(1);
 await expect(repo.createTestSession(make(),{id:s.test_id,revision:0})).rejects.toThrow();
 const latest=await repo.getTestSession('local',s.test_id);const replacement=await repo.createTestSession(make(),{id:s.test_id,revision:latest!.revision});expect((await repo.getTestSession('local',s.test_id))?.status).toBe('abandoned');expect((await repo.getTestSessions('local')).length).toBe(2);expect(replacement.answers).toEqual({});
 await repo.updateTestSession('local',replacement.test_id,0,{type:'pause'});repo.close();const reopened=new IndexedDBProgressRepository(name);expect((await reopened.getTestSession('local',replacement.test_id))?.status).toBe('paused');reopened.close();await Dexie.delete(name);
});
