import 'fake-indexeddb/auto';
import Dexie from 'dexie';
import {it,expect} from 'vitest';
import {IndexedDBProgressRepository} from './storage';
import {summarizeProgress} from '../learning/moduleProgress';
import type {Attempt} from '../learning/model';
const descriptor={exam:'2019-20-winter',module:'arbeitsplanung',question_ids:['q1','q2','q3','u1']};
const a=(id:string,q:string,result:Attempt['correctness'],time='2026-01-01'):Attempt=>({userId:'local',attempt_id:id,question_id:q,timestamp:time,user_answer:{choice:1},correctness:result,partial_status:result==='teilweise',unsure:false,confidence:'sure',hints_used:[],error_reason:'old reason',note:'old note',self_assessed:false,auto_scored:true,subparts:[]});
const setup=()=>{const name='module-progress-'+crypto.randomUUID(),r=new IndexedDBProgressRepository(name);return {r,close:async()=>{r.close();await Dexie.delete(name)}}};
it('migration is idempotent, latest valid result counts once, history remains immutable',async()=>{const x=setup();try{
 const rows=[a('old','q1','falsch'),a('new','q1','richtig','2026-02-01'),a('invalid','q1',null,'2026-03-01'),{...a('test','q2','richtig'),test_id:'exam'}];for(const row of rows)await x.r.saveAttempt(row);
 const p=await x.r.ensureModuleProgress('local',descriptor);expect(p.generation).toBe(1);expect(p.questionStates.q1.state).toBe('correct');expect(p.questionStates.q1.attempt_id).toBe('new');expect(p.questionStates.q2.state).toBe('unanswered');expect(summarizeProgress(p).completed).toBe(1);expect(summarizeProgress(p).rate).toBe(100);expect(await x.r.ensureModuleProgress('local',descriptor)).toEqual(p);expect(await x.r.getAttempts('local')).toEqual([...rows].sort((a,b)=>a.attempt_id.localeCompare(b.attempt_id)));
 }finally{await x.close()}});
it('reset creates a new run, preserves notes/history, rejects stale draft/answer, and never resurrects old results',async()=>{const x=setup();try{
 await x.r.saveAttempt(a('old','q1','falsch'));await x.r.saveLearningSession({userId:'local',question_id:'q2',draft:{note:'migrate before reset',choice:'1'},revealed:true});let p=await x.r.ensureModuleProgress('local',descriptor);const old=p;
 p=await x.r.resetModuleProgress('local',p.id,p.revision,p.run_id);expect(p.generation).toBe(2);expect(p.run_id).not.toBe(old.run_id);expect(summarizeProgress(p).completed).toBe(0);expect(summarizeProgress(p).rate).toBeNull();expect((await x.r.getQuestionNote('local','q2'))?.text).toBe('migrate before reset');expect(await x.r.getAttempts('local')).toHaveLength(1);expect((await x.r.getLearningSessions('local')).every(s=>!s.revealed&&!s.attempt_id&&Object.keys(s.draft).length===0)).toBe(true);
 await expect(x.r.savePracticeAttempt(a('stale','q3','richtig'),{userId:'local',question_id:'q3',draft:{},revealed:true},p.id,old.run_id)).rejects.toThrow();await expect(x.r.savePracticeSession({userId:'local',question_id:'q1',draft:{choice:'1'},revealed:false},p.id,old.run_id)).rejects.toThrow();
 await x.r.savePracticeAttempt(a('current','q3','richtig'),{userId:'local',question_id:'q3',draft:{choice:'1'},revealed:true},p.id,p.run_id);await x.r.deletePracticeAttempt('local',p.id,'old',p.run_id);const current=(await x.r.getModuleProgress('local')).find(v=>v.id===p.id)!;expect(current.questionStates.q1.state).toBe('unanswered');expect(current.questionStates.q3.state).toBe('correct');expect((await x.r.getModuleRuns('local')).length).toBe(2);
 }finally{await x.close()}});
it('deleting current source falls back only within same run; other history and notes survive',async()=>{const x=setup();try{
 let p=await x.r.ensureModuleProgress('local',descriptor);await x.r.saveQuestionNote('local','q1','permanent',0,'');await x.r.savePracticeAttempt(a('first','q1','falsch'),{userId:'local',question_id:'q1',draft:{},revealed:true},p.id,p.run_id);await x.r.savePracticeAttempt(a('second','q1','richtig','2026-02-01'),{userId:'local',question_id:'q1',draft:{},revealed:true},p.id,p.run_id);
 p=(await x.r.getModuleProgress('local'))[0];expect(summarizeProgress(p)).toMatchObject({completed:1,correct:1,incorrect:0});await x.r.deletePracticeAttempt('local',p.id,'second',p.run_id);expect((await x.r.getModuleProgress('local'))[0].questionStates.q1).toMatchObject({state:'incorrect',attempt_id:'first'});await x.r.deletePracticeAttempt('local',p.id,'first',p.run_id);expect((await x.r.getModuleProgress('local'))[0].questionStates.q1.state).toBe('unanswered');expect((await x.r.getQuestionNote('local','q1'))?.text).toBe('permanent');
 const snap=await x.r.exportSnapshot('local');await x.r.importSnapshot(snap,'copy',false);expect((await x.r.exportSnapshot('copy')).moduleProgress).toEqual(snap.moduleProgress?.map(v=>({...v,userId:'copy'})));expect((await x.r.exportSnapshot('copy')).moduleRuns).toEqual(snap.moduleRuns?.map(v=>({...v,userId:'copy'})));
 }finally{await x.close()}});

it('old backup import after reset cannot repopulate current states; incomplete run backup is atomic',async()=>{const x=setup();try{
 await x.r.saveAttempt(a('old','q2','richtig'));const legacy=await x.r.exportSnapshot('local');let p=await x.r.ensureModuleProgress('local',descriptor);p=await x.r.resetModuleProgress('local',p.id,p.revision,p.run_id);await x.r.importSnapshot(legacy,'local',false);expect(summarizeProgress((await x.r.getModuleProgress('local'))[0]).completed).toBe(0);
 const snapshot=await x.r.exportSnapshot('local');await expect(x.r.importSnapshot({...snapshot,moduleRuns:[]},'bad',false)).rejects.toThrow('Lernrunde');expect(await x.r.getAttempts('bad')).toEqual([]);expect(await x.r.getModuleProgress('bad')).toEqual([]);
 }finally{await x.close()}});
it('U partial and invalid incomplete assessments, scope isolation, and reset/submit race',async()=>{const x=setup();try{
 let p=await x.r.ensureModuleProgress('local',descriptor);const other=await x.r.ensureModuleProgress('local',{exam:'other',module:'funktionsanalyse',question_ids:['other-q']});
 const partial={...a('u','u1','teilweise'),self_assessed:true,auto_scored:false,subparts:[{id:'1',user_answer:'answer',correctness:'teilweise' as const,self_assessed:true as const,auto_scored:false as const}]};await x.r.savePracticeAttempt(partial,{userId:'local',question_id:'u1',draft:{},revealed:true},p.id,p.run_id);p=(await x.r.getModuleProgress('local')).find(v=>v.id===p.id)!;expect(summarizeProgress(p)).toMatchObject({partial:1,completed:1,rate:0});
 const invalid={...partial,attempt_id:'incomplete',subparts:[]};await x.r.savePracticeAttempt(invalid,{userId:'local',question_id:'u1',draft:{},revealed:true},p.id,p.run_id);expect((await x.r.getModuleProgress('local')).find(v=>v.id===p.id)?.questionStates.u1.attempt_id).toBe('u');
 p=(await x.r.getModuleProgress('local')).find(v=>v.id===p.id)!;const result=await Promise.allSettled([x.r.resetModuleProgress('local',p.id,p.revision,p.run_id),x.r.savePracticeAttempt(a('race','q1','richtig'),{userId:'local',question_id:'q1',draft:{},revealed:true},p.id,p.run_id)]);expect(result.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await x.r.getModuleProgress('local')).find(v=>v.id===other.id)).toEqual(other);
 await expect(x.r.deletePracticeAttempt('local',other.id,'u',other.run_id)).rejects.toThrow();await expect(x.r.savePracticeAttempt({...a('exam','q1','richtig'),test_id:'test'},{userId:'local',question_id:'q1',draft:{},revealed:true},p.id,p.run_id)).rejects.toThrow();
 }finally{await x.close()}});

it('free attempt deletion rejects all linked exam/test history',async()=>{const x=setup();try{const p=await x.r.ensureModuleProgress('local',descriptor);for(const link of ['test_id','test_session_id','exam_session_id']){const linked={...a(link,'q1','richtig'),[link]:'test'};await x.r.saveAttempt(linked);await expect(x.r.deletePracticeAttempt('local',p.id,link,p.run_id)).rejects.toThrow();expect((await x.r.getAttempts('local')).some(a=>a.attempt_id===link)).toBe(true);}}finally{await x.close()}});
