import ExternalAttachments from '../learning/ExternalAttachments';
import OfficialCorrection from '../learning/OfficialCorrection';
import QuestionNoteEditor from '../learning/QuestionNoteEditor';
import {contextPagesForQuestion} from '../learning/questionContext';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {asset,questionSources,questionSourceUrl,type SegmentedExam} from '../segmented/types';
import {CropImage} from '../segmented/CropImage';
import type {ProgressRepository} from '../types';
import {examLabel,originalPageLink,findModule,type ModuleConfig} from '../learning/modules';
import type {Correctness,USolution} from '../learning/model';
import {elapsedMs,sessionResult,type TestSession} from './model';
import RecordLifecycle from './RecordLifecycle';
import './exams.css';

type SessionAction=Parameters<ProgressRepository['updateTestSession']>[3];
const time=(ms:number)=>{const seconds=Math.max(0,Math.floor(ms/1000));return `${Math.floor(seconds/3600).toString().padStart(2,'0')}:${Math.floor(seconds/60)%60<10?'0':''}${Math.floor(seconds/60)%60}:${String(seconds%60).padStart(2,'0')}`;};
export default function ExamWorkspace({initialSession,config,exam,solutions,repository,onUpdated,onBusy,onDeleted}:{initialSession:TestSession;config:ModuleConfig;exam:SegmentedExam;solutions:USolution[];repository:ProgressRepository;onUpdated:(session:TestSession)=>void;onBusy:(busy:boolean)=>void;onDeleted?:(id:string)=>void}){
 const [noteBusy,setNoteBusy]=useState(false);
 const [session,setSession]=useState(initialSession);const [lifecycleBusy,setLifecycleBusy]=useState(false);const [deleted,setDeleted]=useState(false);const currentSession=useRef(initialSession);
 const [drafts,setDrafts]=useState(initialSession.answers);const draftsRef=useRef(initialSession.answers);
 const [saving,setSaving]=useState(false);const [blocking,setBlocking]=useState(false);const locks=useRef(0);const count=useRef(0);const queue=useRef<Promise<void>>(Promise.resolve());const generation=useRef(0);
 const [error,setError]=useState('');const [confirm,setConfirm]=useState<'submit'|null>(null);const [now,setNow]=useState(Date.now());
 useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(count.current>0){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 useLayoutEffect(()=>{onBusy(saving||!!confirm||lifecycleBusy||noteBusy);},[saving,confirm,lifecycleBusy,noteBusy,onBusy]);useLayoutEffect(()=>()=>onBusy(false),[onBusy]);
 const apply=(next:TestSession)=>{currentSession.current=next;setSession(next);onUpdated(next);};
 const act=(action:SessionAction)=>{
  const batch=generation.current;const exclusive=action.type!=='answer';if(exclusive){locks.current++;setBlocking(true);}count.current++;setSaving(true);onBusy(true);setError('');
  queue.current=queue.current.then(async()=>{
   if(batch!==generation.current)return;
   try{const current=currentSession.current;const next=await repository.updateTestSession(current.userId,current.test_id,current.revision,action);apply(next);}
   catch{
    generation.current++;setError('Nicht gespeichert: Die Sitzung wurde möglicherweise in einem anderen Tab geändert. Der neueste Stand wurde geladen. Bitte prüfe deine Eingabe und versuche es erneut.');
    try{const fresh=await repository.getTestSession(currentSession.current.userId,currentSession.current.test_id);if(fresh){apply(fresh);draftsRef.current=fresh.answers;setDrafts(fresh.answers);}else{setDeleted(true);onDeleted?.(currentSession.current.test_id);}}catch{setError('Der Speicher ist nicht erreichbar. Bitte diese Seite geöffnet lassen und erneut versuchen.');}
   }
  }).finally(()=>{if(exclusive){locks.current--;if(!locks.current)setBlocking(false);}count.current--;if(!count.current){setSaving(false);onBusy(false);}});
 };
 const answer=(key:string,value:string)=>{const id=session.current_question;const next={...draftsRef.current,[id]:{...draftsRef.current[id],[key]:value}};draftsRef.current=next;setDrafts(next);act({type:'answer',questionId:id,answer:next[id]});};
 const index=session.question_ids.indexOf(session.current_question);const id=session.current_question;const q=session.source_mix.find(s=>s.question_id===id)?.question_snapshot??exam.questions.find(q=>q.question_id===id);const model=session.question_models[id];
 const submitted=session.status==='completed';const paused=session.status==='paused';const active=session.status==='active';const u=solutions.find(u=>u.question_id===id);const source=session.source_mix.find(s=>s.question_id===id);
 const questionConfig=findModule(source?.exam??session.exam,source?.module??session.module)??config;const sourceExam=source?.exam??session.exam;const mixed=new Set(session.source_mix.map(s=>s.exam)).size>1;
 const sourceLabel=(qid:string)=>{const origin=session.source_mix.find(s=>s.question_id===qid);return examLabel(origin?.exam??session.exam);};
 const lifecycle=<RecordLifecycle session={session} repository={repository} disabled={saving||!!confirm||noteBusy} onBusy={setLifecycleBusy} onUpdated={next=>{apply(next);draftsRef.current=next.answers;setDrafts(next.answers);}} onDeleted={id=>{setDeleted(true);onDeleted?.(id);}}/>;
 const spent=elapsedMs(session,now);const remaining=session.duration_minutes===null?null:session.duration_minutes*60000-spent;
 const answered=session.question_ids.filter(qid=>Object.values(drafts[qid]??{}).some(v=>v.trim())).length;
 const result=submitted?sessionResult(session):null;
 if(deleted)return <section className="exam-workspace" role="status"><h1>Versuch gelöscht</h1><p>Der Versuch wurde dauerhaft entfernt. Freie Lernfortschritte und andere Versuche bleiben erhalten.</p></section>;
 if(session.status==='discarded'||session.status==='abandoned')return <section className="exam-workspace"><h1>{session.status==='discarded'?'Versuch verworfen':'Versuch beendet'}</h1><p>Dieser Versuch wird nicht in Auswertungen berücksichtigt und kann nicht fortgesetzt werden.</p>{lifecycle}</section>;
 if(!q||!model)return <p role="alert">Die gespeicherte Aufgabe ist in diesem Modul nicht verfügbar.</p>;
 return <section className="exam-workspace" aria-label="Prüfungssitzung">
  <div className="session-heading"><div><span className="eyebrow">{mixed?'Mehrere Prüfungszeiträume':examLabel(session.exam)} · {config.title}</span><h1>{session.test_type==='original'?'Originalprüfung':`Modultest · ${session.mode==='kurz'?'Kurz':'Standard'}`}</h1><p>{session.question_ids.length} Aufgaben · {answered} beantwortet · {submitted?'Abgegeben':paused?'Pausiert':active?'In Bearbeitung':'Verworfen'}</p></div><div className="session-clock"><strong data-testid="elapsed-time">{time(spent)}</strong><span>Bearbeitungszeit</span>{remaining!==null&&<small>{remaining>0?`Verbleibend: ${time(remaining)}`:(active?'Zeit abgelaufen · Du kannst weiterarbeiten':'Zeitvorgabe überschritten')}</small>}</div></div>
  {session.test_type==='module'&&<p className="hint">Übungstest aus Originalaufgaben · {[...new Set(session.source_mix.map(s=>examLabel(s.exam)))].join(" + ")} · Auswahlkennung: {session.seed}</p>}
  {session.test_type==='original'&&<p className="hint">{session.duration_minutes===null?'Prüfungszeit noch nicht bestätigt.':`Richtzeit ${session.duration_minutes} Minuten für ${config.parts.map(p=>p.title).join(" und ")}.`} Der Timer läuft bis zur Pause oder Abgabe weiter. {config.durationSource&&<a href={config.durationSource.image?asset(config.durationSource.image):asset(config.durationSource.pdf)+`#page=${config.durationSource.page}`} target="_blank" rel="noreferrer">Zeitvorgabe · Original Seite {config.durationSource.page} ↗</a>}</p>}
  {remaining!==null&&remaining<=0&&active&&<p className="session-warning" role="status">Die Richtzeit ist erreicht. Deine Antworten bleiben erhalten; die Abgabe erfolgt nur durch dich.</p>}
  {error&&<p className="session-warning" role="alert">{error}</p>}
  {result&&<section className="session-results" aria-label="Ergebnis"><h2>{result.vorlaeufig?'Vorläufiges Ergebnis':'Ergebnis'}</h2><p>Aufgabenzählung zur Übung, keine offizielle gewichtete Prüfungsnote.</p><div className="result-counts">{[['Richtig',result.richtig],['Falsch',result.falsch],['Teilweise',result.teilweise],['Unbeantwortet',result.unbeantwortet],['Bewertung offen',result.pending]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>{result.pending>0&&<p>Offene Aufgaben bleiben bis zu deiner Selbstbewertung unbewertet. Fehlende Antworten zählen als unbeantwortet.</p>}</section>}
  {paused?<section className="session-pause"><h2>Sitzung pausiert</h2><p>Antworten und Zeit sind gespeichert. Während der Pause werden keine Aufgaben angezeigt.</p><button className="primary" disabled={saving||lifecycleBusy} onClick={()=>act({type:'resume'})}>Sitzung fortsetzen</button></section>:
  <><nav className="learning-question-nav" aria-label="Prüfungsaufgaben">{session.question_ids.map((qid,i)=><button key={qid} disabled={saving||lifecycleBusy||noteBusy||!!confirm} aria-label={`Prüfungsaufgabe ${session.question_models[qid].number}${mixed?` · ${sourceLabel(qid)} · Position ${i+1}`:""}`} title={`${sourceLabel(qid)} · Aufgabe ${session.question_models[qid].number}`} aria-current={qid===id?'true':undefined} onClick={()=>act({type:'move',questionId:qid})}>{session.question_models[qid].number}{Object.values(drafts[qid]??{}).some(v=>v.trim())?' •':''}<span className="sr-only"> Position {i+1}</span></button>)}</nav>
  <section className="reader session-question"><div className="reader-head"><h2>Aufgabe {model.number}</h2><span>{examLabel(sourceExam)} · {questionConfig.title} · </span><span>{index+1} / {session.question_ids.length}</span></div><CropImage question={q} edited={false}/>
   <ExternalAttachments items={questionConfig.externalAttachments} number={model.number}/>
   {contextPagesForQuestion(questionConfig,model.number,model.kind==='multi_part').length>0&&<details className="session-attachments"><summary>{questionConfig.descriptionLabel??'Aufgabenbeschreibung'} und Anlagen</summary>{contextPagesForQuestion(questionConfig,model.number,model.kind==='multi_part').includes(questionConfig.descriptionPage)&&<a href={originalPageLink(questionConfig,q.source_pdf,questionConfig.descriptionPage)} target="_blank" rel="noreferrer">{questionConfig.descriptionLabel??'Aufgabenbeschreibung'} ↗</a>}{contextPagesForQuestion(questionConfig,model.number,model.kind==='multi_part').filter(page=>page!==questionConfig.descriptionPage).map(page=><p key={page}><a href={originalPageLink(questionConfig,q.source_pdf,page)} target="_blank" rel="noreferrer">Anlage · Seite {page} ↗</a></p>)}</details>}
   <div className="practice"><h3>Deine Antwort</h3>{model.kind==='multiple_choice'?<fieldset className="choice-options" disabled={!active||!!confirm||blocking||lifecycleBusy}><legend>Wähle eine Antwort</legend>{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name={'test-'+id} checked={drafts[id]?.choice===String(n)} onChange={()=>answer('choice',String(n))}/>{n}</label>)}</fieldset>:<div className="subparts">{model.subpart_ids.map(part=>{const p=(model.subpart_models??u?.subparts)?.find(p=>p.id===part);return <fieldset key={part} disabled={!active||!!confirm||blocking||lifecycleBusy}><legend>{p?.label??`Teilaufgabe ${part}`}</legend><textarea rows={3} aria-label={`Prüfung ${model.number} Teil ${part}`} value={drafts[id]?.[part]??''} onChange={e=>answer(part,e.target.value)}/>{p?.type==='drawing'&&active&&<button className="outline" onClick={()=>answer(part,(drafts[id]?.[part]??'')+' Auf Papier gezeichnet.')}>Auf Papier gezeichnet</button>}</fieldset>;})}</div>}
   {submitted&&<section className="submitted-answer"><p className="hint">Quelle: {examLabel(sourceExam)} · {questionConfig.title} · Aufgabe {model.number} · Originalseite {source?.source_page}. Der Lösungsschlüssel wurde beim Start dieses Versuchs gespeichert.</p>{source&&<div className="source-links">{questionSources(q).map(page=><a key={page.source_page} href={questionSourceUrl(q,page)} target="_blank" rel="noreferrer">Originalaufgabe · {q.source_pdf_available===false?'Seite':'PDF-Seite'} {page.source_page} ↗</a>)}</div>}<h3>{result?.byQuestion[id]==='pending'?'Bewertung offen':result?.byQuestion[id]==='unbeantwortet'?'Unbeantwortet':result?.byQuestion[id]==='richtig'?'Richtig':result?.byQuestion[id]==='falsch'?'Falsch':'Teilweise richtig'}</h3>{model.kind==='multiple_choice'?<><p>Offizielle Antwort: {session.official_answers[id]??'noch nicht eindeutig'}</p>{source?.answer_source_crop&&<img className="mc-source" src={asset(source.answer_source_crop)} alt={`Offizielle Antwortquelle Q${model.number}`}/>} {source?.answer_source_pdf&&<a href={asset(source.answer_source_pdf)+`#page=${source.answer_source_page}`} target="_blank" rel="noreferrer">Offizielle Antwortquelle ↗</a>}</>:<><OfficialCorrection questionId={id}/><h3>Offizielle Lösung · {model.number}</h3>{source?.solution_image&&<img className="u-solution-image" src={asset(source.solution_image)} alt={`Offizielle Lösung ${model.number}`}/>}<p>{source?.answer_source_pdf&&<a href={asset(source.answer_source_pdf)+`#page=${source.answer_source_page}`} target="_blank" rel="noreferrer">Offizielle Lösung · PDF-Seite {source.answer_source_page} ↗</a>}</p><p>Vergleiche selbst mit der offiziellen Lösung. Deine Bewertung entscheidet; sie ist später änderbar.</p>{Object.values(drafts[id]??{}).some(v=>v.trim())?model.subpart_ids.map(part=><label className="part-assessment" key={part}>Teilaufgabe {part} <select aria-label={`Prüfung ${model.number} Bewertung ${part}`} disabled={saving||lifecycleBusy} value={session.subpart_assessments[id]?.[part]??''} onChange={e=>act({type:'assess',questionId:id,assessments:{...session.subpart_assessments[id],[part]:e.target.value as Correctness}})}><option value="" disabled>Bitte selbst bewerten</option><option value="richtig">richtig</option><option value="teilweise">teilweise richtig</option><option value="falsch">falsch</option></select></label>):<p>Keine Antwort abgegeben: unbeantwortet.</p>}</>}</section>}
   {submitted&&<details><summary>Notiz ansehen / bearbeiten</summary><QuestionNoteEditor key={session.userId+':'+id} questionId={id} onBusy={setNoteBusy}/></details>}
   </div></section><div className="study-pagination"><button disabled={saving||lifecycleBusy||noteBusy||!!confirm||index<=0} onClick={()=>act({type:'move',questionId:session.question_ids[index-1]})}>← Vorherige Aufgabe</button><button disabled={saving||lifecycleBusy||noteBusy||!!confirm||index>=session.question_ids.length-1} onClick={()=>act({type:'move',questionId:session.question_ids[index+1]})}>Nächste Aufgabe →</button></div></>}
  {active&&<div className="session-actions"><button className="outline" disabled={saving||lifecycleBusy} onClick={()=>act({type:'pause'})}>Pausieren</button><button className="primary" disabled={saving||lifecycleBusy} onClick={()=>setConfirm('submit')}>Prüfung abgeben</button></div>}
  {confirm&&<section className="session-confirm" role="alertdialog" aria-label={confirm==='submit'?'Abgabe bestätigen':'Verwerfen bestätigen'}><h2>{confirm==='submit'?'Prüfung jetzt abgeben?':'Sitzung wirklich verwerfen?'}</h2><p>{confirm==='submit'?`${session.question_ids.length-answered} Aufgaben sind noch unbeantwortet. Nach der Abgabe sind Antworten nicht mehr änderbar; offene Aufgaben bewertest du selbst.`:'Der bisherige Verlauf bleibt erhalten. Diese Sitzung kann danach nicht fortgesetzt werden.'}</p><button className="primary" disabled={saving||lifecycleBusy} onClick={()=>{const type=confirm;setConfirm(null);act({type});}}>{confirm==='submit'?'Jetzt abgeben':'Verwerfen bestätigen'}</button><button className="outline" disabled={saving||lifecycleBusy} onClick={()=>setConfirm(null)}>Abbrechen</button></section>}
  {lifecycle}<p className="save-status" role="status">{saving?'Speichert…':'Sitzung gespeichert'} · ID {session.test_id}</p>
 </section>;
}
