import {useState} from 'react';
import type {ProgressRepository} from '../types';
import {examLabel,findModule,EXAM_SESSIONS} from '../learning/modules';
import {isEligibleForAnalysis,sessionResult,type TestSession,type TestType} from './model';
import {DEFAULT_HISTORY_FILTERS,HISTORY_PAGE_SIZE,filterHistory,historyPage,sessionExams,type HistoryFilters} from './history';
import RecordLifecycle from './RecordLifecycle';
export interface HistoryViewProps {sessions:TestSession[];repository:ProgressRepository;disabled?:boolean;initialType?:TestType;initialExam?:string;onOpen:(session:TestSession)=>void;onUpdated:(session:TestSession)=>void;onDeleted:(id:string)=>void;onBusy?:(busy:boolean)=>void}
const statusLabel=(s:TestSession)=>s.status==='active'?'Laufend':s.status==='paused'?'Pausiert':s.status==='completed'?'Abgeschlossen':s.status==='discarded'?'Verworfen':'Abgebrochen';
export default function HistoryView({sessions,repository,disabled=false,initialType,initialExam,onOpen,onUpdated,onDeleted,onBusy}:HistoryViewProps){
 const [filters,setFilters]=useState<HistoryFilters>({...DEFAULT_HISTORY_FILTERS,type:initialType??'all',exam:initialExam??'all'});const [visible,setVisible]=useState(HISTORY_PAGE_SIZE);const [archiveVisible,setArchiveVisible]=useState(HISTORY_PAGE_SIZE);const [showArchive,setShowArchive]=useState(false);
 const change=(next:Partial<HistoryFilters>)=>{setFilters({...filters,...next});setVisible(HISTORY_PAGE_SIZE);setArchiveVisible(HISTORY_PAGE_SIZE);};
 const years=[...new Set([...EXAM_SESSIONS.map(e=>e.id),...sessions.flatMap(sessionExams)])].sort();const normal=filterHistory(sessions,filters);const archive=filterHistory(sessions,filters,{archive:true});const expanded=showArchive||filters.status==='archived';
 const row=(s:TestSession)=>{const result=isEligibleForAnalysis(s)?sessionResult(s):null;return <article key={s.test_id} data-test-id={s.test_id}><div><h3>{findModule(s.exam,s.module)?.title??s.module} · {s.test_type==='original'?'Originalprüfung':`Modultest ${s.mode}`}</h3><p>{sessionExams(s).map(examLabel).join(' + ')}</p><p>{new Date(s.started_at).toLocaleString('de-DE')} · {statusLabel(s)}{result?` · ${result.richtig} richtig · ${result.falsch} falsch · ${result.pending} offen`:''}</p></div><div className="record-actions">{['active','paused','completed'].includes(s.status)&&<button className="primary" disabled={disabled} onClick={()=>onOpen(s)}>{s.status==='completed'?'Ergebnis ansehen':'Fortsetzen'}</button>}<RecordLifecycle compact session={s} repository={repository} disabled={disabled} onUpdated={onUpdated} onDeleted={onDeleted} onBusy={onBusy}/></div></article>;};
 return <section className="test-history" aria-label="Prüfungsverlauf"><h2>Prüfungsverlauf</h2><div className="history-filters"><label>Typ <select aria-label="Verlauf Typ" disabled={disabled} value={filters.type} onChange={e=>change({type:e.target.value as HistoryFilters['type']})}><option value="all">Alle</option><option value="original">Originalprüfung</option><option value="module">Modultest</option></select></label><label>Jahrgang <select aria-label="Verlauf Jahrgang" disabled={disabled} value={filters.exam} onChange={e=>change({exam:e.target.value})}><option value="all">Alle Jahre</option>{years.map(year=><option key={year} value={year}>{examLabel(year)}</option>)}</select></label><label>Status <select aria-label="Verlauf Status" disabled={disabled} value={filters.status} onChange={e=>change({status:e.target.value as HistoryFilters['status']})}><option value="all">Alle</option><option value="completed">Abgeschlossen</option><option value="active">Laufend</option><option value="paused">Pausiert</option><option value="archived">Archiviert</option></select></label></div>
 {filters.status!=='archived'&&<section className="session-history" aria-label="Normale Versuche">{normal.length?historyPage(normal,visible).map(row):<p>Keine passenden Versuche.</p>}{visible<normal.length&&<button className="outline" disabled={disabled} onClick={()=>setVisible(n=>n+HISTORY_PAGE_SIZE)}>Mehr anzeigen</button>}<p className="hint">{Math.min(visible,normal.length)} von {normal.length} Versuchen</p></section>}
 <section className="discarded-history"><button className="outline" disabled={disabled} aria-expanded={expanded} onClick={()=>{if(filters.status==='archived')change({status:'all'});setShowArchive(!expanded);}}>Archivierte / verworfene Versuche {expanded?'ausblenden':'anzeigen'}</button>{expanded&&<section className="session-history" aria-label="Archivierte Versuche">{archive.length?historyPage(archive,archiveVisible).map(row):<p>Keine passenden archivierten Versuche.</p>}{archiveVisible<archive.length&&<button className="outline" disabled={disabled} onClick={()=>setArchiveVisible(n=>n+HISTORY_PAGE_SIZE)}>Mehr archivierte anzeigen</button>}<p className="hint">{Math.min(archiveVisible,archive.length)} von {archive.length} archivierten Versuchen</p></section>}</section></section>;
}
